### ISSUE TITLE
[BottomNavigationView] Part of badge still remaining when remove badge

### ISSUE THREAD

**Issue by mucahidkambur** [material-components/material-components-android#1002]
**Description:** When trying to clean badge with removeBadge(), to top of the badge is still remaining.

**Expected behavior:** ![](https://image.prntscr.com/image/mTViXc8wRkOMv4DLXpsjfA.png)

**Android API version:** 28

**Material Library version:** 1.2.0-alpha01 - 1.2.0-alpha04

**Device:** Redmi Note 8 Pro

**Comment by wcshi** [comment]
@mucahitkambur thank you for reporting the issue, do you have repro steps or a sample app that you could share?

**Comment by mucahitkambur** [comment]
I tried it with simple app, it works fine but when i try it in our big project it occure.

**Comment by wcshi** [comment]
Is it consistently reproducible in your app?

**Comment by mucahitkambur** [comment]
I did not understand what you said

**Comment by wcshi** [comment]
I'm trying to ask if it always happens in your app?

**Comment by mucahitkambur** [comment]
In version alpha 02-03-04 always happening with all devices. But in alpha01 it happens randomly.

**Comment by wcshi** [comment]
Could you please try calling badge.setVisible(false) to hide the badge instead of removing it?

**Comment by mucahitkambur** [comment]
val bottomNavigationView: BottomNavigationView = binding.bnvHome
        val menuItemId: Int = bottomNavigationView.menu.getItem(2).itemId

        if (totalPendingTransactionsBadgeCount != 0) {
            bottomNavigationView.getOrCreateBadge(menuItemId).apply {
                isVisible = true
                number = totalPendingTransactionsBadgeCount
                backgroundColor = ContextCompat.getColor(requireContext(), R.color.papara_red)
            }
        } else {
            bottomNavigationView.getOrCreateBadge(menuItemId).apply {
                isVisible = false
            }
        }

I tried to hide but it's not hiding

**Comment by wcshi** [comment]
Could you please try 1.2 alpha 06?

**Comment by mucahidkambur** [comment]
Still remaining. Also i am not using React Native.

**Comment by grahammendick** [comment]
I should clarify why I referenced this issue. Although my library targets React Native, under the covers it uses the public Material Components api. I noticed the problem only happens if I change fragments.

1. The badge is on one tab in fragment A 
2. Replace fragment A with fragment B 
3. Go back to fragment A
4. Clear the badge then you get the problem

If you then go to fragment B and back to A again then the quarter-badge switches to a different tab

**Comment by wcshi** [comment]
Could either of you provide a small sample app that reproduces the issue? It would greatly help us debug. thanks!

**Comment by grahammendick** [comment]
I've tried to recreate it outside of my react native setup but had no luck. I did find a workaround that I want to run past you. I can clear the badge by finding the image and clearing the overlay. Can you see any problem with this?
```java
BottomNavigationItemView itemView = 
    (BottomNavigationItemView) findViewById(R.id.notificationsTab);
itemView.getChildAt(0).getOverlay().clear();
```

**Comment by wcshi** [comment]
Thanks for the update @grahammendick 

calling itemView.getChildAt(0).getOverlay().clear() currently has the same effect as calling BottomNavigationView#removeBadge

**Comment by grahammendick** [comment]
Thanks @wcshi but they didn't have the same effect for me. Calling removeBadge left part of the badge behind but clearing the overlay didn't.

**Comment by gtgray** [comment]
> I should clarify why I referenced this issue. Although my library targets React Native, under the covers it uses the public Material Components api. I noticed the problem only happens if I change fragments.
> 
> 1. The badge is on one tab in fragment A
> 2. Replace fragment A with fragment B
> 3. Go back to fragment A
> 4. Clear the badge then you get the problem
> 
> If you then go to fragment B and back to A again then the quarter-badge switches to a different tab

I have exactly the same problem in my project.
It also appears when I navigate from fragment A (with BottomNavigationView) to another one and then go back to fragment A. 
As far as I figured out this behavior is related to the **SavedState** of **BottomNavigationView**.
BadgeDrawables for the same tab (got with getOrCreateBadge) before and after navigating are different
but BadgeDrawable created after navigation doesn't replace one created before navigation.
So, if new badge cleared (with setVisible(false) or removeBadge) we would still see the old badge near the tab icon
(of course, it will be cut after removeBadge call because this method calls setClipChildren(true) for icon view under the hood)
That is why getOverlay().clear() workaround solves. It removes all badges - old one and new one as well.
Below picture shows unexpected 2 badges appeared for the same tab.
Red badge is created before navigating, Green on is created after navigating.
![image](https://user-images.githubusercontent.com/9328004/107499614-37369800-6ba6-11eb-91b1-9050f5795c1c.png)

Hope this can help debug this issue.

P.S.: As for now my workaround is to use android:saveEnabled="false" attribute for BottomNavigationView

**Comment by wcshi** [comment]
@gtgray thank you for the info, we considered called `getOverlay().clear()` but wanted to avoid clearing any additional overlays that a dev might be adding onto the badge icon / text label as well. Since that is a hypothetical use case and this is a real problem many devs are experiencing, I'll discuss with the team.

**Comment by drchen** [comment]
I think this has been fixed. Please feel free to reopen it if it's still happening with the latest library version.
