### ISSUE TITLE
[TextInputLayout] error ClickableSpan

### ISSUE THREAD

**Issue by bblackbelt** [material-components/material-components-android#1041]
I am setting a `ClicableSpannable` as error in `TextInputLayout`

**Expected behavior:**  the `click` function of the `ClickableSpan` should be called 
 
**Android API version:**  1.1.0-rc02

**Comment by bblackbelt** [comment]
after looking into the source code I find out that `movementMethod` is not applied to the `errorView` in the `indicatorViewControllerField`. I changed it through reflection and the `click()` gets correctly called

 javaClass.superclass?.getDeclaredField(IndicatorViewController)
```
            ?.let { indicatorViewControllerField ->
                indicatorViewControllerField.isAccessible = true
                val indicatorViewController = indicatorViewControllerField.get(this)
                indicatorViewController.javaClass.getDeclaredField(ErrorView).let { errorView ->
                    errorView.isAccessible = true
                    (errorView.get(indicatorViewController) as? TextView?)?.movementMethod =
                        LinkMovementMethod.getInstance()
                }
            }
```

**Comment by leticiarossi** [comment]
Our UX guidance regarding having links on an error message for text fields is that enough information should be provided before the error occurs, making a link to a long help article unnecessary. If the text entry requires such nuanced understanding then a help tip (possibly with a "learn more" link) should be provided before the text field, rather than waiting for the error to occur before informing users.

**Comment by bblackbelt** [comment]
Ok, so I guess it is going to be pointless to open a pull request exposing a method that changes the errorView behavior to make the link clickable? Should I keep relying on reflection?

**Comment by luangs7** [comment]
any updates about this one?
