### ISSUE TITLE
[Transition] Shared axis animation not working on Samsung S10

### ISSUE THREAD

**Issue by magnusvs** [material-components/material-components-android#1047]
**Description:** 

The Shared Axis animation (X,Y,Z) works great on my Pixel 3, however on a Samsung S10 the FadeThrough animation does not seem to work.

The visibility of the added fragment is not being animated. The new fragment background seems to go from alpha 0->1 with no animation.

Just because I'm curious, why is the library using android.transition and not androidx.transition?

**Expected behavior:** 
The animation should look more or less the same on the Samsung S10 as the Pixel 3.

**Source code:** 
The Material Components Catalog app reproduces this in the Shared Axis example.

**Android API version:** Android API version here

**Material Library version:** 1.2.0-alpha05)

**Device:** Samsung SM-G973F

**Comment by hunterstich** [comment]
Hey magnusvs,

Thanks for the feedback. I'll look into what's happening on Samsung and get back to you. 

As far as `android.transition` vs. `androidx.transition` goes - since we support Activity transitions, we had to use the framework Transition library instead of the AndroidX version. Window is only able to accept a Framework Transition. If this effects you negatively, it'd be great to hear about your use case.

**Comment by afohrman** [comment]
@magnusvs Which API level were you using on your Pixel 3 and your Samsung S10, and what behavior were you seeing for each? I'm investigating a bug that may be related where the MaterialFadeThrough demo is broken on API 22. Could you please attach a video of exactly what you're seeing?

**Comment by magnusvs** [comment]
@afohrman 
Pixel 3: Api 29 and works as expected
S10: Api 28 and attached gif shows how it looks

![s10-shared-axis](https://user-images.githubusercontent.com/9012452/76076725-b1769980-5f9f-11ea-9381-2adaf9750140.gif)
