### ISSUE TITLE
[Slider] Differentiate between displayed and settable range

### ISSUE THREAD

**Issue by carstenhag** [material-components/material-components-android#1147]
**Is your feature request related to a problem? Please describe.**
My use case is the following: The user should be prompted a slider with values from 0% to 100%. 

This relates to a battery level, therefore it makes no sense for the user to select anything below 5%. Setting the `valueFrom` property to 5% would be a possibility, but then the user may get confused why the value doesn't start at 0%.

**Describe the solution you'd like**
It would be really cool if I was able to set `valueMin`, `valueMax` as well as `valueFrom`, `valueTo`. Of course, the naming is not so easy in this case.  

**Describe alternatives you've considered**
Create an addOnChangeListener which catches any values below `MINIMUM_SLIDER_VALUE`, and sets the slider value back to `MINIMUM_SLIDER_VALUE`. Looks like this:

![slider](https://user-images.githubusercontent.com/3776997/77540313-1fc5c200-6ea3-11ea-82d9-e4ea29e84311.gif)

```kotlin
var sliderValue: Int
    get() = slider.value.toInt()
    set(value) {
        slider.value = value.toFloat()
    }

// ...

slider.addOnChangeListener { _, value, _ ->
    if (value < MINIMUM_SLIDER_VALUE) {
        sliderValue = MINIMUM_SLIDER_VALUE
    }
}
```

**Comment by wcshi** [comment]
Hi @carstenhag 
It sounds like you want to "disable" part of the range of the slider rather than change its bounds.

Feedback from our design team:
1. The use case is too specific for us to provide built-in support

2. Semantically, if you want to restrict the selectable values to be between 5% and 100%, it makes sense to set the ValueTo and ValueFrom of your slider to match
Setting the lower bound to 5%, with a brief explanation is better than disabling part of the scale
3. Alternatively, if the exact # isn't important, consider moving to a more qualitative scale: e.g. use a discrete slider where there are just a few "steps" for users to choose instead, 5%, 25%, 50%, 75% could be reasonable step options

**Comment by carstenhag** [comment]
Yes exactly, "disabling a part of the slider" is a better description of the feature request :). 

On 2: I can see both variants making sense, ultimately thus is what our requirement engineers wanted us to do :). We will perhaps user-test this in the future, maybe they find it more intuitive with there not being a disabled part. 

On 3: The user selects the current state of their electric car's battery  in %. We are using steps of 5%. Having 0% battery level makes no sense in this case, that's why we have added this restriction.

**Comment by chhatrasal09** [comment]
The feature requirement request by @carstenhag is a standard feature. 
When using the range slider we might need to allow the user to select a window value values between valueTo and valueFrom, like if you allow the user to choose 10s of audio from the 60s of audio, so it can be anywhere the windows should be of 10s. This feature is required in many scenarios. It would be helpful if you can add the feature request by @carstenhag.
