### ISSUE TITLE
[Tab Items] Tab Items does not work with View Binding, throws NPE

### ISSUE THREAD

**Issue by kaushalyap** [material-components/material-components-android#1162]
**Description:** 
Filing this in response to ja...@google.com comment on https://issuetracker.google.com/issues/145687658

> a....@tandu.it

> I have a view which contains some TabItem with an ID.
> When I try to generate my binding with .inflate() the app throws an NPE on those views. This happens on both Activity and Fragment.

> ja...@google.com : 

> My working theory is material library is doing something horrific like intercepting TabLayout.addView and not actually putting the views into the hierarchy synchronously.

> ja...@google.com :

> Indeed, that is the problem.
> 
> 2019-12-09 15:57:32.859 6425-6425/? I/System.out: FrameLayout ID:16908290
> 2019-12-09 15:57:32.859 6425-6425/? I/System.out:   LinearLayout ID:2131230917
> 2019-12-09 15:57:32.859 6425-6425/? I/System.out:     TabLayout ID:-1
> 2019-12-09 15:57:32.859 6425-6425/? I/System.out:       SlidingTabIndicator ID:-1
> 2019-12-09 15:57:32.859 6425-6425/? I/System.out:         TabView ID:-1
> 2019-12-09 15:57:32.859 6425-6425/? I/System.out:           ImageView ID:-1
> 2019-12-09 15:57:32.859 6425-6425/? I/System.out:           TextView ID:-1
> 2019-12-09 15:57:32.859 6425-6425/? I/System.out:         TabView ID:-1
> 2019-12-09 15:57:32.859 6425-6425/? I/System.out:           ImageView ID:-1
> 2019-12-09 15:57:32.859 6425-6425/? I/System.out:           TextView ID:-1
> 
> Please file a bug on the Google Material library that it should consider retaining the IDs if one was supplied.
> 
> I'll repurpose this issue for honoring our `tools:viewBindingIgnore` attribute on arbitrary XML nodes to at least work around the issue.

**Expected behavior:** Tab Items working with View Binding without throwing NPEs

**Source code:** 
Required source files could be found at https://issuetracker.google.com/issues/145687658

**Material Library version:**

> Android Material dependency: com.google.android.material:material:1.1.0-beta01

**Comment by carterhudson** [comment]
Also an issue opened here https://issuetracker.google.com/issues/152606440

**Comment by paour** [comment]
Still happening with `com.google.android.material:material:1.2.1`.

**Comment by reallysunny** [comment]
same here. Noticed on com.google.android.material:material:1.2.1 Any work around?

**Comment by Jennifer23078** [comment]
Try using view binding like this.
I faced and solved the same problem as you.
Never define tabitem in xml.
Even if I try findViewByid the NPE will pop up.
Add tabItem in kotlin.
Then you will be able to solve the problem.

fragmentHomebinding = FragmentHomeBinding.inflate(inflater,container,false)

fragmentHomebinding.tablayoutHomefrag.addTab(fragmentHomebinding.tablayoutHomefrag.newTab().setText(R.string.main_home_home))//

fragmentHomebinding.tablayoutHomefrag.addTab(fragmentHomebinding.tablayoutHomefrag.newTab().setText(R.string.main_home_best))//
        fragmentHomebinding.tablayoutHomefrag.addTab(fragmentHomebinding.tablayoutHomefrag.newTab().setText(R.string.main_home_event))//
        fragmentHomebinding.tablayoutHomefrag.addTab(fragmentHomebinding.tablayoutHomefrag.newTab().setText(R.string.main_home_timesale))//
        fragmentHomebinding.tablayoutHomefrag.addTab(fragmentHomebinding.tablayoutHomefrag.newTab().setText(R.string.main_home_guid))//

**Comment by dzzchao** [comment]
When will this bug be fixed?
Still happening with  1.3.0-rc01

**Comment by acugniere** [comment]
Still happening ... Nearly 1 year later. Someone has a workaround ?

**Comment by rupinderjeet** [comment]
@acugniere I am using `tools:viewBindingIgnore="true"` to skip these views. Then, I just use `findViewById` to access them.

Dirty workaround,  but this is all I have for now. I hope this gets fixed 🙏

**Comment by Dreft12** [comment]
Still happening, I found a workaround, try this: 

Go to your XML and search the ID that is generating the issue and delete its android:id

Use the TabLayout API in your class to access the TabItems.

**Comment by hunterstich** [comment]
I don't think this is something we plan on supporting since it would require a significant change in the way TabLayout manages each TabItem. `com.google.material.tab.TabItem` is used more as a struct that just tells TabLayout what `text`, `icon`, and `customLayout` a client would like for each tab. Using those parameters, `TabLayout`, by default, then inflates its own `TabView` that is what actually gets added to the `TabLayout` `ViewGroup`. If ids of `TabItems` are retained, data binding will generate a binding class that expects `TabItem`s but will find `TabView`s and throw a ClassCastException. This issue becomes more interesting/complicated when you're passing in custom layout for tabs.

If there's a way to override the view type given to a `TabItem` in the generated data binding class, that might be an option—I'm not aware of this being possible but @JakeWharton might have more info.

I would suggest sticking with @Dreft12's suggestion of using `binding.tabLayout.getTabAt(<index>)` which returns a [Tab](https://github.com/material-components/material-components-android/blob/master/lib/java/com/google/android/material/tabs/TabLayout.java#L2005), from which you can get/set the item's text, view, etc.

I'm going to close this for now, but feel free to re-open if there are thoughts/questions/suggestions.
