### ISSUE TITLE
[ShapeableImageView]Wrong with ShapeableImageView,when set the stroke size too large

### ISSUE THREAD

**Issue by ShowMeThe** [material-components/material-components-android#1173]
Description:If set the stroke size too large,it will show like the following pic</br>
<img src="https://user-images.githubusercontent.com/30461332/78227276-9d22af80-74ff-11ea-89cd-c0bf9aae50ef.jpg" width="200"/>

Source code:
MainActivity:
```
 iv.shapeAppearanceModel = ShapeAppearanceModel.builder()
            .setAllCornerSizes(ShapeAppearanceModel.PILL).build()
```
activity_main：
```
<com.google.android.material.imageview.ShapeableImageView
        android:id="@+id/iv"
        android:layout_width="200dp"
        android:layout_height="200dp"
        app:strokeColor="@color/colorAccent"
        android:src="@mipmap/ic_launcher"
        app:strokeWidth="20dp"
        />
```
Android API version: 29
Material Library version: 'com.google.android.material:material:1.2.0-alpha05'

**Comment by wcshi** [comment]
What's the expected behavior? That the strokes are not clipped?

**Comment by ymarian** [comment]
@ShowMeThe Hi unfortunately I don't see an easy way to solve this, since the shape can be anything. It's not obvious how much the stroke will be outside the bounds. So as a workaround you can solve this by adding the necessary padding for your shape. For a circle since your stroke is 20dp adding `android:padding="10dp"` should solve your issue.
