### ISSUE TITLE
[BottomNavigationView] Custom animations with Navigation Component

### ISSUE THREAD

**Issue by kikasik** [material-components/material-components-android#1194]
**Problem:** 
Can't set the custom animations to Navigation Actions when using BottomNavigationView with Navigation Component by normal way:
`bottomNavigationView.setupWithNavController(navController)`

**Expected behavior:** 
Using animations from navigation graph of nav controller, or give us the way to pass NavOptions with our default animations to `NavigationUI.setupWithNavController(bottomNavigationView, navController)` method. 

**Source code:** 

*NavigationUI.java line 74* 

Force setting default animations to all navigations:

```Java
public static boolean onNavDestinationSelected(@NonNull MenuItem item,
            @NonNull NavController navController) {
        NavOptions.Builder builder = new NavOptions.Builder()
                .setLaunchSingleTop(true)
                .setEnterAnim(R.anim.nav_default_enter_anim)
                .setExitAnim(R.anim.nav_default_exit_anim)
                .setPopEnterAnim(R.anim.nav_default_pop_enter_anim)
                .setPopExitAnim(R.anim.nav_default_pop_exit_anim);
        if ((item.getOrder() & Menu.CATEGORY_SECONDARY) == 0) {
            builder.setPopUpTo(findStartDestination(navController.getGraph()).getId(), false);
        }
        NavOptions options = builder.build();
        try {
            //TODO provide proper API instead of using Exceptions as Control-Flow.
            navController.navigate(item.getItemId(), null, options);
            return true;
        } catch (IllegalArgumentException e) {
            return false;
        }
    }
```

Method `NavigationUI.setupWithNavController(bottomNavigationView, navController)` does many work for us! Just only one thing left - **Animations**!

**Comment by hunterstich** [comment]
Hey there. 
Thanks for filing an issue. This is actually a feature request for the Navigation Architecture Component which they are currently tracking and working on. Feel free to file a bug with AndroidX Arch here - https://b.corp.google.com/issues?q=componentid%3D197448%20status:open&s=modified_time:desc

In the meantime, you'd need to manually configure you're BottomNavigationView with a listener and then navigate yourself without using any enter/exit/popenter/popexit animation NavOptions and instead set transitions on your start/end Fragments. 

Let me know if this makes sense.

Since this isn't owned by our team, I'm going to go ahead and close this.
