### ISSUE TITLE
[Bottom Sheet] Can't drag out nav drawer on top of bottom sheet

### ISSUE THREAD

**Issue by ColtonIdle** [material-components/material-components-android#1221]
**Description:** I can't drag out the nav drawer onto a bottom sheet

**Expected behavior:** Allow me to do so, even if it takes some kind of configuration on the navigation drawer or bottom sheet.

Reproducible here: https://github.com/ColtonIdle/NavDrawerIssue

**Comment by dsn5ft** [comment]
Hi @ColtonIdle, can you show a screenshot or video of this issue?

Is it because the bottom sheet dialog is modal and has a higher elevation than the nav drawer?

**Comment by ColtonIdle** [comment]
@dsn5ft correct. The bottom sheet has a higher elevation than the drawer. Is there a way to change this?

![four](https://user-images.githubusercontent.com/31751141/79906386-b1164e80-83e5-11ea-9685-9791da64e7b6.gif)

**Comment by dsn5ft** [comment]
Oh now I see what you mean with the GIF. `BottomSheetDialogFragment` is meant to be [modal](https://material.io/develop/android/components/bottom-sheet-dialog-fragment/), meaning it needs to be interacted with first in order to interact with anything else.

For this case I'd recommend trying to use `BottomSheetBehavior` which is [not modal](https://material.io/develop/android/components/bottom-sheet-behavior/).

**Comment by ColtonIdle** [comment]
Is there any chance that there's some configuration on a fragment to change the behavior. For a few reasons, we can't move away from BottomSheetDialogFragment. Some constructor param or elevation attribute?

**Comment by dsn5ft** [comment]
I'm not sure. Now that I see you're using BottomSheetDialogFragment, I don't think it's just an elevation issue. The dialog fragment adds a new Window on top of the current fragment, so that's what is intercepting the touch events. Maybe you can experiment with setting the [FLAG_NOT_TOUCH_MODAL flag](https://developer.android.com/reference/android/view/WindowManager.LayoutParams#FLAG_NOT_TOUCH_MODAL) on the Window.

**Comment by ColtonIdle** [comment]
I've never dealt with window flags but I will try that out. Thank you!

**Comment by ColtonIdle** [comment]
After 2 hours of trying, I wasn't able to figure it out. I'm going to quit on this for now, but if anyone figures out how to do this, please leave a comment!
