### ISSUE TITLE
[MaterialAlertDialog] Button theming broken on 1.2.0-alpha06 for Bridge theme

### ISSUE THREAD

**Issue by rlatapy-luna** [material-components/material-components-android#1234]
**Description:** Full description of issue here
AlertDialog theming seems broken in 1.2.0-alpha06 with Bridge theme.

**Expected behavior:**
|alpha05 + bridge|alpha06 + bridge|alpha06 (expected behavior)|
|:--:|:--:|:--:|
|![image](https://user-images.githubusercontent.com/45555889/80015461-0def3300-84d2-11ea-9f98-1ff2b53c0242.png)|![image](https://user-images.githubusercontent.com/45555889/80015336-da140d80-84d1-11ea-881d-d6a330303372.png)|![image](https://user-images.githubusercontent.com/45555889/80015368-e8fac000-84d1-11ea-9b3f-84289447aa24.png)|

With `backgroundTint` I can manage to have the correct color with alpha05 + bridge but not with alpha06 + bridge

**Source code:**  https://github.com/rlatapy-luna/dialogbuttonstyleissue

```
<style name="AppTheme" parent="Theme.MaterialComponents.DayNight.NoActionBar.Bridge">
    <item name="materialAlertDialogTheme">@style/ThemeOverlay.Custom.MaterialAlertDialog</item>
</style>
<style name="ThemeOverlay.Custom.MaterialAlertDialog" parent="ThemeOverlay.MaterialComponents.MaterialAlertDialog">
    <item name="buttonBarPositiveButtonStyle">@style/Widget.MaterialComponents.Button</item>
    <item name="buttonBarNeutralButtonStyle">@style/Widget.MaterialComponents.Button.OutlinedButton</item>
</style>

```
**Android API version:** 29

**Material Library version:** 1.2.0-alpha06

**Device:** Pixel 3XL

**Comment by gabrielemariotti** [comment]
I am not sure that it is a bug.
You are using a `Bridge` theme and it means that each button is a  `AppCompatButton` instead of a `MaterialButton`.

<img width="459" alt="Schermata 2020-08-15 alle 20 54 23" src="https://user-images.githubusercontent.com/2583078/90319839-66908300-df3c-11ea-9a64-e08cd85198c2.png">

You can't use an `OutlinedButton` or a `Filled` style with an `AppCompatButton` since some attributes are not used.

**Comment by drchen** [comment]
It seems we can close the issue. : )
