### ISSUE TITLE
[Motion] Help me fix this.MaterialContainerTransform beetween Activities

### ISSUE THREAD

**Issue by Magicontrol** [material-components/material-components-android#1274]
Description: I want to make a transition between Activities by clicking on an item from the list, but the transition seems to be broken.
[Screenrecorder-2020-05-05-12-06-33-98.mp4.zip](https://github.com/material-components/material-components-android/files/4579964/Screenrecorder-2020-05-05-12-06-33-98.mp4.zip)

Source code: [Uploading SF2Shop.zip…]()

Android API version: 29

Material Library version: com.google.android.material:material:1.2.0-alpha06

Device: Xiaomi Redmi Note 7

**Comment by dsn5ft** [comment]
Hi @Magicontrol, your source code zip link doesn't seem to be working. It might be easier for us if you create a GitHub repo with your project.

**Comment by Magicontrol** [comment]
> Hi @Magicontrol, your source code zip link doesn't seem to be working. It might be easier for us if you create a GitHub repo with your project.

[SF2Shop.zip](https://github.com/material-components/material-components-android/files/4583049/SF2Shop.zip) Try it again

**Comment by dsn5ft** [comment]
I'm not exactly sure what the problem is, but it looks like `android.R.id.content` from the `ItemContentActivityKotlin` is somehow becoming both the start and end view for the MaterialContainerTransform.

I think it partially has to do with not having unique transition names for the cards in your recyclerview. I made the the transition names random strings, and also moved the `makeSceneTransitionAnimation(...)` and `new Intent(...)` into the click listener. It's slightly better but not completely fixed, not sure what else is wrong but maybe something with the recyclerview binding.

**Comment by dsn5ft** [comment]
Maybe this guide will help:

https://mikescamell.com/shared-element-transitions-part-4-recyclerview
