### ISSUE TITLE
[MaterialCheckBox] Ripples are red on Lollipop

### ISSUE THREAD

**Issue by ataulm** [material-components/material-components-android#1277]
**Description:**

When `colorControlHighlight` is a ColorStateList with theme attributes, MaterialCheckBox ripples are red on Lollipop:

v22 | v29
---|---
![light-before](https://user-images.githubusercontent.com/2678555/81180798-6f6bd300-8fa3-11ea-82b7-75ec517e2d13.gif) | ![v23](https://user-images.githubusercontent.com/2678555/81180827-78f53b00-8fa3-11ea-88f8-9ac38f38ad49.gif)

**Expected behavior:**

See v29^

Fixing this would require tinting the background programmatically, using `AppCompatResources` to load `colorControlHighlight`, rather than using it from XML.

**Source code:**

In the app theme, override `colorControlHighlight` to point to a CSL:

```xml
<?xml version="1.0" encoding="utf-8"?>
<selector xmlns:android="http://schemas.android.com/apk/res/android">
    <item android:alpha="0.12" android:color="?attr/colorPrimary" />
</selector>
```

**Android API version:**
21,22

**Material Library version:**
1.1.0, 1.2.0-alpha06

**Device:**
Emulator

To help us triage faster, please check to make sure you are using the [latest version](https://github.com/material-components/material-components-android/releases) of the library.

We also happily accept [pull requests](https://github.com/material-components/material-components-android/pulls).

**Comment by dsn5ft** [comment]
Hi @ataulm, unfortunately globally setting `colorControlHighlight` to a CSL with theme attributes is not a safe thing to do, because that attribute is used in many places by many widgets (framework, AppCompat, etc.), and it's not guaranteed that they all use `AppCompatResources` to load the attribute.

E.g., in this case, the loading of `colorControlHighlight` isn't in [MaterialCheckBox](https://github.com/material-components/material-components-android/blob/master/lib/java/com/google/android/material/checkbox/MaterialCheckBox.java). I think it's in `AppCompatCheckBox`, so you may be able to file an AppCompat bug.

**Comment by ataulm** [comment]
We're not doing it globally, we're using materialThemeOverlay to override
colorControlHighlight for this default style.

Thanks, will raise on the bug tracker.

**Comment by ataulm** [comment]
Ah yeah, we're doing it locally using `materialThemeOverlay`, I just simplified the example for this issue.

Thanks, I'll open it on the main bug tracker! :+1:

**Comment by ataulm** [comment]
For others following along, submitted here - https://issuetracker.google.com/issues/155939564
