### ISSUE TITLE
[MaterialButtonToggleGroup] OnButtonCheckedListener not called on first check

### ISSUE THREAD

**Issue by mtrewartha** [material-components/material-components-android#1365]
**Description:**
When using a `MaterialButtonToggleGroup` that has both `singleSelection` and `selectionRequired` set to `true` but no initial `checkedButton` set, the first tap of one of the buttons does not trigger an `OnButtonCheckedListener` that was added.

**Expected behavior:**
If a button was not previously checked but I tap on it, it should trigger the listener. For example, with the code below, I should see "Button 1 has been checked 1 time" after initially launching the activity and tapping Button 1 once (but I don't). Subsequent taps of each button are dispatched properly.

**Source code:**
Here's a sample activity layout:
```xml
<?xml version="1.0" encoding="utf-8"?>
<androidx.constraintlayout.widget.ConstraintLayout xmlns:android="http://schemas.android.com/apk/res/android"
    xmlns:app="http://schemas.android.com/apk/res-auto"
    xmlns:tools="http://schemas.android.com/tools"
    android:layout_width="match_parent"
    android:layout_height="match_parent"
    tools:context=".MainActivity">

    <com.google.android.material.button.MaterialButtonToggleGroup
        android:id="@+id/toggleGroup"
        android:layout_width="wrap_content"
        android:layout_height="wrap_content"
        app:layout_constraintBottom_toBottomOf="parent"
        app:layout_constraintEnd_toEndOf="parent"
        app:layout_constraintStart_toStartOf="parent"
        app:layout_constraintTop_toTopOf="parent"
        app:selectionRequired="true"
        app:singleSelection="true">

        <com.google.android.material.button.MaterialButton
            android:id="@+id/button1"
            android:layout_width="wrap_content"
            android:layout_height="wrap_content"
            android:text="Button 1" />

        <com.google.android.material.button.MaterialButton
            android:id="@+id/button2"
            android:layout_width="wrap_content"
            android:layout_height="wrap_content"
            android:text="Button 2" />

    </com.google.android.material.button.MaterialButtonToggleGroup>

</androidx.constraintlayout.widget.ConstraintLayout>
```

Here's the code for the activity:
```kotlin
package com.example.materialbuttontogglegroupbug

import android.os.Bundle
import android.util.Log
import androidx.appcompat.app.AppCompatActivity
import kotlinx.android.synthetic.main.activity_main.*

class MainActivity : AppCompatActivity() {

    override fun onCreate(savedInstanceState: Bundle?) {
        super.onCreate(savedInstanceState)
        setContentView(R.layout.activity_main)

        val buttonChecks = mutableListOf(0, 0)

        toggleGroup.addOnButtonCheckedListener { group, checkedId, isChecked ->
            if (!isChecked) return@addOnButtonCheckedListener

            val index = when (checkedId) {
                button1.id -> 0
                button2.id -> 1
                else -> return@addOnButtonCheckedListener
            }
            buttonChecks[index] = buttonChecks[index] + 1

            Log.i("BUG", "Button ${index + 1} has been checked ${buttonChecks[index]} times")
        }
    }
}
```

**Android API version:**
Android 11 DP

**Material Library version:**
1.3.0-alpha01

**Device:**
Pixel 4 XL

**Comment by wcshi** [comment]
hmm, I wonder if it's related to https://github.com/material-components/material-components-android/commit/2d0e00980c9f3f02fa4e755bc668ddb155bc1b67

**Comment by wcshi** [comment]
i think this bug is happening because when the user clicks on a button `MaterialButtonToggleGroup#onPressedChanged` is called before  `MaterialButtonToggleGroup#onCheckedChanged`. `MaterialButtonToggleGroup#onPressedChanged` calls `updateCheckedStates(button.getId(), button.isChecked())` which has logic to "undo deselection" when `selectionRequired` == true and there are no selected ids. 
When `MaterialButtonToggleGroup#onPressedChanged`, the clicked on button has not yet updated its checked state, so the logic described above erroneously updates it internally to be checked. Later when MaterialButtonToggleGroup#onCheckedChanged` calls `updateCheckedStates(button.getId(), button.isChecked())`, OnButtonCheckedListener is called because we think there's no change to the button's checked state.

I'm looking into why we need to call `updateCheckedStates(button.getId(), button.isChecked())` in `MaterialButtonToggleGroup#onPressedChanged`
