### ISSUE TITLE
[MaterialAlertDialog] TalkBack accessibility issues

### ISSUE THREAD

**Issue by dlew** [material-components/material-components-android#1400]
**Description:** The accessibility of a dialog with TalkBack enabled is pretty different between the standard `AlertDialog` vs. `MaterialAlertDialog`.

In general, the icon should not be important for accessibility, it should read the title, and it should start selecting relevant items in the dialog.

-----

Suppose I'm showing a dialog in Trello with an icon, a title "pick an item", and some list items.

**Expected behavior:** Talkback reads "Trello alert pick an item", then auto-focuses the first item of the list (and talks about it). (This is what `AlertDialog` does.)

**Actual behavior:** Talkback reads "Alert dialog icon icon", then auto-focuses the icon of the dialog.

-----

**Source code:**

```
// Somewhat abbreviated
override fun onCreateDialog(savedInstanceState: Bundle?): Dialog {
  return MaterialAlertDialogBuilder(requireContext())
      .setIcon(R.mipmap.icon)
      .setTitle(R.string.title)
      .setAdapter(adapter)
      .setNegativeButton(R.string.cancel)
      .create()
}
```

Switching to `AlertDialog.Builder` fixes all the issues stated above.

**Android API version:** Android 10

**Material Library version:** com.google.android.material:material:1.1.0

**Device:** Pixel 3

**Comment by jemmaSlater** [comment]
I have also had the same issue where it was repeating "dialog icon" with talkback.

Did some digging and the content description for the dialog is set by this style and the string value is just "Dialog Icon". https://github.com/material-components/material-components-android/blob/72cfef981b59fc2b3170c1a22e9910402f8d6770/lib/java/com/google/android/material/dialog/res/values/styles.xml#L48

Came up with a workaround which was to override this value with an empty string in our AppTheme, so it ignores the icon on talkback and behaves as if it is not there. This worked for us because we did not need to provide contextual information for talkback users for our icons on any of our dialogs, but it would not work if we needed to set different content descriptions for different dialogs. However, it does not seem like you are able to provide it in any way other than a style right now to change them all. The documentation also implies you can only do this via a style here: https://material.io/develop/android/components/dialogs/#using-dialogs

Incase it helps, if you just want talkback to ignore it for now, I was able to do it by adding the following in our base application theme:
`<item name="materialAlertDialogTheme">@style/CustomMaterialAlertDialog</item>`

along with:
```
<style name="CustomMaterialAlertDialog" parent="ThemeOverlay.MaterialComponents.MaterialAlertDialog">
    <item name="materialAlertDialogTitleIconStyle">@style/MaterialAlertDialogIconEmptyDescription</item>
</style>

<!-- Style used to remove the content description from icon on MaterialAlertDialog. This prevents talkback from announcing "Dialog icon" when the dialog is shown (this value is hardcoded in the Material library). -->
<style name="MaterialAlertDialogIconEmptyDescription" parent="MaterialAlertDialog.MaterialComponents.Title.Icon">
    <item name="android:contentDescription">""</item>
</style>
```

Ideally there would be a way to set/remove the content description for each use case and not rely on a global style.
