### ISSUE TITLE
Theme.MaterialComponets.DayNight

### ISSUE THREAD

**Issue by lapism** [material-components/material-components-android#142]
Theme.MaterialComponets.DayNight ... will it be available in future release ? Thank you

**Comment by NickM-27** [comment]
See #101 for a guide on how to do this yourself

**Comment by lapism** [comment]
Nice.

**Comment by icarapovic** [comment]
I've just lost half an hour trying to find Theme.MaterialComponets.DayNight and finding out why is my theme not working with MaterialComponents but is with AppCompat.DayNight.

Shouldn't the whole point of this library be that it has this implemented? Whats the point if I need to implement it myself for each project, or why use this instead of AppCompat which already has this?

**Comment by NickM-27** [comment]
What dependency are you using? I bet you're not using a new enough. Sounds be material 1.1.0-alpha07. used it in 3 of my apps so I know it's there

**Comment by dsn5ft** [comment]
Correct, we added full support for the Material DayNight themes in 1.1.0, which is currently in alpha.

See our [Dark Theme Guide](https://github.com/material-components/material-components-android/blob/master/docs/theming/Dark.md) for more information.
