### ISSUE TITLE
[TextInputLayout] background for endIconMode `dropdown_menu` is set from code

### ISSUE THREAD

**Issue by DeMoss15** [material-components/material-components-android#1431]
**Description:** 
First of all: when `endIconMode` in `TextInputLayout` set `dropdown_menu` there is a crash that  `boxBackgroundMode` `none` is not supported for the end icon mode :(

I've tried to set custom background via style for `TextInputLayout`
_The given style worked fine for 1.2.0-alpha05 and older library versions_:

```
<style name="MyApp.Widget.MaterialComponents.TextInputLayout.OutlinedBox.Dense.ExposedDropdownMenu" parent="Base.Widget.MaterialComponents.TextInputLayout">
        <item name="materialThemeOverlay">@style/MyApp.ThemeOverlay.Design.TextInputEditText.Dropdown
        </item>

        <item name="boxBackgroundMode">outline</item>
        <item name="endIconMode">dropdown_menu</item>
        ...
    </style>

    <style name="MyApp.ThemeOverlay.Design.TextInputEditText.Dropdown" parent="ThemeOverlay.Design.TextInputEditText">
        <item name="autoCompleteTextViewStyle">@style/MyApp.Widget.AppCompat.AutoCompleteTextView</item>
        <item name="endIconDrawable">@drawable/selector_dropdown</item>
    </style>

    <style name="MyApp.Widget.AppCompat.AutoCompleteTextView" parent="Widget.AppCompat.AutoCompleteTextView">
        <item name="backgroundTint">@color/selector_my_app_input_background</item>
        ...
        <item name="android:background">?attr/editTextBackground</item>
    </style>
```
And set it as style in layout
```
<com.google.android.material.textfield.TextInputLayout
            android:id="@+id/tilSuffix"
            style="@style/MyApp.Widget.MaterialComponents.TextInputLayout.FilledBox.Dense.ExposedDropdownMenu"
            ...>
```
But the layout changes the background based on `boxBackgroundMode`, and my background is replaced to another drawable.
As I understood, the issue is in the `DropdownMenuEndIconDelegate.setPopupBackground(@NonNull AutoCompleteTextView editText)` method that is called during initialization:
```
if (IS_LOLLIPOP) {
      int boxBackgroundMode = textInputLayout.getBoxBackgroundMode();
      if (boxBackgroundMode == TextInputLayout.BOX_BACKGROUND_OUTLINE) {
        editText.setDropDownBackgroundDrawable(outlinedPopupBackground);
      } else if (boxBackgroundMode == TextInputLayout.BOX_BACKGROUND_FILLED) {
        editText.setDropDownBackgroundDrawable(filledPopupBackground);
      }
    }
```

**Expected behavior:**
Dropdown should be as flexible as input fields to keep the same style for all fields in an app.
![image](https://user-images.githubusercontent.com/24409716/85254039-116a5080-b468-11ea-9810-0cd313494661.png)

**Current behavior:**
![image](https://user-images.githubusercontent.com/24409716/85254300-9b1a1e00-b468-11ea-96be-ed0fcadbf760.png)

**Android API version:** 23 and higher (not sure about older versions)

**Material Library version:** 1.2.0-beta01; 1.3.0-alpha01

**Device:** All devices

**Comment by ianpea** [comment]
Bump, same error

**Comment by drchen** [comment]
Hey Leticia, can you take a look?

**Comment by leticiarossi** [comment]
Hi, could you provide a sample app that reproduces the issue? The screenshot of your expect behavior looks like the Filled style but with a different background color, does using the Filled style and changing `app:boxBackgroundColor` not work?

Your styles look a little confusing, but not sure if that could be the cause of the issue. The parent of `MyApp.Widget.MaterialComponents.TextInputLayout.OutlinedBox.Dense.ExposedDropdownMenu` should probably be the `Widget.*.TextInputLayout.OutlinedBox.Dense.ExposedDropdownMenu` style instead of the Base TextInputLayout style (so you wouldn't need to set `boxBackgroundMode` and `endIconMode` there - but again maybe you want to try the filled style?).

The `DropdownMenuEndIconDelegate.setPopupBackground` method sets the popup's background (`android:popupBackground` attr of the `AutoCompleteTextView`), not the text field's background.

**Comment by drchen** [comment]
I think I have a fix for it.
