### ISSUE TITLE
[BottomAppBar] performHide() isn't working properly

### ISSUE THREAD

**Issue by AxelBlaz3** [material-components/material-components-android#1452]
**Description:** I'm using the Jetpack Navigation for Fragment transactions. Well, I have a BottomAppBar in the `activity_main.xml`. My app uses only dark theme (`Theme.MaterialComponents`). Say, I have two fragments: `FragmentA` and `FragmentB`. In `FragmentA` BottomAppBar should be shown and I call `performShow()`. In `FragmentB` BottomAppBar should be hidden, so I call `performHide()` in `onDestinationChangedListener()` of `NavController`. Whenever I change the system theme from settings to either Light or Dark and navigate back to the app, BottomAppBar shows back in `FragmentB` even though it is expected to be hidden.

**Android API version:** 28 and 29

**Material Library version:** 1.3.0-alpha01

**Device:** Redmi 3S Prime (Android 9), Pocophone F1 (Android 10).

**Comment by goth4m** [comment]
I face this issue too. It's 6 months but still not be resolved?

**Comment by drchen** [comment]
It's working as intended. When config changes, BottomAppBar will be recreated. If clients need to preserve the scroll state, it has to be implemented on the client side.

The reason behind this is that, by design, the BottomAppBar showing/hiding behavior is supposed to be decided by the state of other views. It's hard for BottomAppBar to make assumptions about other views' state during recreation. If we just restore the showing/hiding state blindly, it may cause different issues in different scenarios. 

In your case I think you can just save BottomAppBar.isScrollDown() in your fragment's onSaveInstanceState() and restore it in onCreate().
