### ISSUE TITLE
[MaterialCheckBox] textColor in textAppearance is ignored if specified in layout or styles XML

### ISSUE THREAD

**Issue by gmetal** [material-components/material-components-android#1470]
**Description:** If you have a MaterialCheckBox and you apply a text Appearance style to it in XML (either directly in the layout XML, or through a theme/style) then the textColor attribute is completely ignored. Note that setting the text appearance programmatically, sets the textColor correctly.

**Expected behavior:** The expected behaviour is that the text color is set to the value specified in the text appearance.

**Source code:** 

An example layout fragment is:
```
    <com.google.android.material.checkbox.MaterialCheckBox
        android:id="@+id/sample_checkbox"
        style="@style/AppTheme.Checkbox"
        android:layout_width="0dp"
        android:layout_height="wrap_content"
        android:text="Lorem ipsum sit dolor emet"
        app:layout_constraintEnd_toEndOf="parent"
        app:layout_constraintStart_toStartOf="parent"
        app:layout_constraintTop_toTopOf="parent"
        />

    <com.google.android.material.checkbox.MaterialCheckBox
        android:id="@+id/sample_checkbox2"
        android:layout_width="0dp"
        android:layout_height="wrap_content"
        android:text="Lorem ipsum sit dolor emet"
        android:textAppearance="@style/AppTheme.TextAppearance"
        app:layout_constraintEnd_toEndOf="parent"
        app:layout_constraintStart_toStartOf="parent"
        app:layout_constraintTop_toBottomOf="@id/sample_checkbox"
        />
```

The corresponding styles are: 
```
    <style name="AppTheme.Checkbox" parent="Widget.MaterialComponents.CompoundButton.CheckBox">
        <item name="android:paddingStart">32dp</item>
        <item name="android:textAppearance">@style/AppTheme.TextAppearance</item>
    </style>

    <style name="AppTheme.TextAppearance" parent="TextAppearance.MaterialComponents.Caption">
        <item name="android:textSize">21sp</item>
        <item name="android:textColor">#000000</item>
    </style>
```

**Android API version:** Tested on Android Q

**Material Library version:** 1.1.0 (also tested on 1.2.0-beta01)

**Device:**  Huawei P30  (although the bug can also be seen in the Android Studio designer)

**Comment by consp1racy** [comment]
This is because `Widget.MaterialComponents.CompoundButton.CheckBox` extends `android:Widget.CompoundButton` which looks like this:


    <style name="Widget.CompoundButton">
        <item name="android:focusable">true</item>
        <item name="android:clickable">true</item>
        <item name="android:textAppearance">?android:textAppearance</item>
        <item name="android:textColor">?android:textColorPrimaryDisableOnly</item>
        <item name="android:gravity">center_vertical|start</item>
    </style>

The style defines a `android:textColor` which overides the text color from `android:textAppearance`. It doesn't matter if it's defined as an attribute on the widget element or in a style resource.

You can try setting `android:textColor="@null"` in your style. Then it shouldn't override the value from text appearance.

**Comment by gmetal** [comment]
> This is because `Widget.MaterialComponents.CompoundButton.CheckBox` extends `android:Widget.CompoundButton` which looks like this:
> 
> ```
> <style name="Widget.CompoundButton">
>     <item name="android:focusable">true</item>
>     <item name="android:clickable">true</item>
>     <item name="android:textAppearance">?android:textAppearance</item>
>     <item name="android:textColor">?android:textColorPrimaryDisableOnly</item>
>     <item name="android:gravity">center_vertical|start</item>
> </style>
> ```
> 
> The style defines a `android:textColor` which overides the text color from `android:textAppearance`. It doesn't matter if it's defined as an attribute on the widget element or in a style resource.
> 
> You can try setting `android:textColor="@null"` in your style. Then it shouldn't override the value from text appearance.

Indeed this is correct. However, it is not very straightforward and can be easily missed. Moreover, it does not seem to be documented. The [documentation](https://material.io/develop/android/components/checkboxes) states that you can alter the checkbox text appearance, or the text color as you normally would. 

I can understand that there is some reason behind the specific style implementation, however I believe that it should, at least, be more clearly documented.

**Comment by consp1racy** [comment]
This is not a problem in Material Design Components. This happens in pure Android.

Maybe it could be handled in AppCompat. You can file an issue [here](https://issuetracker.google.com/issues/new?component=460343&template=1422420) instead. I'm curious if it gets done, it shouldn't break anything because it already doesn't work.

---

The linked documentation explicitly says that *color* is handled by `android:textColor` attribute. Snapshot here:
![obrazek](https://user-images.githubusercontent.com/4589773/87791110-070e5d00-c842-11ea-9db8-994f6218f5fb.png)
The documentation isn't wrong and it doesn't work as you would expect in pure Android anyway.

**Comment by gmetal** [comment]
I will file an issue with AppCompat and see what happens. However, I do believe that the documentation is not very clear that setting the textColor in a text appearance will be ignored.

**Comment by PhantomLord72** [comment]
FontFamily too
