### ISSUE TITLE
[Transitions] Axis transition crashes if there is ViewPager2 in layout

### ISSUE THREAD

**Issue by YuriDenison** [material-components/material-components-android#1475]
```
java.lang.IllegalStateException: ViewPager2 does not support direct child views
        at androidx.viewpager2.widget.ViewPager2.onViewAdded(ViewPager2.java:489)
        at android.view.ViewGroup.dispatchViewAdded(ViewGroup.java:4988)
        at android.view.ViewGroup.addViewInner(ViewGroup.java:5160)
        at android.view.ViewGroup.addView(ViewGroup.java:4935)
        at android.view.ViewGroup.addView(ViewGroup.java:4875)
        at androidx.transition.TransitionUtils.createViewBitmap(TransitionUtils.java:138)
        at androidx.transition.TransitionUtils.copyViewImage(TransitionUtils.java:64)
        at androidx.transition.Visibility.onDisappear(Visibility.java:401)
        at androidx.transition.Visibility.createAnimator(Visibility.java:257)
        at androidx.transition.Transition.createAnimators(Transition.java:747)
        at androidx.transition.Transition.playTransition(Transition.java:1821)
        at androidx.transition.TransitionManager$MultiListener.onPreDraw(TransitionManager.java:301)
        at android.view.ViewTreeObserver.dispatchOnPreDraw(ViewTreeObserver.java:1088)
```

Reproduced at least with MaterialSharedAxis and FadeThrough transitions animating simple views

Material library version 1.3.0-alpha01
Tested on Android 9,10
Any device/emulator

**Comment by hunterstich** [comment]
Hey @YuriDenison,

Thanks so much for filing an issue! Any chance you could provide a sample that reproduces this so I can start working on a possible fix?

Thanks!

**Comment by YuriDenison** [comment]
Hey @hunterstich,
I was just playing with [Conductor](https://github.com/bluelinelabs/Conductor)'s transition ChangeHandlers.

```
class ZAxisChangeHandler : TransitionCompatChangeHandler() {
  override fun getTransition(container: ViewGroup, from: View?, to: View?, isPush: Boolean): Transition = MaterialSharedAxis(MaterialSharedAxis.Z, isPush)
}
```

Reproduced with 2 layouts, one of them contains viewpager in CollapsingAppBarLayout 
```
    <androidx.coordinatorlayout.widget.CoordinatorLayout>
      <CollapsingToolbarLayout>
        <Toolbar/>
        <androidx.viewpager2.widget.ViewPager2/>
      </CollapsingToolbarLayout>

      <androidx.recyclerview.widget.RecyclerView/>
    </androidx.coordinatorlayout.widget.CoordinatorLayout>
```

**Comment by hunterstich** [comment]
@YuriDenison 

Do you mind sending along a repo of what you were playing that reproduces this? It's extremely helpful if we don't have to create entire projects and reproduce exact configurations manually for each issue we look into.

**Comment by YuriDenison** [comment]
It's reproduced on our private project, I'll try to create sample project and share it with you in a couple of days.

**Comment by hunterstich** [comment]
Okay great, thanks! 

Just off the top of my head, you might want to try setting `transitionGroup=true` on the root ViewGroup which you want your `MaterialSharedAxis` or `MaterialFadeThrough` to run. This has been a common solution with a few other bugs and its at least worth a shot : ). In this case, I'm assuming you'd want set `transitionGroup=true` on your CoordinatorLayout from the snippet you posted above?

Let me know if that helps

**Comment by YuriDenison** [comment]
@hunterstich I've created sample project https://github.com/YuriDenison/material-transitions-sample
To reproduce the issue you just need to click on header pager's item and go back.

The sample contains simpliest conductor integration, I'm sure it can be done without conductor at all using simple views add/remove.

**Comment by hunterstich** [comment]
Thanks for the sample @YuriDenison!

After looking into this, it looks like an issue with the way Visibility transitions work. By default, a Transition will target all descendants changing visibility that are beneath the Transition's scene root. In the case of your `AxisChangeHandler`, that would include all views in both your `home.xml` and `profile.xml` layouts since your scene root is `MainActivity`'s `R.id.content` `FrameLayout`. 

If a view is disappearing, the only way to capture that view before it is removed from the hierarchy is to take a snapshot of it and [add it back into the layout via an overlay](https://android.googlesource.com/platform/frameworks/base/+/master/core/java/android/transition/TransitionUtils.java#192). It looks like this adding is what's causing a crash since Visibility is trying to add the overlay to ViewPager2 which throws an [IllegalStateException if you try to add direct children](https://github.com/aosp-mirror/platform_frameworks_support/blob/androidx-master-dev/viewpager2/src/main/java/androidx/viewpager2/widget/ViewPager2.java#L465). 

To fix this, you can give your MaterialSharedAxis targets, causing the transition to only run on the targeted view(s) and none of their children.

In your sample's case, this worked for me:
<br>

_AxisChangeHandler_.kt
```
class ZAxisChangeHandler() : TransitionChangeHandler() {

  private var handlerTarget = mutableListOf<Int>()

  fun addHandlerTarget(id: Int) {
    handlerTarget.add(id)
  }

  override fun getTransition(container: ViewGroup, from: View?, to: View?, isPush: Boolean): Transition {
    return MaterialSharedAxis(MaterialSharedAxis.Z, isPush).apply {
        handlerTarget.forEach { addTarget(it) }
    }
  }
}
```

_HomeController_.kt
```
RouterTransaction.with(ProfileController())
  .pushChangeHandler(ZAxisChangeHandler().apply {
     addHandlerTarget(R.id.home_coordinator)
     addHandlerTarget(R.id.profile_coordinator)
  })
  .popChangeHandler(ZAxisChangeHandler().apply {
     addHandlerTarget(R.id.home_coordinator)
     addHandlerTarget(R.id.profile_coordinator)
   })
)
```

I'm going to go ahead and close this since it's more a quirk of the Transition system/ViewPager2, but let me know if this solves your problem and if we do anything else to help.

Hunter

**Comment by YuriDenison** [comment]
Thanks @hunterstich.

Creating abstract parent for all material transition helped with the issue
```
abstract class MaterialTransitionChangeHandler : TransitionChangeHandler() {
  override fun getTransition(container: ViewGroup, from: View?, to: View?, isPush: Boolean): Transition = getTransition(isPush).apply {
    from?.let { addTarget(it) }
    to?.let { addTarget(it) }
  }

  abstract fun getTransition(isPush: Boolean): Transition
}
```

However don't you think the view transitions should respect `transitionGroup=true` attribute?
Currently it's not working for this case.

It'll be convenient if it is possible to explicitly mark specific layouts with `transtitionGroup=true` and ignore their children targets, saving default behavior for other layouts.

**Comment by hunterstich** [comment]
@YuriDenison That was the first approach I tried and is what we're usually recommending. It works for all the cases we've run into previously (see [Reply](https://github.com/material-components/material-components-android-examples/blob/af74b67b37c8fe6bc3bda5a6e01b45fbc429bb8a/Reply/app/src/main/res/layout/fragment_home.xml#L25) as an example), but strangely it's not working with Conductor in your sample. I'm not sure what's the reason might be here.
