### ISSUE TITLE
[MaterialTextView] Line height documentation is confusing

### ISSUE THREAD

**Issue by nateridderman-lilly** [material-components/material-components-android#1482]
**Description:** The documentation for [MaterialTextView](https://material.io/develop/android/components/material-text-view) says that you can specify the lineHeight on a textAppearance in order to apply it to the view. In my testing, this only works for SDK 28+ so it must rely on the native lineHeight attribute that was added at that time. It did not work on a SDK 26 emulator. 

I find this documentation confusing. It should specify the minSdk or just not be in the documentation at all. 

**Material Library version:** 1.1.0

**Comment by hunterstich** [comment]
Hey @nateridderman-lilly! `lineHeight` in your TextAppearances should work fine on pre-28 devices. Can you link a project that shows the problem you're running into? Might you be using `android:lineHeight` instead of `lineHeight` in your TextAppearances? 

We have two sample apps - [Reply](https://github.com/material-components/material-components-android-examples/tree/develop/Reply), [Owl](https://github.com/material-components/material-components-android-examples/tree/develop/Owl) - that both use lineHeight in their text appearances and run on 23+. To verify this works, you can open [type.xml](https://github.com/material-components/material-components-android-examples/blob/develop/Reply/app/src/main/res/values/type.xml#L47), change body1's `lineHeight` and re-run the app.

Let me know if this helps. I'm going to close this but feel free to continue discussing or reopen if this isn't correct.
