### ISSUE TITLE
Snackbar uses deprecated class when searching for parent for anchor

### ISSUE THREAD

**Issue by przybylski** [material-components/material-components-android#150]
### Overview

When Snackbar is searching for suitable parent to anchor to with `findSuitableParent` function
it checks only for  `android.support.design.widget.CoordinatorLayout`.
Since CoordinatorLayout will be moved to androidx it package name will change to
`androidx.coordinatorlayout.widget.CoordinatorLayout`.
So with current implementation without FrameLayout or android.support.design.widget.CoordinatorLayout Snackbar will always attach to android.R.id.container. 

This might cause snackbar to be shown below navbar.

### Reproduction steps

Have two nested CoordinatorLayout
```xml
<androidx.coordinatorlayout.widget.CoordinatorLayout
            android:id="@+id/main_container"
            android:layout_width="match_parent"
            android:layout_height="match_parent">
    <androidx.coordinatorlayout.widget.CoordinatorLayout
                android:id="@+id/fitting_container"
                android:layout_width="match_parent"
                android:layout_height="match_parent"
                android:fitsSystemWindows="true">
    </androidx.coordinatorlayout.widget.CoordinatorLayout>
</androidx.coordinatorlayout.widget.CoordinatorLayout>
```

Invoke Snackbar attached to fitting containter:
```java
    View  v = findViewById(R.id.fitting_container);
    Snackbar.make(v, "TEST", Snackbar.LENGHT_LONG).show()
```
Snackbar will show below navbar.

### Version number

 - 1.0.0-alpha3

**Comment by dsn5ft** [comment]
This is because we are in a transition period of migrating to AndroidX, and I believe this will only happen if you build our library from source (our releases to Maven get "jetified" to use the new androidx classes).

If you are building our library from source, you can try setting `android.enableJetifier=true` in your `gradle.properties` file, which should jetify our library to use androidx at build time.
