### ISSUE TITLE
[MaterialDatePicker] option to setTimeZone

### ISSUE THREAD

**Issue by deepakgupta7403** [material-components/material-components-android#1513]
**Is your feature request related to a problem? Please describe.**
I faced a problem when I get the time and it'll return me UTC time but I want IST time Millis because all my customers belong from India or provide such a method so it'll pick time zone according to the device timezone not UTC. 

**Describe the solution you'd like**
if there is one method setTimeZome like Calendar, so most of the issue is based on time showing wrong, and returning UTC time only is resolved.

We also happily accept [pull requests](https://github.com/material-components/material-components-android/pulls).

**Comment by ricscar2570** [comment]
Il 24/07/2020 15:19 Deepak Gupta <notifications@github.com> ha scritto:
   
   
    
   
   
    
   
   
   Is your feature request related to a problem? Please describe.I faced a problem when I get the time and it'll return me UTC time but I want IST time Millis because all my customers belong from India or provide such a method so it'll pick time zone according to the device timezone not UTC.
   Describe the solution you'd likeif there is one method setTimeZome like Calendar, so most of the issue is based on time showing wrong, and returning UTC time only is resolved.
   We also happily accept pull requests.

**Comment by matpag** [comment]
Converting date/time between timezones is not hard.
You can use a library like [ThreeTenABP](https://github.com/JakeWharton/ThreeTenABP) and it's pretty easy.

**Comment by dsn5ft** [comment]
Agreed, for simplicity I think `MaterialDatePicker` should stick with UTC.
