### ISSUE TITLE
[AllTextComponent] Migrate TextView to AppCompatTextView  for PrecomiledText support

### ISSUE THREAD

**Issue by slavonnet** [material-components/material-components-android#1530]
Only MatirealText extends AppCompatTextView. Other components not support setFuture for delayed render text. 
Also don't foget hint's and other small text fileds! All textView must support it! And buttons!

**Comment by dsn5ft** [comment]
I'm not sure what this is referring to. If it's referring to places where we use `<TextView` in XML within other components, then we don't need to migrate them because our view inflater class will automatically replace `TextView` with `MaterialTextView` when using a `MaterialComponents` theme:

https://github.com/material-components/material-components-android/blob/master/lib/java/com/google/android/material/theme/MaterialComponentsViewInflater.java#L61

https://github.com/material-components/material-components-android/blob/8851f703d86c3d80cae21d3d117fe5a80560297d/lib/java/com/google/android/material/theme/res/values/themes_base.xml#L23

Please reopen with more context if needed.
