### ISSUE TITLE
[ShapeableImageView] Doesn't have elevation overlay with night mode

### ISSUE THREAD

**Issue by alorma** [material-components/material-components-android#1563]
**Description:** When using `ShapeableImageView` with night mode set to `MODE_NIGHT_YES` it should add an overlay as it's shown in [this video](https://kstatic.googleusercontent.com/files/9976752535996547e4486a11a5e6b17cb0dfc27541bab905752c1c9c725bc3d0d3ca91f6072752b8aff8b96f60aa5e5c4b0af474ac12c45912dce8373c6803cf) froom material.io

<img width="185" src="https://user-images.githubusercontent.com/887462/89297371-03613f80-d664-11ea-9fc4-8d34e461d671.png">

**Expected behavior:** View should add elevationOverlay

**Source code:** Demo sample: https://github.com/alorma/SampleCode_ShapeableImageView_elevation_Bug

**Android API version:** 29

**Material Library version:** 1.2.0-rc01)

**Device:** Emulator / ANY

**Comment by ymarian** [comment]
The result of the video can be achieved with MaterialCardView instead of ShapeableImageView.

MaterialCardView uses Surface color most of the time so it makes sense to have built in support for elevation overlays, ShapeableImageView is intended to be used with pictures so the concept of elevation overlay doesn't transfer. Also checkout 
[MaterialShapeDrawable](https://github.com/material-components/material-components-android/blob/f945a0649b9cddc13afafeb80df7218f1aa85ef8/lib/java/com/google/android/material/shape/MaterialShapeDrawable.java#L150). Depending on what you end goal is.
