### ISSUE TITLE
Bottom App Bar Error

### ISSUE THREAD

**Issue by cngeru** [material-components/material-components-android#158]
### Overview
Getting this error on my logs and the app keeps crashing
`Error inflating class com.google.android.material.bottomappbar.BottomAppBar`
### Reproduction steps
Following the instructions on https://material.io/develop/android/components/bottom-app-bar/

**Comment by dsn5ft** [comment]
This might be because you are using the `com.android.support:design` version of our library. If that's the case, you can try switching `com.google.android.material.bottomappbar.BottomAppBar` to `android.support.design.bottomappbar.BottomAppBar`.

Alternatively, you could follow our [Getting Started](https://github.com/material-components/material-components-android/blob/master/docs/getting-started.md) guide which talks about updating to `com.google.android.material`.

**Comment by firatkarababa** [comment]
You may be missing something in your setup, e.g not including the required dependency as below.

dependencies {
     // ...
     compile 'com.google.android.material:material:1.0.0-alpha1'
     // ...
   }

Have a look at [Getting Started](https://material.io/develop/android/docs/getting-started/) page if you are missing something.

**Comment by cngeru** [comment]
It works Thanks
