### ISSUE TITLE
[Motion] Material container transformation will dismiss when re-enter app，after unlock screen

### ISSUE THREAD

**Issue by Sanlorng** [material-components/material-components-android#1639]
**Description** : MaterialContainerTransform will dismiss after switch app/ block screen / return home /enter second Activity，third Activity then return first Activity。this problems also appear in Categories's TranstionContainerTransformStartDemoActivity

**Expect Behavior** ：No matter if I lock the screen, return to the desktop, or enter the multitasking management, it will not disappear when I re-enter the application。No matter how many activities I open, when I return to the previous Activity, the MaterialContainerTransform of each previours Activity will not disappear if the previous Activity  does not destroy View

**Library Version** ： 1.3.0-alpha02

**Comment by dsn5ft** [comment]
Hi @Sanlorng, this is unfortunately a limitation of the Android Transition framework that's built into the Android platform.

It happens due to the enter/return Activity transitions being cleared in onStop():

https://cs.android.com/android/platform/superproject/+/master:frameworks/base/core/java/android/app/ActivityTransitionState.java;l=249-259;drc=64643f6dcd261c4bf1a1856bb9ad303e96aab039

As far as I know there aren't any workarounds, and if the bug was fixed, it would only be available on future versions of Android.

**Comment by Sanlorng** [comment]
@dsn5ft Thanks
