### ISSUE TITLE
[MaterialDatePicker] Test utils

### ISSUE THREAD

**Issue by dawidhyzy** [material-components/material-components-android#1720]
I was doing some UI tests for one of my screens which uses MaterialDatePicker. Unfortunately, there is no testing artifact that could help with that.

I found [MaterialDatePickerTestUtils](https://github.com/material-components/material-components-android/blob/22973ff10305397bfc72fed41684175fee8aeefb/tests/javatests/com/google/android/material/datepicker/MaterialDatePickerTestUtils.java#L49) in this repository and this could greatly help with that challenge. Are you planning to make this public?

**Comment by ymarian** [comment]
Hi, we would need to release a separate testing maven artifact, which is not in our immediate plans. 

That would require some work since we like to keep some flexibility in our testing utils in case we need to change them or refactor them significantly. The code is there so it can be copied or used as example.
