### ISSUE TITLE
[MaterialShapeDrawable] Shadow Visibility below view 

### ISSUE THREAD

**Issue by jacklebbos** [material-components/material-components-android#1837]
**Description:** Hello, I am setting a `MaterialShapeDrawable` with shadow color and elevation to views in a linear layout,
forcing always to draw fake shadows, but the shadows are not respecting the other views background so they are appearing above neighbor views. is there any way to fix this?

<img width="390" alt="Screen Shot 2020-10-29 at 6 03 23 PM" src="https://user-images.githubusercontent.com/10996732/97599829-13917c80-1a11-11eb-8009-8428aee84b4a.png">

**Expected behavior:** The shadows of `MaterialShapeDrawable` appears below neighbor views if the have same elevation, in other words, the bottom shadow of test 1 and the top shadow of test 2 should not be visible, just like a cardview would behave

**Android API version:** 29

**Material Library version:** 1.2.1

**Device:** Any Emulator

**Comment by drchen** [comment]
It's indeed a bug but unfortunately it's a limitation of the compat shadow. MaterialShapeDrawable have no ways to figure out if the shadow should be "hidden" by other views/drawables on the screen.

In short, with compat shadow, it will just draw the shadow on the canvas according to the absolute value of the specified elevation & translation-z of the drawable, instead of taking the relative z value to other views/drawables locating nearby or underneath into account. (There's no way for it to do it.)

To have better shadow effect, please use SHADOW_COMPAT_MODE_DEFAULT instead. So whenever the native shadow is available, it will use it instead.
