### ISSUE TITLE
[TextInputLayout] Semi-transparent box background

### ISSUE THREAD

**Issue by digitalheir** [material-components/material-components-android#1899]
**Is your feature request related to a problem? Please describe.**
I would like to be able to set a semi-transparent background for my `TextInputLayout`. 

**Describe the solution you'd like**
Either `boxBackgroundColor` respects alpha or there is a `boxBackgroundAlpha` field.

**Describe alternatives you've considered**
I'ved use a color with alpha for `boxBackgroundColor`, but the library forces it to be opaque.

**Comment by leticiarossi** [comment]
Hi, the text field has a surfaceLayer that takes `?attr/colorSurface` as its color ([code](https://github.com/material-components/material-components-android/blob/master/lib/java/com/google/android/material/textfield/TextInputLayout.java#L2638-L2651)), so that's why it's opaque.
You can set a theme overlay on a custom TextInputLayout style to set `?attr/colorSurface` to transparent
