### ISSUE TITLE
[ShapeableImageView] Corners are not rounded after updating to 1.3.0

### ISSUE THREAD

**Issue by amankgo** [material-components/material-components-android#2046]
**Description:** Corners are not rounded in  ShapeableImageView after updating to 1.3.0. It was working properly in 1.2.0. Corners are just flat with the updated version. I have added shape style to the global theme.
```
<style name="ShapeAppearance.Todafy.MediumComponent" parent="ShapeAppearance.MaterialComponents.MediumComponent">
        <item name="cornerFamily">rounded</item>
        <item name="cornerSize">8dp</item>
    </style>

    <style name="ShapeAppearance.Todafy.LargeComponent" parent="ShapeAppearance.MaterialComponents.LargeComponent">
        <item name="cornerFamily">rounded</item>
        <item name="cornerSize">8dp</item>
    </style>
```

**Expected behavior:** Corners should be rounded. 
![Screenshot_20210206-004836_Todafy Debug](https://user-images.githubusercontent.com/40785614/107079313-ab271800-6815-11eb-89d2-224ec7119679.jpg)

**Android API version:** Android Version 10, Samsung One UI 2.0

**Material Library version:** 1.3.0

**Device:** Samsung Galaxy A30

**Comment by amankgo** [comment]
Also adding the xml code for reference:

```
<com.google.android.material.imageview.ShapeableImageView
        android:id="@+id/tdfPodImage"
        android:layout_width="0dp"
        android:layout_height="wrap_content"
        android:layout_marginStart="15dp"
        android:layout_marginTop="10dp"
        android:layout_marginEnd="15dp"
        android:adjustViewBounds="true"
        android:elevation="2dp"
        android:minHeight="200dp"
        android:scaleType="centerCrop"
        app:layout_constraintEnd_toEndOf="parent"
        app:layout_constraintHeight_min="200dp"
        app:layout_constraintStart_toStartOf="parent"
        app:layout_constraintTop_toBottomOf="@id/tdfHeader" />
```

**Comment by thibseisel** [comment]
I've had the same issue and had to browse library source code to find what changed between 1.2.0 and 1.3.0.
Due to [this commit](https://github.com/material-components/material-components-android/commit/61d2be7c00561c97674100bdad246c14ba2f30c4#diff-b73054153de516a62a1eab4ab5f27c32c0520f2da1ea1ac6c8afda03d21abf3a) `ShapeableImageView` no longer has a default `shapeAppearance` applied ; which makes perfectly sense because `ImageView`s could be of any size.

Adding `app:shapeAppearance="?shapeAppearanceMediumComponent"` should bring you back to how it worked in 1.2.0.
It seems that this attribute is mandatory now: specify it either on individual `ShapeableImageView`s or extend `@style/Widget.MaterialComponents.ShapeableImageView` to specify a default `shapeAppearance`.

**Comment by amank22** [comment]
Yeah, manually adding it works but it would be better if they mentioned it in release notes so that devs can do proper migration.

**Comment by hunterstich** [comment]
Updated the release notes 
https://github.com/material-components/material-components-android/releases/tag/1.3.0

Thank you
