### ISSUE TITLE
Interesting. But I can't just delete vector. I have a lot of them and I don't know which one cause problem.

### ISSUE THREAD

**Issue by Tigranbabajanyan** [material-components/material-components-android#205]
_Originally posted by @Mistic92 in https://github.com/material-components/material-components-android/issues/104#issuecomment-390602633_

**Comment by afohrman** [comment]
I'm not sure what this issue is referring to. I'm closing this issue; if you have an issue and you'd like to re-open this, please file a bug in our [Issue Tracker](https://issuetracker.google.com/issues/new?component=439535).

For usage questions, ask on [Stack Overflow](https://stackoverflow.com/questions/tagged/material-components+android).
