### ISSUE TITLE
[BadgeDrawable] BadgeDrawable can only be anchored to a FrameLayout

### ISSUE THREAD

**Issue by rewgoes** [material-components/material-components-android#2076]
**Description:** Version 1.30 remove the capability of setting BadgeDrawable in any kind of view, limiting it to be anchored only on `FrameLayout`.

I could not find any discussion why this feature was removed in 9487c33b8ab50edbcff46cf728531712ab091a85. By the looks of it, it was removed by mistake. That is why I'm reporting this as an issue and not as a feature.

@wcshi and @hunterstich, could you please explain why this was removed? Can I create a PR to add this feature back to the code?

**Expected behavior:** BadgeDrawable should be anchored in any view starting in API 18+

**Source code:** 
`badge.updateBadgeCoordinates(iconView, toolbar)`

**Android API version:** Any

**Material Library version:** 1.3.0

**Device:** Any

**Comment by wcshi** [comment]
@rewgoes the PR you referenced is to revert a rollback, it restored functionality (), it didn't remove any.

why do you think this feature was removed? 

Please see https://github.com/material-components/material-components-android/blob/9487c33b8ab50edbcff46cf728531712ab091a85/docs/components/BadgeDrawable.md

**Comment by rewgoes** [comment]
`updateBadgeCoordinates(@NonNull View anchorView, @Nullable ViewGroup customBadgeParent)` was annotated  as `@Deprecated` and the following constraint was added:
```java
if (customBadgeParent instanceof FrameLayout == false) {
    throw new IllegalArgumentException("customBadgeParent must be a FrameLayout");
}
```

Is this expected? What is the reason for removing it?

**Comment by wcshi** [comment]
ah, i see what you are asking. 
In api 18+ badge's are attached via an viewoverlay to their anchor view, so it can be anything e.g. BadgeDrawable#updateBadgeCoordinates(View anchorView)

In pre api 18, in order to support an arbitrary anchor view, we wrap your anchor view in a framlayout, which is why the customBadgeParent is expected to be FrameLayout.

From a dev perspective, you no longer need to specify the custom badge parent. After calling `BadgeUtils#attachAnchor(BadgeDrawable, Anchor)` you can call BadgeDrawable#updateBadgeCoordinates(View anchorView)` and BadgeDrawable will do the right thing without you having to explicitly specify the customBadgeParent.

Does that make sense?

**Comment by rewgoes** [comment]
Sorry for the late reply, busy days.

Thanks for the tip! I went through the library code and recent changes and I found the method `BadgeUtils#attachBadgeDrawable(BadgeDrawable, View)` which works without providing a parent, as you said. I'm closing this issue.

-------

Just one last question. I'm using Badge on the Toolbar's navigation/back button, `android.R.id.home`, and I've noticed that it's possible to attach a badge to the Toolbar by using `BadgeUtils.attachBadgeDrawable(BadgeDrawable, Toolbar, menuItemId)`. However, it only works with `ActionMenuItemView`.

Is there any chance of adding support to attach the badges to the Toolbar's navigation button as well? Would that be a accepted if a propose a PR to add this feature?
