### ISSUE TITLE
 language select between Java and Kotlin

### ISSUE THREAD

**Issue by LeonChen1024** [material-components/material-components-android#2088]
I have a question ,Google is declared that Kotlin first in Android ,but this Google official  repo seems will still use Java in future even in new components, what makes this decision ?

**Comment by hunterstich** [comment]
Hey @LeonChen1024,

Thanks for the question. We haven't moved to Kotlin since it would mean our non-Kotlin clients would have to take on the additional dependency of the Kotlin standard library. We do try to provide Kotlin friendly API's, so if you come across issues using the library while in a Kotlin codebase, please let us know!
