### ISSUE TITLE
Theming Text fields

### ISSUE THREAD

**Issue by HaDangTu** [material-components/material-components-android#2177]
I'm using material version 1.3.0 and Android Studio shows an error **Cannot resolve symbol '@style/Widget.MaterialComponents.TextInputEditText'** when I try to change theme of text field. Where is that style?
![xml](https://user-images.githubusercontent.com/38284966/114719546-6792e200-9d61-11eb-8db9-2ac495d40202.PNG)

Here is my app build.gradle
![build_gradle](https://user-images.githubusercontent.com/38284966/114719924-be002080-9d61-11eb-8229-cac0450f180a.PNG)
![build_gradle_cont](https://user-images.githubusercontent.com/38284966/114719952-c6585b80-9d61-11eb-91ad-72e0ed68ca6a.PNG)

**Comment by afohrman** [comment]
There is no edit text style named `"Widget.MaterialComponents.TextInputEditText"`. The `editTextStyle` attribute should be set to either a filled box style (`Widget.MaterialComponents.TextInputEditText.FilledBox` or an outlined box style (`Widget.MaterialComponents.TextInputEditText.OutlinedBox`).

Extending `ThemeOverlay.App.TextInputLayout` from `ThemeOverlay.MaterialComponents.TextInputEditText.FilledBox` should handle setting the `editTextStyle` for you so that you don't have to reference it explicitly.

Side point: have you tried using a plain theme overlay using `android:theme`? The `materialThemeOverlay` attribute should respect theme attributes set in `android:theme`, so that would be a better place to set color theme attributes. `MaterialThemeOverlay` is intended to be an internal attribute used by Material to make sure developers can use `android:theme` without overwriting anything set by Material.

Please reopen if this does not fix your issue.

**Comment by unc0ded** [comment]
> There is no edit text style named `"Widget.MaterialComponents.TextInputEditText"`. The `editTextStyle` attribute should be set to either a filled box style (`Widget.MaterialComponents.TextInputEditText.FilledBox` or an outlined box style (`Widget.MaterialComponents.TextInputEditText.OutlinedBox`).
> 
> Extending `ThemeOverlay.App.TextInputLayout` from `ThemeOverlay.MaterialComponents.TextInputEditText.FilledBox` should handle setting the `editTextStyle` for you so that you don't have to reference it explicitly.
> 
> Side point: have you tried using a plain theme overlay using `android:theme`? The `materialThemeOverlay` attribute should respect theme attributes set in `android:theme`, so that would be a better place to set color theme attributes. `MaterialThemeOverlay` is intended to be an internal attribute used by Material to make sure developers can use `android:theme` without overwriting anything set by Material.
> 
> Please reopen if this does not fix your issue.

I came across the same issue as the OP, there is no such style `Widget.MaterialComponents.TextInputEditText.FilledBox` or `Widget.MaterialComponents.TextInputEditText.FilledBox`. There are only `Widget.MaterialComponents.TextInputLayout.FilledBox` or `Widget.MaterialComponents.TextInputLayout.OutlinedBox`. Was there any change in the naming since the docs were written, or am I doing something wrong?
