### ISSUE TITLE
[MaterialDatePicker] Is there a way to launch it in/as a bottom sheet?

### ISSUE THREAD

**Issue by oheyadam** [material-components/material-components-android#2179]
Hello, I'm trying to launch the date picker as a bottom sheet instead of a dialog. Is there a way to do this?

**Comment by msasikanth** [comment]
While the library doesn't provide an option to open the `MaterialDatePicker` as a bottom sheet right now. You can fork the repo and make the changes to `MaterialDatePicker`, you can start by extending the `BottomSheetDialogFragment` instead of `DialogFragment`.

Apart from that, you might need to adjust the shape drawable that is used for the background. I haven't actually tried the implementation, but it might have more changes that need to be made.

**Comment by drchen** [comment]
Unfortunately we don't support opening date picker from a bottom sheet and I don't feel we will have an official support for that in the recent future. (It has to put a lot of efforts on doing it and we don't really have a plan from the design side.)

I'll close the feature request for now.

**Comment by sk2andy** [comment]
Can you explain why you build the library so restrictively? Couldn't you create the view itself and offer the builder as a goodie besides the view? I would like to understand if you just want to force the developers into a specific UI pattern or if there is another reason for that
