### ISSUE TITLE
How to build-from-source with androidx

### ISSUE THREAD

**Issue by WebTiger89** [material-components/material-components-android#220]
I did a build from source and imported it as dependency in my project but I got errors regarding "class file for android.support.v7.app.AppCompatDialogFragment not found"

I then noticed, that the material dependency is internally using "import android.support.v7.app.AppCompatDialogFragment;" whereas the offical dependency uses "import androidx.appcompat.app.AppCompatDialogFragment;"

Is there a way to build the source with androidx artifacts?

**Comment by dsn5ft** [comment]
After [building from source](https://github.com/material-components/material-components-android/blob/master/docs/building-from-source.md) you can use [Jetifier](https://developer.android.com/studio/command-line/jetifier) to update our library to reference androidx instead of android.support. E.g.:

./jetifier-standalone -i material_aars.zip -o jetified_material_aars.zip

**Comment by dsn5ft** [comment]
Our source is now migrated to androidx as of https://github.com/material-components/material-components-android/commit/dc72aaeed4cb14f914d00b538cebdcd6589d3799.
