### ISSUE TITLE
[NavigationView] itemBackground inflate exception on api 26,27,28

### ISSUE THREAD

**Issue by Shakezulla57** [material-components/material-components-android#2247]
**Description:** 
Here's the relevant exception lines
```
android.view.InflateException: Binary XML file line #45: Binary XML file line #45: Error inflating class com.google.android.material.navigation.NavigationView
...
Caused by: android.view.InflateException: Binary XML file line #45: Binary XML file line #45: Error inflating class com.google.android.material.navigation.NavigationView
Caused by: android.view.InflateException: Binary XML file line #45: Error inflating class com.google.android.material.navigation.NavigationView
...
Caused by: android.content.res.Resources$NotFoundException: Drawable com.app.app:color/navigation_item_background_color with resource ID #0x7f06010d
Caused by: android.content.res.Resources$NotFoundException: File res/color/navigation_item_background_color.xml from drawable resource ID #0x7f06010d
        at android.content.res.ResourcesImpl.loadDrawableForCookie(ResourcesImpl.java:847)
...
Caused by: org.xmlpull.v1.XmlPullParserException: Binary XML file line #3: <item> tag requires a 'drawable' attribute or child tag defining a drawable
```

**Expected behavior:** Should behave as it does on api 30

**Source code:** 
```
<com.google.android.material.navigation.NavigationView
        android:id="@+id/nav_view"
        style="@style/Widget.App.NavigationView"
        android:layout_width="wrap_content"
        android:layout_height="match_parent"
        android:layout_gravity="start"
        app:headerLayout="@layout/drawer_header"
        app:menu="@menu/navigation_drawer"
        android:fitsSystemWindows="true" />

    <style name="Widget.App.NavigationView" parent="Widget.MaterialComponents.NavigationView">
        <item name="itemTextColor">@color/navigation_item_text_color</item>
        <item name="itemBackground">@color/navigation_item_background_color</item>
    </style>

<selector xmlns:android="http://schemas.android.com/apk/res/android">
    <item android:alpha="0.2" android:color="?attr/colorPrimary" android:state_activated="true"/>
    <item android:alpha="0.2" android:color="?attr/colorPrimary" android:state_checked="true"/>
    <item android:color="@android:color/transparent"/>
</selector>
```

If I remove the `itemBackground` property it will work. This same code works on api 30.

**Android API version:** 26, 27, 28

**Material Library version:** 1.4.0-rc01

**Device:** Samsung and emulator

**Comment by karllindmark** [comment]
Hey @Shakezulla57,

I had an hour or so to kill this evening and thought I'd dig through the code a bit, as this struck me as one of those "hm I wonder how this works" type of problems. I think I have an idea about what's going on so I'll share my findings below.

After some initial staring at the code and reproducing the crash, I noticed that API 30 was producing a `ColorStateListDrawable` whilst my API 24 emulator was crashing on this line in `ResourceManagerInternal`:

![image](https://user-images.githubusercontent.com/979152/121823890-63733a00-cca8-11eb-9e59-b0561267ee73.png)

A quick Google search later provided me the following link to the Mozilla bug tracker where they encountered a similar (if not the same?) problem: https://bugzilla.mozilla.org/show_bug.cgi?id=1574028

Apparently API 29 (and onwards) has [this nifty little thing under the hood](https://cs.android.com/android/platform/superproject/+/android-10.0.0_r30:frameworks/base/core/java/android/content/res/ResourcesImpl.java;l=859) that actually handles your specific usage (`res/color/your_selector.xml` instead of `res/drawable/your_selector.xml`), as opposed to not doing so [in versions prior to API 29](https://cs.android.com/android/platform/superproject/+/android-9.0.0_r34:frameworks/base/core/java/android/content/res/ResourcesImpl.java;l=830). I think Ashley Rose [summarizes the problem way better than me](https://bugzilla.mozilla.org/show_bug.cgi?id=1574028#c10), though.

With the Mozilla bug tracker thing in mind and [the solution they went with](https://phabricator.services.mozilla.com/D42703), I thought this could be something for you:

```
<?xml version="1.0" encoding="utf-8"?>
<selector xmlns:android="http://schemas.android.com/apk/res/android">
  <item android:alpha="0.2" android:color="?attr/colorPrimary" android:drawable="?attr/colorPrimary" android:state_activated="true" />
  <item android:alpha="0.2" android:color="?attr/colorPrimary" android:drawable="?attr/colorPrimary" android:state_checked="true" />
  <item android:color="@android:color/transparent" android:drawable="@android:color/transparent" />
</selector>
```

However, that didn't really turn out as expected, as it doesn't manage to resolve the `?attr/colorPrimary` under the hood (when I tested it):

```
     Caused by: java.lang.UnsupportedOperationException: Failed to resolve attribute at index 0: TypedValue{t=0x2/d=0x7f0400c7 a=-1}
```

Hardcoding a direct color resource works though. I haven't really tried any alternative approaches here, but maybe you should be using a `StateListDrawable` directly (residing under `res/drawable`). I'll let someone with more knowledge about this subject answer that. :-)

**Comment by Shakezulla57** [comment]
@karllindmark Thanks for taking a look. I had gone through a couple of these ideas and tried some other combinations of drawable/color, api level and what not to no acceptable result. For now I'll just disable using the `itemBackground` property.

**Comment by drchen** [comment]
The crash happens inside AppCompat library. We are contacting the relevant folks and checking if this is possible to be fixed.

**Comment by drchen** [comment]
AppCompat doesn't have a plan to backport the support of loading CSL into drawables in the near future.

Please use drawable with ?attr/itemBackground instead, as how it's defined.
