### ISSUE TITLE
[CollapsingToolbarLayout] While CollapsingToolbarLayout is expanded, scroll view is not entirely visible when scrolling with keyboard

### ISSUE THREAD

**Issue by kai-vala** [material-components/material-components-android#2249]
**Description:** The bottom of the scroll view seems to be "out of bounds" while CollapsingToolbarLayout is expanded and user tries to scroll the view with keyboard only: 

https://user-images.githubusercontent.com/20531622/121896532-1041cb80-cd2a-11eb-9471-3326f791f828.mov

**Expected behavior:** 
When user scrolls the view via keyboard navigation while CollapsingToolbarLayout is expanded, the entire view should be made visible.

**Source code:**
https://github.com/kai-vala/DemoForAccessibilityBugs/tree/demo3

**Android API version:** 21, 28, 30

**Material Library version:** 1.4.0-rc01

**Device:** Simulator (API 21 and 30), Samsung S8 (API 28)

**Comment by kai-vala** [comment]
This creates an accessibility issue for us (legal requirements), so I need to fix this somehow, if you guys have any good ideas for workarounds please let me know.

**Comment by imhappi** [comment]
Temporary fix is in place until keyboard scrolling issue is fixed in androidx library: https://github.com/material-components/material-components-android/commit/9df6c9d072d927da65e5c371cea7be6bd2fff498

Note that for < API 28, note that this solution may not work properly as it sets an onKey listener on the scrollable child view in the CoordinatorLayout. The scrollable child view may not get the keys if it doesn't have focus.

**Comment by imhappi** [comment]
This issue has been addressed in androidx.core:core:1.10.0-alpha02

workaround will be removed when the fix is in stable
