### ISSUE TITLE
[TabLayout] RTL issue on api lower than 18

### ISSUE THREAD

**Issue by alishari** [material-components/material-components-android#2250]
**Description:** When tabMode is scrollable, Tabs are not scrollable to the end. Also, there is an empty space at the start of the view.

Empty Space:
<img src="https://user-images.githubusercontent.com/1575881/121955825-a222f600-cd75-11eb-9e0c-de5468139b56.png" width="240">

**Expected behavior:** You should be able to scroll tab items to the end. I do not expect to have an empty space at the start of tab items.

**Source code:** You can use material source code and change layout direction to test it.

**Android API version:** 17 and 18

**Material Library version:** 1.4.0-rc01

**Device:** Emulator API 17 and 18

**Comment by drchen** [comment]
Hey so it's actually a framework bug of the `HorizontallScrollView` class, which doesn't support RTL scrolling on API 17 & 18 (although it's supposed to.)

Unfortunately there is really nothing we can do to fix the issue on our end since the logic is deeply bound with the framework and we have no good way to workaround it.
