### ISSUE TITLE
TextInputLayout Helper text single vs multiline

### ISSUE THREAD

**Issue by RoarGronmo** [material-components/material-components-android#2304]
Please make it possible to force the helper text in TextInputLayout to be single line (even horizontal scrollable?) (or multiline as now)

![image](https://user-images.githubusercontent.com/11217296/125928182-fe1ef5b9-08b4-4fb8-9ead-507ad4976d77.png)

**Comment by drchen** [comment]
Hi, due to the limitation of the current implementation, don't really think there will be a handy solution in the near future. 

I'll suggest you set it programmatically after TextInputLayout is created by findViewById(R.id.textinput_helper_text) to retrieve the helper text view and set up the required style attributes.
