### ISSUE TITLE
Unable to find Spinner (Select Dropdown)

### ISSUE THREAD

**Issue by themhsami** [material-components/material-components-android#232]
A Spinner for Android with Design similar to Floating Input Layout https://material.io/design/components/text-fields.html

Like this for Web: https://material-components.github.io/material-components-web-catalog/#/component/select

Spinner should be provided.

**Comment by wcshi** [comment]
Does the menu component meet your needs?

https://github.com/material-components/material-components-android/tree/master/lib/java/com/google/android/material/menu

**Comment by dsn5ft** [comment]
This is available now in `1.1.0-alpha06` via [Exposed Dropdown Menus](https://github.com/material-components/material-components-android/blob/master/docs/components/Menu.md#exposed-dropdown-menus) that are based on `TextInputLayout`!

**Comment by shiomax** [comment]
To make the dropdown not editable the documentation suggests you set android:editable="false" on the AutoCompleteTextView. Android Studio sais it's deprecated and the app crashes when inflating the XML. I'm using com.google.android.material:material:1.1.0-alpha07. I don't want the user to be only able to select one of the entries in the dropdown. Not type something into the textbox.

**Comment by vkotovv** [comment]
@shiomax See #465 for notes on deprecation warning

**Comment by hameno** [comment]
I'm sorry to be so blunt, but: This implementation is a joke, right? 
Why the hell would you not use the native Spinner component? This implementation is useless for any serious use case 😞 

Short comings:
* No way to have different layouts for drop down / selected item. Selected item just used "toString" on the item of the adapter...
* No item selected callback with original model - just a "on text change", what if you have items with the same text? Did no one think of this?
* Recommended way of preventing text input does not work (android:inputType="none")
+ everything mentioned here: https://blog.usejournal.com/there-is-no-material-design-spinner-for-android-3261b7c77da8

I seriously hope you reconsider the current implementation.

**Comment by drmrbrewer** [comment]
@dsn5ft are there any plans to improve the implementation of a "spinner" in MDC?

My main gripe is that my current `Spinner` implementation uses a Custom Adapter to display a graphical sample + text for each spinner item, and when the item is selected, the text *and the graphic* is then visible as the selected item.  But with exposed dropdown menus, you only see the text, not the graphic... I guess because it is basically just an `EditText` underneath.  This is a massive backward step from a trusty `Spinner`.

Another gripe is in how the dropdown menu is displayed.  With a `Spinner`, the dropdown list is automatically aligned with the left of the `Spinner` element itself *if possible*.  But if the strings in the dropdown are too lengthy, the whole dropdown list is automatically positioned to display the whole strings (again, if possible) by shifting it within the parent view.  But with the MDC version of spinners, this doesn’t seem to happen… the dropdown aligns with the spinner element and the longer text is just truncated… yes you can apply a horizontal offset but this seems to be a fixed offset rather than an offset which is worked out based on what needs to be shown.

Doesn't seem very satisfactory.  I've transitioned all of my other UI elements to MDC, and am really happy... but for now I can't transition `Spinner` because of the above limitations.
