### ISSUE TITLE
[Chip] Chip setting style via code is not as easy as other views

### ISSUE THREAD

**Issue by DavidCorrado** [material-components/material-components-android#2356]
**Description:**
Setting style via xml seems to work.  Setting style via attr seems to work.  But setting a style form a style name directly does not seem to work.  Below are some stackoverflows on this
https://stackoverflow.com/questions/53557863/change-chip-widget-style-programmatically-not-working-android
https://stackoverflow.com/questions/55318552/how-to-apply-a-style-for-a-chip-in-code

**Expected behavior:** Screenshots and/or description of expected behavior
In general I like to set a style for a view via ContextThemeWrapper as shown below but it does not work
https://stackoverflow.com/questions/3142067/set-style-for-textview-programmatically

**Source code:** 
See stack overflow

**Android API version:** 
30

**Material Library version:** 
1.4.0

**Device:** 
Pixel 5

To help us triage faster, please check to make sure you are using the [latest version](https://github.com/material-components/material-components-android/releases) of the library.

We also happily accept [pull requests](https://github.com/material-components/material-components-android/pulls).

**Comment by drchen** [comment]
You can provide a "theme" (instead of style) and set R.attr.ChipStyle to your custom style to create your ContextThemeWrapper instead. (Note that ContextThemeWrapper is used to wrap "themes" instead of styles. The approach you mentioned is a misuse.)

Also consider all the possible alternatives mentioned in the first stackoverflow link you pasted.
