### ISSUE TITLE
It seems that property "insetXXX" doesn't work with Button

### ISSUE THREAD

**Issue by ung8023** [material-components/material-components-android#236]
## Description
I tried to use a material Button, but it seems that it has default margin, I tried to set "insetXXX",it didn't work.

## drawable
![image](https://user-images.githubusercontent.com/12079626/49267374-125a1c80-f495-11e8-9434-699ed5bd6dd9.png)

## code
```xml
<Button
        android:layout_width="228dp"
        android:layout_height="89dp"
        android:backgroundTint="@color/colorAccent"
        />
```

**Comment by gsajith** [comment]
Hello, looking into this now. I'm unable to reproduce this issue locally, as setting android:insetXXX exhibits the expected behavior.

Could you please file an issue at https://issuetracker.google.com/issues/new?component=439535 with more details?

Namely, your source code where you specify the inset, and Android version/device this reproduces on.

Thanks!

**Comment by PureWeen** [comment]
@ung8023  did you get this resolved or log an issue with the issuetracker?

**Comment by ung8023** [comment]
@PureWeen sorry, I didn't log it.

**Comment by calmmycode** [comment]
same here
