### ISSUE TITLE
MD3 BottomNavigationBar Active indicator wrong height

### ISSUE THREAD

**Issue by umerov1999** [material-components/material-components-android#2430]
If I set Unlabled mode, Active Indicator gets the wrong height. But if you add Badge, then the height becomes normal
![56565656](https://user-images.githubusercontent.com/3888404/137460453-6f75a999-500b-4fbc-9af0-6d31b292b1e2.jpg)
.

**Comment by umerov1999** [comment]
> What are the values you're using for your BottomNavigationView's `android:height`, `android:minHeight`, `app:itemPaddingTop`, and `app:itemPaddingBottom`?

i used android: height 48dp or wrap_content.  The result is the same.  minHeight, itemPagingTop / Bottom I didn't use

**Comment by hunterstich** [comment]
If you're setting `android:height` to anything other than `wrap_content` the indicator might get clipped since, by default when using a Material3 style, `itemPaddingTop` (defaults to 4dp) and `itemPaddingBottom` (defaults to 8dp) are pushing the icon/indicator and text labels in towards the vertical center of the bar. If you want to use a specific height for your bottom navigation bar, you can decrease itemPaddingTop and itemPaddingBottom to avoid the clipping/pushing. Alternatively, you can increase the height of your BottomNavigationBar or decrease the height of the [active indicator ](https://github.com/material-components/material-components-android/blob/master/lib/java/com/google/android/material/bottomnavigation/res/values/styles.xml#L80-L86)

Does that make sense?

**Comment by LRCD** [comment]
> @umerov1999 going to go ahead and close this but please re-open or comment if you have more questions or issues!

I have an Issue please help. My App is already Migrated to Material3. Everything works but BottomNavigationView doesn't show Indicator. I've Followes Material Catalog Source in this repo.

**Comment by hunterstich** [comment]
@LRCD Can you add some additional info like your layout XML, Theme and any styles your setting on your BottomNavigationView?

**Comment by hunterstich** [comment]
Never mind I see you've filed https://github.com/material-components/material-components-android/issues/2494
