### ISSUE TITLE
[HideBottomViewOnScrollBehavior] I want the Snackbar to follow the movement of the BottomNavigationView.

### ISSUE THREAD

**Issue by Pinoshino2** [material-components/material-components-android#2432]
**Is your feature request related to a problem? Please describe.**
I want the BottomNavigation and Snackbar to be displayed on the same screen. Also, for BottomNavigation's Behavior, I specify HideBottomViewOnScrollBehavior.

When I try to show the Snackbar by simply specifying HideBottomViewOnScrollBehavior for `app:layout_behavior`, the Snackbar is hidden behind the BottomNavigation as shown in the following recording.

https://user-images.githubusercontent.com/42328337/137682534-f5b9e297-43ea-48b5-b47b-5c77877d5d48.mp4

**Describe the solution you'd like**
As mentioned in [MATERIAL DESIGN](https://material.io/components/snackbars#placement), the Snackbar should be placed above the BottomNavigationView. I also want the Snackbar to move as the BottomNavigationView moves.
So, the ideal behavior would look like the following recording.

https://user-images.githubusercontent.com/42328337/137081304-ca30b197-0af3-4eaa-95a3-3b3ed0255db8.mp4

**Describe alternatives you've considered**
I have mentioned in [this issue](https://github.com/material-components/material-components-android/issues/2425) how to implement this behavior.
I can achieve the expected behavior by specifying Snackbar as the anchor for BottomNavigationView.
Here is the code I wrote. I create a custom behavior.

```kt
// kt
class CustomHideBottomViewBehavior(context: Context, attrs: AttributeSet) : HideBottomViewOnScrollBehavior<BottomNavigationView>(context, attrs) {

    // this value is the default margin for Snackbar.
    private val bottomMargin: Int = context.resources.getDimensionPixelSize(R.dimen.mtrl_snackbar_margin)

    override fun layoutDependsOn(parent: CoordinatorLayout, child: BottomNavigationView, dependency: View): Boolean {
        if (dependency is Snackbar.SnackbarLayout) {
            updateSnackbarPosition(child, dependency)
        }
        return super.layoutDependsOn(parent, child, dependency)
    }

    private fun updateSnackbarPosition(child: View, snackbarLayout: Snackbar.SnackbarLayout) {
        val params = snackbarLayout.layoutParams
        if (params is CoordinatorLayout.LayoutParams) {
            params.anchorId = child.id
            params.gravity = Gravity.TOP or Gravity.CENTER_HORIZONTAL
            params.anchorGravity = Gravity.TOP or Gravity.CENTER_HORIZONTAL
            params.bottomMargin = 0
            snackbarLayout.layoutParams = params
            snackbarLayout.translationY = -bottomMargin.toFloat()
        }
    }
}
```

```xml
<!-- xml -->
<com.google.android.material.bottomnavigation.BottomNavigationView
    android:id="@+id/bottomNavView"
    android:layout_width="match_parent"
    android:layout_height="@dimen/bottom_nav_height"
    android:layout_gravity="bottom"
    app:layout_behavior="CustomHideBottomViewBehavior"
    />
```

In this code, I can't use `Snackbar.setAnchorView()` method, so we use the `CoordinatorLayout.LayoutParams.setAnchorId()`.
I would like to see that the SDK will be implemented in such a way that this behavior can be achieved without creating a custom behavior.

**Additional context**
Ideally, it would be nice if Snackbar could automatically find anchors for BottomNavigation, FAB, etc.

**Comment by drchen** [comment]
Can you elaborate why can't you use `Snackbar.setAnchorView()` method, which is provided for this purpose?

**Comment by drchen** [comment]
Hi, so the concern here is, logically speaking, the requested feature is "making snackbar automatically depend on BottomNavigationView" - in other words, the behavior needs to be implemented on the snackbar side, instead of the bottom navigation view side. And we already have this behavior implemented via anchor views. 

What https://github.com/material-components/material-components-android/issues/2432#issue-1028729771 is trying to do is kind of a misuse of layoutDependsOn() - the method is intended to specify the holder of the behavior (in this case, the bottom navigation view) should depend on another child of the coordinator layout (in this case, the snackbar) - we cannot really incorporate it into our library because it can be fragile and not scalable. 

Also it doesn't seem right to make this as a default behavior of snack bars. BottomNavigationView is just a special case, and as a library what we are aiming at is supporting behavior customization in a generic way. 

Given that we already have support for clients to implement this behavior, I'll close this request as a no-go.
