### ISSUE TITLE
[cardview] I hope I can define the shadow attribute of cardview more freely

### ISSUE THREAD

**Issue by BraveHL** [material-components/material-components-android#2508]
**Is your feature request related to a problem? Please describe.**
A clear and concise description of what the problem is.

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

We also happily accept [pull requests](https://github.com/material-components/material-components-android/pulls).

When developing an app, we often need to use the card layout. At this time, we will use cardview, but there are similar and richer designs around the card designed by the designer, such as lighter color shadows and color shadows. However, cardview itself cannot modify the color of the shadow, which makes us very painful when using cardview. Please improve it as soon as possible, Allow developers to configure more properties of cardview

**Comment by raajkumars** [comment]
While it is possible to change the shadow color either using the stock methods in View class (since P) or using the MaterialShapeDrawable, Material Design does not recommend this because apps following Material guidelines must provide a consistent user experience. Typically, the color of a shadow is always a shade of grey color. 

Hope this answers your question. If you still feel that the card view must directly support changing of shadow colors, please feel free to reopen this issue to provide us some examples (mock implementations / screenshots), so that we can better understand your specific need.
