### ISSUE TITLE
[BottomNavigationView] round corner

### ISSUE THREAD

**Issue by LeonChen1024** [material-components/material-components-android#2510]
**Describe the solution you'd like**
shapeAppearanceLargeComponent could affect corners , or provide a property to affect BottomNavigationView corners

**Comment by drchen** [comment]
Hi, I think corners of BottomNavigationView are intended to be square by design, so I'm not sure if in the near future we will support it to be customized.

As an alternative I think you can create a new MaterialShapeDrawable with the corner size you want and set it as your BottomNavigationView's background. Hope this helps!

**Comment by LeonChen1024** [comment]
> 
thanks
