### ISSUE TITLE
[Typography] Material3 theme is missing some styles the were previously available in MaterialComponents

### ISSUE THREAD

**Issue by y20k** [material-components/material-components-android#2518]
I am currently adapting my app theme to **Material3**. In the process of substituting typography styles from the older **MaterialComponents** I found that some older styles do not have a Material3 equivalent.

In my case I am missing the following styles in Material3:

1. [`textAppearanceHeadline6`](https://github.com/material-components/material-components-android/commit/333dceaa638eccb18fe7101f4049f6b3217c3657#diff-6e384148bced15bcd0774c9cf6c3be1aa27775d63f1fcf30e22397708cc633f9L31) = a 20sp Material3 headline
=> my problem: I am using a Headline6 in a CardView. The closest Material3 equivalent is TitleLarge. Given space restraints in my CardView TitleLarge (22sp) is too large and TitleMedium (16sp) is too small. 
2. [`textAppearanceButton`](https://github.com/material-components/material-components-android/commit/333dceaa638eccb18fe7101f4049f6b3217c3657#diff-6e384148bced15bcd0774c9cf6c3be1aa27775d63f1fcf30e22397708cc633f9L37) = a Material3 button text style
=> my problem: not really a problem that distorts an existing layout like 1... but still I was wondering, why there is no distinct styling suggestion for text in a button.

I guess the decision to not provide those styles in Material3 was intentional. And I know that my problems are probably just "my problems" and are of no general relevance. So feel free to close this issue. But still I wanted to let you know of the problems I encountered in practice.

**Comment by dsn5ft** [comment]
Hi @y20k, definitely not just your problems, we really appreciate the feedback.

1. You may have already done something like this, but for this case I think I would suggest making your own text appearance that inherits from `TextAppearance.Material3.TitleLarge`, sets the text size to 20sp, and remaps `textAppearanceTitleLarge` in your app theme to your new text appearance - if you think the slightly smaller text size will be a better fit throughout your app. You could also just make a more specific text appearance if you only want to use it for CardViews. I think the reason for the larger 22sp default text size is because as part of M3, Top App Bars (and some components in general) grew a bit vertically, so they can accommodate larger text.

2. In the new M3 system, Buttons now use [`textAppearanceLabelLarge`](https://github.com/material-components/material-components-android/blob/master/docs/theming/Typography.md#usage), as opposed to having an explicit type scale entry like `textAppearanceButton` which feels a little too specific and out of place with the rest of the type scale.
