### ISSUE TITLE
[TextInputLayout] Add a textInputExposedDropdownMenuStyle attribute

### ISSUE THREAD

**Issue by eygraber** [material-components/material-components-android#2519]
I'm creating a library that has a custom view that combines regular `TextInputLayout` and `TextInputLayout` meant to be used as an exposed dropdown menu.

I'm setting the style of the regular `TextInputLayout` to be `?attr/textInputStyle`, but for the menu, I have to choose between outlined and filled.

It would be helpful if there was a `textInputExposedDropdownMenuStyle` attribute to use so I could delegate that decision.

**Comment by leticiarossi** [comment]
Hi there! Unfortunately that's not possible to implement because the `ExposedDropdownMenu` is not a class itself, it's a `TextInputLayout` style.

The `TextInputLayout` class uses `?attr/textInputStyle` as its default style, which gets overridden when there's another style specified by the user. In our theme that defaults to an outlined text field. It's not possible to have another default for the same class, which is why you always have to specify an `ExposedDropdownMenu` style when using the dropdown menus.

The other text field style attrs we have (like `?attr/textInputOutlinedExposedDropdownMenuStyle`, `?attr/textInputFilledExposedDropdownMenuStyle`, etc)  are for convenience (for example, you can just use the attr in your xml layouts instead of the entire `Widget.Material3.TextInputLayout.(...)` path - it also makes setting custom styles simpler).
