### ISSUE TITLE
[Theme.Material3.Light] 'DynamicColors.applyToActivitiesIfAvailable()' affect on 'forcedarkAllowed = true' behavior

### ISSUE THREAD

**Issue by VicMikhailau** [material-components/material-components-android#2521]
Hi, 
**Description:** The App use `Theme.Material3.Light.NoActionBar` theme with `android:forceDarkAllowed = true` attribute.
Also applied 'Dynamic Colors' feature through `DynamicColors.applyToActivitiesIfAvailable()`. In-App colors don't tailor to the enabled Dark Theme (exclude dialogs). With disabled 'Dynamic Colors' feature, all work fine.
It is expected behavior?

**Expected behavior:** Colors must be changed according to the `forceDarkAllowed = true` attribute.

**Source code:** 
```
<style name="MainTheme" parent="Theme.Material3.Light.NoActionBar">
        ...
      <item name="android:windowBackground">@android:color/white</item> -- stayed as is.
      <item name="android:forceDarkAllowed">true</item>
        ...
    </style>
```

**Android API version:** 31

**Material Library version:** 1.5.0-rc01 or 1.6.0-alpha01

**Device:** Pixel 4a

Thanks.

**Comment by dsn5ft** [comment]
Hi @VicMikhailau, thanks for reporting this.

I did some debugging and found that calling `Activity#setTheme`, which is done by `DynamicColors.applyToActivitiesIfAvailable()`, is the thing that breaks the Force Dark behavior. I even tried setting a completely empty theme overlay like `setTheme(R.style.ThemeOverlay_ForceDark_Empty)` where `ThemeOverlay.ForceDark.Empty` has `parent=""` and no attributes, and that still broke Force Dark for some reason.

However, I found that using `Activity#getTheme#applyStyle` instead of `Activity#setTheme` doesn't break Force Dark. So a workaround for this issue should be the following:

```
  override fun onCreate(savedInstanceState: Bundle?) {
    if (DynamicColors.isDynamicColorAvailable()) {
      theme.applyStyle(R.style.ThemeOverlay_Material3_DynamicColors_DayNight, true)
    }
    super.onCreate(savedInstanceState)
  }
```

Can you try that and let us know if that works for you? We will consider updating our `DynamicColors` util to do the same, and reach out to the Android framework team to hopefully figure out the underlying issue here.

**Comment by VicMikhailau** [comment]
@dsn5ft Thanks a lot.
I have tried the solution described above (applied to the parent Activity onCreate method) and see that has been partially changed color only some widgets like BottonNavigationview, FAB, switchers.

**Comment by dsn5ft** [comment]
No problem, so does that mean it's working as you expect?

**Comment by VicMikhailau** [comment]
@dsn5ft Unfortunately not. Looks like in this case changed color only for widgets like BottonNavigationview, FAB, switchers (parts with dynamic colors changed as expected). But e.g. background of activity (and fragments inside) and etc. stayed white.

**Comment by dsn5ft** [comment]
Hmm the Activity background seems to be automatically switching to dark as expected for me, so not sure what the difference with your app is:

![image](https://user-images.githubusercontent.com/1420597/149982981-c7d4c795-081f-4d8a-b1c0-298689fbdb2c.png)

**Comment by VicMikhailau** [comment]
@dsn5ft In sample above also using `DynamicColors.applyToActivitiesIfAvailable()`?
