### ISSUE TITLE
[TextInputLayout] setEndIconMode clears the current end icon drawable

### ISSUE THREAD

**Issue by DeuceTheCoder** [material-components/material-components-android#2528]
**Description:** When calling setEndIconMode, the current end icon drawable is set to null

**Expected behavior:** Any previously set icons will still be present

**Source code:**
```Kotlin
textInputLayout.setEndIconDrawable(R.drawable.ic_validation_pass)
textInputLayout.endIconMode = END_ICON_CUSTOM // end icon drawable is removed
textInputLayout.endIconContentDescription = validationPassDescription
```

**Android API version:** Android API 30

**Material Library version:** 1.5.0

**Device:** Emulator API 29

To help us triage faster, please check to make sure you are using the [latest version](https://github.com/material-components/material-components-android/releases) of the library.

We also happily accept [pull requests](https://github.com/material-components/material-components-android/pulls).

**Comment by leticiarossi** [comment]
Hi there! The expected programmatic usage of the end icon mode API is to first set the mode, then set any customizations. 

That is because calling `setEndIconMode` will initialize the icon with its default features. In the case of the custom mode, that means it'll have an empty icon, since its icon should be a custom drawable that the user will specify. Therefore a drawable set via `setEndIconDrawable` will be cleared if the current icon mode is switched. The only exception to that is if a drawable was set in XML via `app:endIconDrawable`, which will have precedence over any defaults.

I'll update the [documentation](https://github.com/material-components/material-components-android/blob/master/docs/components/TextField.md#adding-a-trailing-icon-to-a-text-field) to make things clearer.
