### ISSUE TITLE
[RangeSlider] Part of the label still remains after sliding with Huawei phones

### ISSUE THREAD

**Issue by Arnold-Abacus** [material-components/material-components-android#2624]
**Description:** 
When using RangeSlider with Huawei Android 9 phones the label does not disappear completely after adjusting. Parts of the label still remain on the screen.

**Expected behavior:** 
Label is disappearing

**Source code:** 
```
<?xml version="1.0" encoding="utf-8"?>
<androidx.constraintlayout.widget.ConstraintLayout xmlns:android="http://schemas.android.com/apk/res/android"
    xmlns:app="http://schemas.android.com/apk/res-auto"
    xmlns:tools="http://schemas.android.com/tools"
    android:layout_width="match_parent"
    android:layout_height="match_parent"
    android:paddingTop="80dp"
    tools:context=".MainActivity">

    <com.google.android.material.slider.RangeSlider
        android:id="@+id/amountSlider"
        android:layout_width="match_parent"
        android:layout_height="wrap_content"
        android:stepSize="1"
        android:valueFrom="0.0"
        android:valueTo="100.0"
        app:values="@array/initial_slider_values"
        tools:ignore="MissingConstraints" />

</androidx.constraintlayout.widget.ConstraintLayout>
```

![image](https://user-images.githubusercontent.com/72196651/161275659-6fb550ac-eb45-4497-b7d8-b0d76aca45ea.png)

**Android API version:** 31

**Material Library version:** 1.5.0 (also tried 1.6.0-beta01)

**Device:** Huawei P20 Pro, Android 9

**Comment by Arnold-Abacus** [comment]
So far I could only see it on Huawei devices with Android 9. I was not able to test it on Huawei devices with a newer Android version. Other devices don't have this issue.

**Comment by drchen** [comment]
If that's the case I'm afraid that it's an OEM bug on a certain version, maybe related to ViewOverlay implementation.

I don't have a Huawei device with me but can you try to add a check here:
https://github.com/material-components/material-components-android/blob/master/lib/java/com/google/android/material/internal/ViewUtils.java#L283

So if it's a Huawei device with Android 9, it uses `ViewOverlayApi14.createFrom(view)` instead of `new ViewOverlayApi18(view)`. 

If this doesn't work either, I'm afraid that there's not much we can do.

**Comment by drchen** [comment]
I'll close this issue for now due to no further info available. Please feel free to reopen it if this is still happening.

**Comment by zuhriddinjon** [comment]
Hello, is there a solution to this problem?
