### ISSUE TITLE
Snackbar Material 3 theme overlay

### ISSUE THREAD

**Issue by ArcherEmiya05** [material-components/material-components-android#2661]
**Description:**
I am following the Material 2 [doc](https://material.io/components/snackbars/android#theming-snackbars) for Snackbar.
However it does not apply with Material 3, how can we style Snackbar in Material 3 because currently none of the specified value color gets applied.

**Source code:** 
```
<!-- Snackbar style on both light and night mode -->
    <style name="AppSnackbar" parent="Widget.Material3.Snackbar">
        <item name="materialThemeOverlay">@style/ThemeOverlay.App.Snackbar</item>
        <item name="actionTextColorAlpha">1</item>
    </style>

    <style name="Widget.App.SnackbarButton" parent="Widget.Material3.Button.TextButton.Snackbar">
        <item name="android:textColor">@color/colorPrimary_Accent</item>
    </style>

    <style name="ThemeOverlay.App.Snackbar" parent="">
        <!-- Text color -->
        <item name="colorPrimary">@color/colorPrimary_Accent</item>
        <!-- Background color -->
        <item name="colorSurface">@color/colorWhite_Primary</item>
        <item name="colorOnSurface">@color/colorWhite_Primary</item>
    </style>
```

Usage
`
<item name="snackbarStyle">@style/AppSnackbar</item>`

**Android API version:** 21

**Material Library version:** 1.7.0-alpha01

**Device:** Samsung J1

**Comment by dsn5ft** [comment]
Hi @ArcherEmiya05, this is the [source code](https://github.com/material-components/material-components-android/blob/master/lib/java/com/google/android/material/snackbar/res/layout/mtrl_layout_snackbar_include.xml) for the layout used by Snackbar.

Instead of `snackbarStyle`, can you try using `snackbarTextViewStyle` (extend from `Widget.Material3.Snackbar.TextView`) and `snackbarButtonStyle` (extend from `Widget.Material3.Button.TextButton.Snackbar`) in your theme?

I think that should work and give you full flexibility for text colors and other attributes for the message / action button, but feel free to reopen if you're still having issues.

**Comment by dsn5ft** [comment]
Oh, looking at the [source code](https://github.com/material-components/material-components-android/blob/921868d31ba733b99c7175fbc7dfa7678f4a2fa5/lib/java/com/google/android/material/snackbar/res/values/styles.xml#L73) for the M3 Snackbar style, instead of `materialThemeOverlay`, can you try using `backgroundTint`?

**Comment by ArcherEmiya05** [comment]
> `backgroundTint`

Yes it works, but can't we use `materialThemeOverlay` for Snackbar in Material 3?

**Comment by dsn5ft** [comment]
`materialThemeOverlay` still works, but it's not how the background is determined for M3 Snackbars.

**Comment by ArcherEmiya05** [comment]
> `materialThemeOverlay` still works, but it's not how the background is determined for M3 Snackbars.

So we can't change Snackbar background color using `materialThemeOverlay` in M3 is that correct?

**Comment by drchen** [comment]
Actually you can. But the color attribute you need to override is `?attr/colorSurfaceInverse`. : )
