### ISSUE TITLE
[Build] Error when trying to build app with 1.7.0-alpha02

### ISSUE THREAD

**Issue by fcduarte** [material-components/material-components-android#2722]
Hi team,

I'm not much familiar with the `<macro>` tag but just by trying to bump the lib to 1.7.0-alpha02 I'm getting the following error:

```
Resource and asset merger: Can't determine type for tag '<macro name="m3_comp_switch_disabled_selected_handle_color">?attr/colorSurface</macro>'
```

I spent some time building it from the source and saw this was newly added but I'm not sure how to solve. Is it a missing step that is not part of the docs? Sorry for not being able to provide more details, appreciate if you can take a look. Thanks!

**Comment by afohrman** [comment]
Hi Felipe, you'll need to update your project's Gradle version to [7.3.3](https://developer.android.com/studio/releases/gradle-plugin#updating-gradle) and AGP version to [7.2.0](https://developer.android.com/studio/releases/gradle-plugin#updating-gradle) in order to use version `1.7.0-alpha02` and later. Please see the [release notes](https://github.com/material-components/material-components-android/releases/tag/1.7.0-alpha02) for more information about new minimum requirements for `1.7.0-alpha02`.

**Comment by fcduarte** [comment]
@afohrman ah thanks, I missed those steps! At least if somebody Googles the error now there's a good reference :D
