### ISSUE TITLE
[AppBarLayout] background color when setting DynamicColors

### ISSUE THREAD

**Issue by 0x7e57** [material-components/material-components-android#2813]
**Description:** The background color of the AppBarLayout is different from the background color of the parent (CoordinatorLayout) when setting DynamicColors.applyToActivityIfAvailable(this) on the activity. If DynamicColors is not set, then they have the same background color.

**Expected behavior:** Setting DynamicColors should not affect the background color of the AppBarLayout

**Source code:** `DynamicColors.applyToActivityIfAvailable(this)`

**Android API version:** 31

**Material Library version:**  com.google.android.material:material:1.7.0-alpha02

**Device:** realme 8

without DynamicColors
![without_DynamicColors](https://user-images.githubusercontent.com/65600288/178758083-e5b59b91-617c-4e6f-8bc2-1b56cf218a41.jpg)

with DynamicColors
![with_DynamicColors](https://user-images.githubusercontent.com/65600288/178758090-872c80e2-fa1f-4bc4-8594-cac8cf233d1f.jpg)

**Comment by 0x7e57** [comment]
The problem seems to be the call to `installSplashScreen()` provided by _'androidx.core:core-splashscreen:1.0.0-rc01'_

**Minimal sample app repro:** [DynamicColors](https://github.com/0x7e57/DynamicColors.git)

**Comment by drchen** [comment]
If you call `DynamicColors.applyToActivityIfAvailable(this)` before `super.onCreate()`, will it work?

If not, can you try to explicitly call setTheme(Theme.DynamicColors) before `DynamicColors.applyToActivityIfAvailable(this)` and see if it works?

**Comment by 0x7e57** [comment]
I got the expected behavior just in this case:
```
class MainActivity : AppCompatActivity() {

    override fun onCreate(savedInstanceState: Bundle?) {
        setTheme(R.style.Theme_DynamicColors)
        DynamicColors.applyToActivityIfAvailable(this)
        installSplashScreen()
        super.onCreate(savedInstanceState)
        setContentView(R.layout.activity_main)
    }
}
```
However, I see this as only a temporary solution. In his absence, I would like this case to be described in the documentation.

**Comment by drchen** [comment]
Cool! Glad to hear this works! I'm trying to consult with the framework team regarding how installSplashScreen() and postSplashScreenTheme are supposed to work. Hope I can get a better answer soon!

**Comment by drchen** [comment]
btw if you do it like this, will it work? 

```
class MainActivity : AppCompatActivity() {
    override fun onCreate(savedInstanceState: Bundle?) {
        installSplashScreen()
        DynamicColors.applyToActivityIfAvailable(this)
        super.onCreate(savedInstanceState)
        setContentView(R.layout.activity_main)
    }
}
```

**Comment by 0x7e57** [comment]
No, the background color of the AppBarLayout and its parent will be different.
_Set some green wallpaper._ 
**Result:**
![Screenshot_2022-08-03-06-57-42-46_915c8083507acdfb0d121b20c02ec2fd - копия](https://user-images.githubusercontent.com/65600288/182536999-edcd1723-f1ec-4b28-9258-a4558229be21.jpg)
If the difference is not noticeable, look at it from a different angle.
The only working case is described above, with the call:
```
setTheme(R.style.Theme_DynamicColors)
DynamicColors.applyToActivityIfAvailable(this)
```
before calling `installSplashScreen()`
**Result:**
![Screenshot_2022-08-03-06-58-12-96_915c8083507acdfb0d121b20c02ec2fd](https://user-images.githubusercontent.com/65600288/182538031-972c2129-6617-424c-b529-b22c9cdec1a3.jpg)

**Comment by drchen** [comment]
Hi, thanks for helping check out.

I talked to the Android framework team and it seems like an unfortunate bug when using `installSplashScreen()` together with Material's `DynamicColors` class.

In short, in `installSplashScreen()`, the framework will get/create decor view after setting `postSplashScreenTheme` to the activity, before dynamic colors are applied, so that's why the background color is not rendered in the dynamic colors. 

It's impossible for us to fix the behavior on S - we have no way to intervene what `installSplashScreen()` is doing. If `setTheme()` first works for you, I guess that's the best/simplest workaround we can have here.

If you will always apply dynamic colors if they are available, another safer (but more complicated) solution is override all color attributes in your `postSplashScreenTheme` with the values defined [here](https://github.com/material-components/material-components-android/blob/master/lib/java/com/google/android/material/theme/res/values-v31/themes_overlay.xml#L22). In this way you will have to handle day/night variants on your own, though.

Hope this helps!
