### ISSUE TITLE
Rotating any view 180 degrees causes shadow to disappear completely

### ISSUE THREAD

**Issue by therealbluepandabear** [material-components/material-components-android#2956]
Hello,

I know I am fighting against a massive corporation, but I have tried my best to get at least _someone_ that works with Skia/MaterialComponents to fix this annoying issue which has destroyed my codebase.

I am working on a paint app, and in this app, the user has the option to rotate the canvas, this feature can be useful in some scenarios.

The problem I am having, is that when I rotate the `MaterialCardView`, which hosts the canvas/bitmap, 180 degrees -- the drop shadow (card elevation) disappears. I do not get this problem when I rotate the `MaterialCardView` any angle but 180 degrees, only 180 degrees.

Below are some examples:

0 degrees:

![image](https://user-images.githubusercontent.com/50536495/188256914-a7ee5f94-6b31-4aa7-93bb-308f72468eac.png)

180 degrees:

![image](https://user-images.githubusercontent.com/50536495/188256918-4af45425-4d74-470b-be65-ab4947538b96.png)

My app is greatly suffering because of this bug as I've had to resort to quite frankly terrible workarounds -- such as setting the rotation as `179.9`.

Upon doing more research I discovered that this issue was reported twice in IssueTracker:

https://issuetracker.google.com/issues/173730323

https://issuetracker.google.com/issues/137454913

To my shock, it was marked as resolved. 

This issue is NOT resolved in Android at least, and is easily reproducible when creating a new project in Android Studio Dolphin. With all due respect, it's just absolutely insane that this bug still exists, and I have had to deal with at least 5 bugs because of the workaround that someone helped me come up with. I also have to delay the release of my next app's version because of all the bugs because of this issue.

My codebase is also greatly suffering because of the workaround. It's almost as if you guys don't care about developers and are just sweeping this issue under the rug. Release after release after release and absolutely no comment in regards to this issue.

# Can you please patch this bug?

**Comment by OxygenCobalt** [comment]
The material devs don't respond to issues when they are off. They'll probably get back to you in Tuesday.

**Comment by patzly** [comment]
Im also no MDC dev but I don't really understand why you are rotating the entire container view. As far as I know from my work with canvas, you could easily call `canvas.save()` and `canvas.rotate(180, canvas.getWidth() / 2f, canvas.getHeight() / 2f)` before the paths/lines/shapes are drawn in the `onDraw()` method of your custom view and then `canvas.restore()` when all content was drawn. For example:
``` java
@Override
protected void onDraw(Canvas canvas) {
  // Save and rotate canvas
  canvas.save();
  canvas.rotate(180, getWidth() / 2f, getHeight() / 2f);
  // Now draw the data from touch input e.g.
  canvas.drawPath(pathUserLine, paintUserLine);
  // Restore canvas
  canvas.restore();
}
```

With this method you can leave the container view untouched.
From my point of view regarding design, I would prefer an outline (app:cardStrokeColor/Width) instead of a shadow because the shadow makes the top border kind of blurred and hard to see regarding contrast. Then the problem would also be no longer present.
Also you shouldn't blame the MDC developer team for the problem (I think this issue is therefore "invalid" here), they are not responsible for issues on system level like shadow rendering, as you can read in the Issue Tracker.

**Comment by patzly** [comment]
Okay, then you could put them together into one FrameLayout and put this into the CardView, then you can rotate the FrameLayout.

**Comment by patzly** [comment]
That might be the case, but in general for 180 degrees there always is the workaround I said. It's a more or less rare case that a view with elevation has to be rotated 180 degrees in my opinion and it would be unnecessarily much internal work on shadow rendering or rendering in general only to fix this rare case.

Just pack your views inside of a FrameView and rotate this FrameView instead of the container CardView, then you no longer have any issues.

**Comment by drchen** [comment]
1. It's an Android framework issue, not a Material library issue. A fix definitely won't reside on the library end, and we really don't have the expertise to fix it either.
2. Per what issue tracker said, this should be fixed on Android R+. Did you try this on Android R or S?
3. Issue tracker is the best way to reach out to the relevant framework team, even for us it's the same. So if this is a huge blocker to your app/work, please file a new issue to the issue tracker and highlight that you think this has not been fixed.
