### ISSUE TITLE
[Material You] isDynamicColorAvailable returns true in AS preview

### ISSUE THREAD

**Issue by rlatapy-luna** [material-components/material-components-android#2972]
`DynamicColors.isDynamicColorAvailable()` returns true when running (compose) preview in Android Studio, resulting in the use of default material color scheme. `LocalInspectionMode.current` allows to check if the composition is running in a preview, but it would nice if it could be handle by `DynamicColors.isDynamicColorAvailable()`

https://github.com/material-components/material-components-android/blob/6631abbdb53e789589951452f99d1e0bbedd30bd/lib/java/com/google/android/material/color/DynamicColors.java#L341

**Comment by drchen** [comment]
Can you provide more details? Like how you apply color scheme according to isDynamicColorAvailable()?

**Comment by rlatapy-luna** [comment]
> Can you provide more details? Like how you apply color scheme according to isDynamicColorAvailable()?

```kotlin
val colorScheme = when {
    DynamicColors.isDynamicColorAvailable() && isSystemInDarkTheme() -> dynamicDarkColorScheme(LocalContext.current)
    DynamicColors.isDynamicColorAvailable() -> dynamicLightColorScheme(LocalContext.current)
    isSystemInDarkTheme() -> darkColorScheme
    else -> lightColorScheme
}

MaterialTheme(
    colorScheme = colorScheme,
    ...
) {
    ...
}
```

And now I'm using
```kotlin
@Composable
fun isDynamicColorAvailable(): Boolean = !LocalInspectionMode.current && DynamicColors.isDynamicColorAvailable()
```

**Comment by drchen** [comment]
So the DynamicColors class is created for the general Android usages (both Views and Compose). Unfortunately it's not able for us to add Compose-specific functions like LocalInspectionMode into it. 

If you need certain support in the Material Compose library, please report an issue to:
https://issuetracker.google.com/issues?q=status:open%20componentid:742043

I'll close the issue for now since this repo is specific to Material Android Views.
