### ISSUE TITLE
[BottomAppBar] RTL layout doesn't match M3 guidelines

### ISSUE THREAD

**Issue by patzly** [material-components/material-components-android#2984]
**Description:** Although I don't quite understand why the BottomAppBar shouldn't switch to RTL layout normally, M3 design guidelines say it shouldn't:

[https://m3.material.io/components/bottom-app-bar/guidelines](https://m3.material.io/components/bottom-app-bar/guidelines)

### Section: Responsive layout > Alignement

> Align the layout of elements to the edges of the container. This means the primary action, such as the FAB, is on the right, and secondary actions, such as icon buttons, are on the left.
This arrangement reinforces the hierarchy of actions. **It remains the same no matter the reading direction of the screen’s language.**

And the image description also says:

> **Bottom app bar alignment is the same whether the text is a right-to-left (RTL) or left-to-right (LTR) language.**

 This behavior is not implemented in the library yet, the FAB is on the left for RTL languages.

**Expected behavior:** Match the M3 specs regarding alignment behavior for BottomAppBar in RTL layout mode.

**Android API version:** 33

**Material Library version:** 1.8.0-alpha01

**Comment by pekingme** [comment]
Good catch! Will update the style to enforce this.

**Comment by imhappi** [comment]
Ah I had actually discussed this with the designer

I guess the specs doc never got updated :/ but we had agreed to _not_ enforce the LTR-ness of bottom app bar, because as you say, the behavior was strange/out of place with the rest of the components. Eg. bottom app bar not matching the top app bar's LTR state is weird.

I'll make a request for the m3 specs to be updated!

**Comment by patzly** [comment]
That sounds good to me! Thank you for your efforts! :)
