### ISSUE TITLE
Change Radius and colour of Slider Thumb Ripple 

### ISSUE THREAD

**Issue by imandaliya** [material-components/material-components-android#3005]
![slider-ripple](https://user-images.githubusercontent.com/971804/193755354-96e53020-18e2-4603-9cce-64b92f2fc221.png)

Please check slider design where i need some customisation of slider, but i didn't found how to change ripple colour of slider and radius of ripple while sliding is running.

also please add slider actual height instead of fixed height that added via below code,

`<dimen name="mtrl_slider_widget_height">32dp</dimen>
    <dimen name="mtrl_slider_track_top">16dp</dimen>`

Right now i have to override material dimension instead of setting height using attribute property to get proper result.

I know that 48 DP is default size in touch area but in some condition we need to add more or less height of slider instead of default height.

**Comment by imandaliya** [comment]
added MD3 tag

**Comment by imhappi** [comment]
You can change the radius of the ripple with `setHaloRadius`, or with the `haloRadius` attribute, and the color using `setHaloTintList` or the `haloColor` attribute

The slider height is dependent on some other factors, such as track height and thumb radius, etc. You can change the size of these factors instead (eg. `trackHeight` to change the track height and `thumbRadius` to change the thumb radius), which we instead recommend in order to ensure the slider height is tall enough to accommodate those factors. This also ensures a minimum size of 48dp; we probably won't add a way to support a size smaller than 48dp, which is the default touch area as you mentioned. There are workarounds, such as overriding the material dimension as you mentioned.
