### ISSUE TITLE
[TabLayout] Broken tab indicator animations

### ISSUE THREAD

**Issue by pubiqq** [material-components/material-components-android#3047]
[This commit](https://github.com/material-components/material-components-android/commit/00220d0ad636355b7c9c54c6a1aad64550db5897) broke the tab indicator animations, would be good to fix it:

<table>
  <tr>
    <th>Before 00220d0ad636355b7c9c54c6a1aad64550db5897<br>(correct tab indicator behavior)</th>
    <th>After 00220d0ad636355b7c9c54c6a1aad64550db5897<br>(incorrect tab indicator behavior)</th>
   </tr> 
   <tr>
    <td><video src="https://user-images.githubusercontent.com/82187521/197377440-477fcff1-7ade-49f0-a381-eafaaa06bad8.mp4"></td>
    <td><video src="https://user-images.githubusercontent.com/82187521/197377437-b727ff9f-d0b2-434a-b661-acd738db06dc.mp4"></td>
    </tr>
</table>

**Material Library version:** 1.8.0-alpha02

**Comment by patrickfrei** [comment]
@pubiqq 
I've also reported an issues with the TayLayout a while ago (see #2856) and that's why I've to fork the library. This is why I'm interested in the issue that you've reported.

Are your videos not in the wrong sequence? I mean, isn't the one that is marked as "Before" effectively the one "After" the commit? Because to me it seems as if the active tab indicator in the left video is not changing smoothly anymore when you're clicking on the tab (see [doc](https://developer.android.com/reference/com/google/android/material/tabs/TabLayout#INDICATOR_ANIMATION_MODE_ELASTIC)). Is this the issue?

**Comment by pubiqq** [comment]
🤦
Yeah, indeed, the videos are mixed up with each other. Thanks for noticing, I've fixed the description.

I also want to point out that the indicator stops working smoothly not only when switching tabs by clicking on them, but also when swiping pages in `ViewPager`.

**Comment by patrickfrei** [comment]
I'm using `TabLayout` with `ViewPager2` and when I'm swiping the pages, the active tab indicator slightly stutters sometimes.

**Comment by patrickfrei** [comment]
@imhappi 
As I already have to fork the MD library due to bug #2856 and also don't want to set my app live live with the abovementioned bug #3047, I've uncommented the problematic lines in [TabLayout.java](https://github.com/material-components/material-components-android/blob/00220d0ad636355b7c9c54c6a1aad64550db5897/lib/java/com/google/android/material/tabs/TabLayout.java) (lines 1949-1960). That fits my needs so far as a workaround.

```
      if (currentTab != null && currentTab.parent != null) {
        dispatchTabUnselected(currentTab);
        /*if (currentTab.view != null) {
          currentTab.view.update();
        }*/
      }
      if (tab != null) {
        dispatchTabSelected(tab);
        /*if (tab.view != null) {
          tab.view.update();
        }*/
      }
```

**Comment by imhappi** [comment]
Hi @patrickfrei ! Glad you have a workaround, sorry for the inconvenience! Commenting those lines out should be okay/won't do anything unless you've specified a text appearance for selected tabs.
I already have the fixes, just trying to get them reviewed/submitted for the next release

The issue was that the `update()` lines were triggering the onLayout call, which were re-doing all of the animations

**Comment by patrickfrei** [comment]
Hi @imhappi , thank you very much for your efforts!
Would it also be possible that you or someone from your team will have a look into https://github.com/material-components/material-components-android/issues/2856? Because due to that bug, I also have to fork the library.

**Comment by imhappi** [comment]
Hi @patrickfrei, someone will take a look once bandwidth allows. In the meantime, we are open to PRs!

**Comment by patrickfrei** [comment]
Hi @imhappi , I've just created a PR for that issue. See https://github.com/material-components/material-components-android/pull/3077
