### ISSUE TITLE
[TextInputLayout] Broken custom cursor color set at runtime

### ISSUE THREAD

**Issue by pranavpandey** [material-components/material-components-android#3067]
**Description:** After [this commit](https://github.com/material-components/material-components-android/commit/fbd75ec5b00d04e32eeb48617a3babd0f40c35ee), it no longer allows setting a custom `cursor` color via: 

```java
DrawableCompat.setTintList(getEditText().getTextCursorDrawable(), cursorColor);
```

**Expected behavior:** It should allow using the custom cursor color as it was working fine with **1.7.0-alpha02** and I think it should cache the older tint list before applying the error color.

**Source code:** [This code](https://github.com/material-components/material-components-android/blob/fbd75ec5b00d04e32eeb48617a3babd0f40c35ee/lib/java/com/google/android/material/textfield/TextInputLayout.java#L4296) resets the older color if set dynamically at runtime.

**Android API version:** API 29+

**Material Library version:** 1.8.0-alpha02

**Device:** Emulator and Physical

**Comment by drchen** [comment]
Hi Leticia, this looks like a regression. Can we prioritize it so we can get this fixed before we release 1.8?

**Comment by leticiarossi** [comment]
Hi there, the cursor color is [controlled by `?attr/colorControlActivated`](https://github.com/material-components/material-components-android/blob/master/lib/java/com/google/android/material/textfield/res/values/styles.xml#L487) and since there's not a way of getting the current tint from the cursor drawable it's not possible to cache the older tint unfortunately! You'll need to either set `?attr/colorControlActivated` to your custom cursor color, or alternatively set that attr to `null`, which should allow for you to set the color at runtime as you're doing. If for some reason that's not possible, a workaround would be to set the tint whenever you're setting/unsetting the error. We understand that's not ideal but we'll think of ways of improving the text field in the future

**Comment by pranavpandey** [comment]
Thanks for the explanation!

I already have a [custom](https://github.com/pranavpandey/dynamic-support/blob/a7d77c6a61ecf5cb070b2912053b3cf7b274c48d/dynamic-support/src/main/java/com/pranavpandey/android/dynamic/support/widget/DynamicTextInputLayout.java) `TextInputLayout` and I restored the older functionality (even [better](https://github.com/pranavpandey/dynamic-support/blob/a7d77c6a61ecf5cb070b2912053b3cf7b274c48d/dynamic-support/src/main/java/com/pranavpandey/android/dynamic/support/util/DynamicInputUtils.java#L63)) by adding the below code:
```java
public class CustomTextInputLayout extends TextInputLayout {
   
    ...

    @Override
    public void refreshStartIconDrawableState() {
        super.refreshStartIconDrawableState();

	// Update the cursor color on initialization.
        DrawableCompat.setTintList(getEditText().getTextCursorDrawable(),
                isErrorEnabled() ? errorColor : cursorColor);
    }

    @Override
    public void setErrorEnabled(boolean enabled) {
        super.setErrorEnabled(enabled);

        DrawableCompat.setTintList(getEditText().getTextCursorDrawable(),
                isErrorEnabled() ? errorColor : cursorColor);
    }

    ...
}
```
