### ISSUE TITLE
[MaterialDatePicker] Button colors are not showing correctly

### ISSUE THREAD

**Issue by leinardi** [material-components/material-components-android#3090]
**Description:** The button colors are not showing correctly on API < 30. The text and background color are pink, like the color attribute from the theme was not set. But the rest of the UI of the Dialog seems fine.

API 25:
![image](https://user-images.githubusercontent.com/273338/202688959-1a1b6f54-9a1a-44f6-bcfd-5d7037924449.png)

API 29:
![image](https://user-images.githubusercontent.com/273338/202689032-82cbfd9e-3f38-4a52-a885-877b3d78c4c3.png)

API 30:
![image](https://user-images.githubusercontent.com/273338/202689112-67d345a3-9acf-43b3-b494-4a04df6e433f.png)

**Expected behavior:** Screenshots and/or description of expected behavior

**Source code:** The App theme is extending `Theme.Material3.DayNight.NoActionBar` but it's setting only `colorPrimary`, `colorPrimaryDark` and `colorAccent`  (since this is a Compose only app, I'm trying to keep the XML theme attributes to the minimum).

**Minimal sample app repro:** Repro project available here: https://github.com/leinardi/Forlago/tree/date-piker

- Theme defined here: https://github.com/leinardi/Forlago/blob/date-piker/modules/library-ui/src/main/res/values/themes.xml
- Date picker shown here: https://github.com/leinardi/Forlago/blob/date-piker/modules/feature-foo/src/main/kotlin/com/leinardi/forlago/feature/foo/ui/foo/FooScreen.kt#L133
- Date picker defined here: https://github.com/leinardi/Forlago/blob/date-piker/modules/library-ui/src/main/kotlin/com/leinardi/forlago/library/ui/component/DatePicker.kt#L50

**Android API version:** The issue happens on API < 30 (tested on 29 and 25)

**Material Library version:** 1.7.0

**Device:** Emulator (Nexus 5)

**Comment by drchen** [comment]
That's a very interesting issue.....

We probably need to take a deep look into the interoperability between MDC Views components and the Compose framework. 

Thanks for the report!!

**Comment by dsn5ft** [comment]
Hi @leinardi, I don't have any real answers yet but wanted to provide an update and see if you can help us a bit more.

First, I was able to clone your project and reproduce your issue, on an emulator running API level 29 (Q):

![image](https://user-images.githubusercontent.com/1420597/203402674-d11c79e2-79ec-4259-99b9-a43b9430fd88.png)

Then, in order to try to narrow down the issue, I created a [simple project](https://github.com/dsn5ft/basic-m3-compose-with-mdc) which combines Compose and the Material Views-based library:

- [Theme](https://github.com/dsn5ft/basic-m3-compose-with-mdc/blob/main/app/src/main/res/values/themes.xml)
- [Gradle](https://github.com/dsn5ft/basic-m3-compose-with-mdc/blob/main/app/build.gradle#L57-L58)
- [Date Picker](https://github.com/dsn5ft/basic-m3-compose-with-mdc/blob/main/app/src/main/java/com/example/basicm3compose/MainActivity.kt#L28-L31)

Interestingly, when running the above project on the same API level 29 (Q) device, I don't see the issue with the date picker button colors:

![image](https://user-images.githubusercontent.com/1420597/203402715-f7b65a8d-de10-4812-a164-112cfeb87f47.png)

This implies that there's something else in your project configuration that could be contributing to the issue. Since your project is pretty large, I think we'll need some help from you to pare it down and determine the actual minimal conditions required to reproduce the issue (either by using a branch in your repo or by adding to my project until the issue shows up).

Let us know if you have any questions or ideas as to what from your project could be contributing to the issue.

**Comment by leinardi** [comment]
OK, I made [some changes](https://github.com/leinardi/basic-m3-compose-with-mdc) to your simple project and I managed to reproduce the issue... and it's very weird: it happens only if you use `androidx.core:core-splashscreen` **and** set `WindowCompat.setDecorFitsSystemWindows(window, false)`! :exploding_head: 

If you disable the splash screen and set `WindowCompat.setDecorFitsSystemWindows(window, false)` it works fine.
Same if you keep the splash screen but do not set `WindowCompat.setDecorFitsSystemWindows(window, false)`...

**Comment by dsn5ft** [comment]
@leinardi I have a couple of potentially interesting findings:

1. I was able to simplify / minimize your diff a bit to reproduce the issue (https://github.com/dsn5ft/basic-m3-compose-with-mdc/compare/main...splash-screen-setup)
2. I made a separate minimal M3 project without Compose, so basically just combining the MDC and SplashScreen setup, and was also able to reproduce the issue there. So this seems to have nothing to do with Compose.
3. If I move the `WindowCompat.setDecorFitsSystemWindows(window, false)` to be before `super.onCreate(savedInstanceState)`, it seems to get rid of the issue. Although now that I think about it, I'm not sure if `WindowCompat.setDecorFitsSystemWindows(window, false)` has to be after `onCreate` in order to do anything? I can't really tell in my project. Can you try in your projects and see if a) that fixes the issues and b) it's still going edge-to-edge as you expect?

**Comment by leinardi** [comment]
> 3\. If I move the `WindowCompat.setDecorFitsSystemWindows(window, false)` to be before `super.onCreate(savedInstanceState)`, it seems to get rid of the issue. Although now that I think about it, I'm not sure if `WindowCompat.setDecorFitsSystemWindows(window, false)` has to be after `onCreate` in order to do anything? I can't really tell in my project. Can you try in your projects and see if a) that fixes the issues and b) it's still going edge-to-edge as you expect?

Hey good catch! Moving `WindowCompat.setDecorFitsSystemWindows(window, false)` before the `onCreate()` seems to fix it! And I don't see any other side effects: the app is still edge-to-edge :partying_face:

**Comment by leinardi** [comment]
Oh damn, I completely missed that requirement 😅 Now I've added a comment to avoid the same mistake in the future.
Thank you for digging deeper and providing the proper solution!
