### ISSUE TITLE
[SearchBar] Only for M3?

### ISSUE THREAD

**Issue by NLLAPPS** [material-components/material-components-android#3104]
Hi, it looks like SearchBar only available on M3. Is there any way using it with previous versions?

**Comment by drchen** [comment]
Hi, unfortunately we don't really have an M2 design for search bar since it's a new component. 

We strongly suggest to migrate to M3 because it provides you more up-to-date designs and also better guarantees like accessibility support.

If you really need to stick on M2, you can create your own search bar style and override `?attr/materialSearchBarStyle` and `?attr/materialSearchViewStyle` in your themes.
