### ISSUE TITLE
[TabLayout] Junk scroll

### ISSUE THREAD

**Issue by pubiqq** [material-components/material-components-android#3138]
When selecting a tab in a scrollable TabLayout with linked ViewPager, unwanted scrolling occurs.

<table>
  <tr>
    <th>Actual result</th>
    <th>Expected result</th>
   </tr> 
   <tr>
    <td><video src="https://user-images.githubusercontent.com/82187521/207021948-e288ee0f-2d54-45c5-8b89-b482b59c8af9.mp4" width="270px"></td>
    <td><video src="https://user-images.githubusercontent.com/82187521/207021910-3d93f901-4b43-49ff-8083-f821e923ec5d.mp4" width="270px"></td>
  </tr>
</table>

**Material Library version:** 1.8.0-beta01

**Comment by imhappi** [comment]
Oh wow this seems like a pretty bad visual bug

Unfortunately I don't think we'll fix it in 1.8 since it's already in beta, and the issue doesn't seem to be a 1.8 regression. Did some investigation, and it's happening because when you select a tab, `selectTab` is called which sets the current viewpager item. Setting the viewpager item causes `onPageScrolled` to be called multiple times to smooth scroll from the current viewpager item to the new one. `onPageScrolled` calls `setScrollPosition` with the given position/position offset, which starts at the current viewpager item position which is why it always goes back to scroll from the currently selected tab

There are a couple of potential fixes which I will explore for the next alpha release

**Comment by pubiqq** [comment]
Indeed, this problem is pretty nasty and present in almost all applications with scrollable tabs (including Google apps, like [Files](https://play.google.com/store/apps/details?id=com.google.android.apps.nbu.files), [Tasks](https://play.google.com/store/apps/details?id=com.google.android.apps.tasks), etc.), so I really hope the issue will be resolved in 1.9.0.

**Comment by pubiqq** [comment]
Indeed, this problem is pretty nasty and present in almost all applications with scrollable tabs (including Google apps, like [Files](https://play.google.com/store/apps/details?id=com.google.android.apps.nbu.files), [Tasks](https://play.google.com/store/apps/details?id=com.google.android.apps.tasks), etc.), so I really hope the issue will be resolved in 1.9.0.
