### ISSUE TITLE
Why the default text sizes look very small in many components?

### ISSUE THREAD

**Issue by tahasami2500** [material-components/material-components-android#3140]
**The text sizes look normal if I don't select a specific style for the components**

![Untitled](https://user-images.githubusercontent.com/24863605/207518772-37ece472-b453-4af0-ba26-369937aed9c6.png)

**But the result will look like this if I select the styles for the components**

![Untitled1](https://user-images.githubusercontent.com/24863605/207518898-23170dce-1442-483f-9036-40a7470b768d.png)

**Here is the style of `Widget.App.Toolbar.Surface`**

```
<style name="Widget.App.Toolbar.Surface" parent="Widget.Material3.Toolbar.Surface">
    <item name="materialThemeOverlay">@style/ThemeOverlay.App.Toolbar.Surface</item>
</style>

<style name="ThemeOverlay.App.Toolbar.Surface" parent="ThemeOverlay.Material3.Toolbar.Surface">
    <item name="elevationOverlayEnabled">false</item>
</style>
```

The version that I use is `com.google.android.material:material:1.7.0`

This problem happened newly, What is the reason?

Did I miss something?

**Comment by imhappi** [comment]
The reason is because the Material3 Button style sets its text appearance to be `?attr/textAppearanceLabelLarge`, which is defined in the material 3 theme. I believe the tiny text is due to `textAppearanceLabelLarge` being undefined.

You should use the material 3 theme in your app's theme instead, and only specify styles if you want to override a value
