### ISSUE TITLE
[SideSheet] Modal SideSheet's SideSheetCallback's onSlide() is not called

### ISSUE THREAD

**Issue by manabu-nakamura** [material-components/material-components-android#3167]
**Description:** Modal SideSheet's SideSheetCallback's onSlide() is not called (modal BottomSheet's BottomSheetCallback's onSlide() is not called, too). After the modal SideSheet is dragged once, onSlide() will be called.
![Screenshot_20230106_093622](https://user-images.githubusercontent.com/71050561/210930259-e417637a-dc71-4292-a5fc-00455b6f232d.png)

**Expected behavior:** onSlide() is called.

**Source code:** https://github.com/material-components/material-components-android/tree/master/catalog/java/io/material/catalog/sidesheet/SideSheetMainDemoFragment.java#L278-L282
https://github.com/material-components/material-components-android/blob/master/catalog/java/io/material/catalog/sidesheet/SideSheetMainDemoFragment.java#L114-L119

**Minimal sample app repro:** Catalog app

**Android API version:** 33

**Material Library version:** 1.8.0-beta01

**Device:** Emulator 31.3.14

**Comment by afohrman** [comment]
Thanks for reporting! This is actually a catalog bug, not a modal side sheet bug. What's happening is that the slide offset text view (and the state text view, if you look carefully) are not updated until the first drag, because up until that point, only the dialog window animations have run, and the values are only initialized in the callback. I have a internal change out to fix this issue in the catalog.
