### ISSUE TITLE
[BottomSheet] Fullscreen BottomSheet can not be edge-to-edge

### ISSUE THREAD

**Issue by manabu-nakamura** [material-components/material-components-android#3173]
**Description:** The **fullscreen** BottomSheet **is not drawn** behind the system navigation bar.
![Screenshot_20230110_095837](https://user-images.githubusercontent.com/71050561/211439003-a54a69eb-f7cd-4b54-9378-e81cbb9a7655.png)
The **non-fullscreen** BottomSheet **is drawn** behind the system navigation bar.
![Screenshot_20230110_102050](https://user-images.githubusercontent.com/71050561/211440585-0c6fa913-d35f-4af8-9a87-29f4b9e76381.png)

**Expected behavior:** The **fullscreen** BottomSheet **is drawn** behind the system navigation bar.
![Screenshot_20230110_100027](https://user-images.githubusercontent.com/71050561/211439189-4f6c9264-bde6-4045-a0d1-525ccda07264.png)
Setting paddingBottomSystemWindowInsets to false has a side effect: the bottom sheet cannot be scrolled to the bottom.
https://github.com/material-components/material-components-android/blob/master/lib/java/com/google/android/material/bottomsheet/res/values/styles.xml#L72
![Screenshot_20230110_111747](https://user-images.githubusercontent.com/71050561/211449799-ee824f8d-103e-49ed-8845-9c708241892f.png)

**Source code:** https://github.com/material-components/material-components-android/tree/master/catalog/java/io/material/catalog/bottomsheet/BottomSheetScrollableContentDemoFragment.java#L52-L54

**Minimal sample app repro:** Catalog app

**Android API version:** 33

**Material Library version:** 1.8.0-beta01

**Device:** Emulator 31.3.14

**Comment by manabu-nakamura** [comment]
paddingBottomSystemWindowInsets is true:
![Screenshot_20230110_132125](https://user-images.githubusercontent.com/71050561/211461892-62141649-fbd2-4a79-b92a-bd361c29ea28.png)
paddingBottomSystemWindowInsets is false:
![Screenshot_20230110_132105](https://user-images.githubusercontent.com/71050561/211461930-8db539a8-9e20-4017-a853-691020fbb7f1.png)

**Comment by drchen** [comment]
This is working as intended I think. 

Let's forget about the scrollable content for a moment - just imagine a plain bottom sheet. Under edge-to-edge mode, when the bottom sheet is not fully expanded, should we adding paddings to avoid the content being drawn behind the navigation bar or not?

Apparently our designers' answer is no. This is also consistent with most of the scrolling behavior under edge-to-edge - content is drawn behind the transparent navigation bar to indicate that they it be scrolled.

With that guideline in mind, paddings account for the navigation inset will only be added to the very bottom of the content - in our case, the bottom of the whole bottom sheet content - and that's why when the bottom sheet is expanded, i.e., when its content is fully shown, you will see the bottom paddings showing to avoid content being overlapped the navigation bar, because at the moment the bottom sheet is no longer scrollable upward. 

Ok so now let's move back to the case of a bottom sheet with a nested scroallable content - here we should follow the same guideline, i.e., when the bottom sheet is not expanded, content will be overlapped with the navigation bar, which is the case of the current implementation. However the confusing part is even when the bottom sheet is expanded, the nested scrollable content is still upward scrollable - this creates the confusion why content is not drawn behind the navigation bar in this case. 

Unfortunately we have no control over the nested scrollable content. Therefore to implement the behavior correctly we need to add paddings to the nested scrollable content instead. Let me try to fix that in catalog to be an example.

**Comment by manabu-nakamura** [comment]
Thank you, @drchen. Please remove the bottom padding from the bottom sheet of the bottom app bar, too (https://github.com/material-components/material-components-android/pull/3232). But, it is troublesome.
https://github.com/material-components/material-components-android/issues/3173#issuecomment-1376719392
