### ISSUE TITLE
[Text fields] delay-parameter for the Method afterTextChanged(...) to reduce search queries when typed fast

### ISSUE THREAD

**Issue by Sayum24** [material-components/material-components-android#3188]
**Is your feature request related to a problem? Please describe.**
In a search-bar for every change in the text-field the method `afterTextChanged` gets called.
If a user types really fast every change is a search-query which is sent to a server.

**Describe the solution you'd like**
To reduce unnecessary queries to an api / server a built in timer which only triggers a function when a set delay/ break between a change has passed.

**Describe alternatives you've considered**

**Additional context**
Stackoverflow Questions for this problem/ feature
- [How can I do something 0.5 seconds after text changed in my EditText control?](https://stackoverflow.com/questions/12142021/how-can-i-do-something-0-5-seconds-after-text-changed-in-my-edittext-control)
- [How to avoid multiple triggers on EditText while user is typing?](https://stackoverflow.com/questions/10217051/how-to-avoid-multiple-triggers-on-edittext-while-user-is-typing)

**Comment by dsn5ft** [comment]
Hi, this sounds like more of an application level problem, and not specific to the Material library since the Text Field component is built on top of the standard EditText.

You should be able to forward the results from `afterTextChanged` to another library like RxJava/RxAndroid, and then debounce or throttle those text change events such that you only get notified every 0.5 seconds. Then you can do your api call within the Rx subscription so that it's more limited.

https://gist.github.com/FrantisekGazo/d1a62fcddd0c97453ee6d57efef17916

https://reactivex.io/documentation/operators/debounce.html
