### ISSUE TITLE
[MaterialToolbar] MaterialToolbar Elevation not showing on Android 11, Why?

### ISSUE THREAD

**Issue by tahasami2500** [material-components/material-components-android#3219]
I have a MaterialToolbar with an elevation of 4dp, but it is showing on Android 7 but not on Android 11. Is there something I missed or is this a bug from the library? If so, what is the workaround?

```
<?xml version="1.0" encoding="utf-8"?>
<LinearLayout
    xmlns:android="http://schemas.android.com/apk/res/android"
    xmlns:app="http://schemas.android.com/apk/res-auto"
    xmlns:tools="http://schemas.android.com/tools"
    android:layout_width="match_parent"
    android:layout_height="match_parent"
    android:orientation="vertical"
    tools:context=".activities.MainActivity">

    <com.google.android.material.appbar.MaterialToolbar
        android:id="@+id/activityMain_materialToolbar_topBar"
        style="@style/Widget.App.Toolbar.Surface"
        android:layout_width="match_parent"
        android:layout_height="wrap_content"
        android:elevation="4dp" />

</LinearLayout>
```

```
<style name="Widget.App.Toolbar.Surface" parent="Widget.Material3.Toolbar.Surface">
    <item name="materialThemeOverlay">@style/ThemeOverlay.App.Toolbar.Surface</item>
</style>

<style name="ThemeOverlay.App.Toolbar.Surface" parent="ThemeOverlay.Material3.Toolbar.Surface">
    <item name="elevationOverlayEnabled">false</item>
</style>
```

**Android 7**

![image](https://user-images.githubusercontent.com/24863605/217162123-526647b6-e297-491e-950a-00c6ab05fe69.png)

**Android 11**

![image](https://user-images.githubusercontent.com/24863605/217162157-cef11ba6-5996-4298-80d1-c7b939127d14.png)

**Comment by dsn5ft** [comment]
Hi @tahasami2500, thanks for reaching out.

This is actually intentional as part of the new M3 spec for Top App Bars. The shadow is removed and instead there is a color fill on scroll, based on the elevation value.

https://m3.material.io/components/top-app-bar/overview

However the only way we were able to "keep the elevation" and remove the shadow was to set the shadow colors to be transparent using some newer APIs (https://github.com/material-components/material-components-android/blob/0dd220a6e9f7255c77219b2fe1345f56cf209e8b/lib/java/com/google/android/material/appbar/res/values/styles.xml#L206-L208). That's why you only see the shadow disappear on Android 11+.

**Comment by tahasami2500** [comment]
Your solution is not working with me, I tried to add two items inside `Widget.App.Toolbar.Surface`

**Comment by tahasami2500** [comment]
Thank you for your reply. Why was the elevation feature removed in Android 11 and above? The app looks unattractive, specifically with the RecyclerView.

**Comment by dsn5ft** [comment]
Part of the idea with Material 3 is to reduce the number of unnecessary "layers" on the screen, as well as the visual clutter of shadows (only keeping them for UI elements that are truly floating above content like a FAB). There's more information in the guidelines here: https://m3.material.io/styles/elevation/overview.

**Comment by ShkurtiA** [comment]
looking forward to the time when a new manager will change this design
