### ISSUE TITLE
Why is BaseSlider not public ? 

### ISSUE THREAD

**Issue by renetik** [material-components/material-components-android#3227]
Is there some good reason for this ? I just want to call some base function while using once RangleSlicer once Slider and cannot use it as base class to refeer to. Isnt this unwanted limitaition ? 

My workaround:

`
interface CSMaterialSlider {
    fun onTouchEvent(event: MotionEvent): Boolean
}

class CSRangeSlider @JvmOverloads
constructor(context: Context, attrs: AttributeSet? = null, defStyleAttr: Int = 0) :
    RangeSlider(context, attrs, defStyleAttr), CSMaterialSlider

class CSSlider @JvmOverloads
constructor(context: Context, attrs: AttributeSet? = null, defStyleAttr: Int = 0) :
    Slider(context, attrs, defStyleAttr), CSMaterialSlider
`

**Comment by dsn5ft** [comment]
Hi @renetik, `BaseSlider` is not public at the moment because of the complexity of the API. We'd also have to expose `BaseOnChangeListener<>` and `BaseOnSliderTouchListener<>`, and it would be difficult for us to commit to keeping all of those base APIs stable, in case we need to refactor some of the internals of `Slider` and `RangeSlider`.
