### ISSUE TITLE
[Search] SearchBar should not have a shadow

### ISSUE THREAD

**Issue by pubiqq** [material-components/material-components-android#3254]
<table>
  <tr>
    <th>SearchMainDemoActivity<br>(API 28 Emulator)</th>
    <th>SearchMainDemoActivity<br>(API 29 Emulator)</th>
   </tr> 
   <tr>
    <td><img src="https://user-images.githubusercontent.com/82187521/222997748-94eccf53-0db4-463a-91f1-18ea62040086.png" width="324px"></td>
    <td><img src="https://user-images.githubusercontent.com/82187521/220222571-b8c58f7d-e541-400a-b9a4-86e32a931dad.png" width="324px"></td>
    </tr>
</table>

**Material Library version:** 1.8.0

**Comment by raajkumars** [comment]
Could not reproduce this issue using the latest version of the library. If you still think that the issue exists, please feel free to reopen this issue and attach a working sample app that can be used to reproduce the issue.

**Comment by pubiqq** [comment]
The issue is still present. 
No extra actions are needed, just open SearchMainDemoActivity in Material Catalog App.

**Material Library version:** 1.10.0-alpha01

**Checked on:**
- API 28 Emulator
- API 27 Emulator
- API 25 Emulator
- API 23 Emulator
- API 21 Emulator

**Comment by raajkumars** [comment]
Thanks for your quick response. I believe we are still missing something here, because I did test the search demo in the Material Catalog app on API 28 emulator and API 32 emulator and I do not see the issue that you mentioned. Here are my screenshots. One difference is that I am building the Material Android library from the master.

![Screenshot_search_demo_on_api_32](https://user-images.githubusercontent.com/5881474/229845702-a0a8c48a-5366-49ce-8633-b6924972e14b.png)
![Screenshot_search_demo_on_api_28](https://user-images.githubusercontent.com/5881474/229845707-74956272-2773-4c65-a990-fe76f80eaac5.png)

**Comment by pubiqq** [comment]
It's very weird... Could you please check it on an emulator with an older API (mb API 27 or 23)?

**Comment by pubiqq** [comment]
bump

**Comment by afohrman** [comment]
I was able to reproduce this on API level 27, although interestingly not on 28.

API 27: ![search_27_shadow](https://github.com/material-components/material-components-android/assets/13263374/925da4c2-8558-455f-ac8f-f54c6d90f1b0)
API 28: ![search_bar_28_no_shadow](https://github.com/material-components/material-components-android/assets/13263374/f3ccb3e4-5fb8-4144-aceb-8dc8d9ccfd2e)

@raajkumars, could you please take another look at this?

**Comment by dsn5ft** [comment]
This is actually intentional and known:

https://github.com/material-components/material-components-android/blob/47c307d889a89988b01ec573dd39ed74021c0143/lib/java/com/google/android/material/search/res/values/styles.xml#L34-L36

As part of the Material 3 spec, we had to keep the elevation for the elevation overlay tint color, but remove the shadows. Unfortunately the only API we have for this is API 28+, so on newer devices we fully meet the Material 3 spec and on older devices the shadow is still present.

**Comment by dsn5ft** [comment]
This is also consistent with how other components such as Bottom Nav, Bottom App Bar, and Top App Bar work:

https://github.com/search?q=repo%3Amaterial-components%2Fmaterial-components-android%20outlineAmbientShadowColor&type=code

**Comment by pubiqq** [comment]
Can't you just remove the elevation and use `colorSurfaceContainerHigh` according to your [updated way of achieving tinted surfaces](https://material.io/blog/tone-based-surface-color-m3)?

The current version looks weird, it doesn't meet the specification and differs from `SearchBar` in other applications (Gmail, Google, Messages, Drive, and so on). The fact that "it's consistent with BottomNav and AppBars" seems to me a weak excuse to be honest.

**Comment by dsn5ft** [comment]
It's not an excuse, I just wanted to clarify that this issue is not specific to SearchBar.

And yes we are working on update all M3 components to use the new surface roles instead of elevation overlays. There's a possibility that at that point we can remove elevation, but that could cause z-order issues / breakages for anyone relying on elevation for that. We'll definitely consider it when we get there though.

**Comment by bubbleguuum** [comment]
Any news on this ? 

Although there should be no shadow on <= API 28 (I only see it on API <= 27), it can be trivially removed 
by setting  app:elevation="0dp" on the `SearchBar`. Also works on other components such as `NavigationRailView`.
