### ISSUE TITLE
Material text input layout Keyboard autohiding after input when input type is number

### ISSUE THREAD

**Issue by bakshi-rohan** [material-components/material-components-android#3390]
When i enter any number keyboard hides automatically and i've to re-open it when input type is set to number

**Comment by harshit21saini** [comment]
bro..
use static input field without material library and edit that accordingly.
or 

It's likely that you are experiencing this issue on a mobile device. When the input type is set to "number" on a mobile device, the default behavior is to display a numeric keypad instead of a standard keyboard. When you enter a number, the keyboard will automatically hide to give you a better view of the content.

If you want to keep the keyboard open after entering a number, you can try changing the input type to "text" instead of "number". This will display the standard keyboard, and it should remain open after you enter a number.

Alternatively, you can try using JavaScript to override the default behavior of the number input. You can do this by adding an event listener to the input field that prevents the keyboard from hiding when the user enters a number. Here's an example:

var input = document.querySelector('input[type="number"]');
input.addEventListener('input', function() {
    // Prevent keyboard from hiding
    input.focus();
});

**Comment by imhappi** [comment]
I'm unable to reproduce this issue
