### ISSUE TITLE
[DialogWhenLarge] Dialogue Window on large devices is not styled according to Material Dialog specification

### ISSUE THREAD

**Issue by mtotschnig** [material-components/material-components-android#3398]
When defining a theme based on Theme.Material3.DayNight.DialogWhenLarge, I would expect the activity's window to be configured according to the specification for Material dialogs (https://m3.material.io/components/dialogs/overview).

In my app I am using both activities with this theme, and dialogues created with MaterialAlertDialogBuilder, which leads to an inconsistent design, since only the latter get the material styling.

**Comment by imhappi** [comment]
Hi @mtotschnig ! I'm not sure if I understand your issue; are you using both regular dialogs and material dialogs? Regular alert dialogs will use a different material styling than material dialogs.

 If you would like the Material dialog styling, please make sure to use MaterialAlertDialogBuilder for all of your dialogs.

Closing this, but feel free to comment if I misunderstood and I will re-open the issue

**Comment by imhappi** [comment]
Ah sorry I think I misunderstood. I'm assuming that you mean the dialog comes up when the screen is large is not themed like a material alert dialog. I suspect that is because an alert dialog is used, and alert dialogs use different material styling than MaterialAlertDialogs, because we are able to customize the MaterialAlertDialog.

Unfortunately I don't think that there's anything we can do about this. DialogWhenLarge is not in the m3 specs

**Comment by mtotschnig** [comment]
Hello @imhappi 
I created a repository and a video to illustrate the issue:
https://github.com/material-components/material-components-android/issues/3398
[3398.webm](https://github.com/material-components/material-components-android/assets/1485456/2a6dbe3d-900a-4ffe-b8c7-0bd7794bf773)
I don't think an activity themed with DialogWhenLarge would use an Alert Dialog. It is just an activity styled as a dialog via theme attributes.
The m3 specs describe how dialogues should be rendered, not how they are implemented. On a large device (e.g. tablet), a DialogWhenLarge themed activity appears as a dialogue, so should adhere to the M3 spec in the context of an M3 application.

**Comment by mtotschnig** [comment]
By the way: Since a M3 variant of DialogWhenLarge is provided, I would expect it to adhere to the specs. Accidentally, it is currently broken: #3400 .

**Comment by mtotschnig** [comment]
I changed the title to reflect my finding that the problem is not specific to the DialogWhenLarge theme but to the Theme.Material3.*.Dialog themes in general. There appearance is not in line with the Material3 specification.

**Comment by imhappi** [comment]
Hi @mtotschnig unfortunately we cannot apply MaterialAlertDialog styling on the DialogWhenLarge dialog as it's not a MaterialAlertDialog. From glancing at the AppCompat source code, it looks like DialogWhenLarge only sets some fixed window width/height measurements to make the window a 'dialog' so we don't really have any options there on styling it.

What do you mean the appearance for Theme.Material3.*.Dialog is not in line with the Material3 specification? It looks like they are correct:
```
    <item name="alertDialogTheme">@style/ThemeOverlay.Material3.Dialog.Alert</item>
    <item name="materialAlertDialogTheme">@style/ThemeOverlay.Material3.MaterialAlertDialog</item>
```
As I mentioned previously, alert dialogs use different material styling than MaterialAlertDialogs, because we are able to customize the MaterialAlertDialog. The m3 specifications refer to the MaterialAlertDialog. Is there a particular part of the MaterialAlertDialog that you feel doesn't match the specs?

**Comment by mtotschnig** [comment]
Hello @imhappi, DialogWhenLarge is a theme that, as its name promises, is supposed to achieve a dialog styled window only on large devices. (As mentioned, this behavior is currently broken for M3). What I mean, is that the problem is not in the DialogWhenLarge theme, it is in the Dialog theme that DialogWhenLarge delegates to. I have changed my example project to stress this point, by not using DialogWhenLarge but Dialog theme: https://github.com/mtotschnig/MaterialComponentsAndroidIssue3398/commit/114d5f9c2cb1c4df7f3b1708e301d2a7ed110957
I understand that the magic achiveving the Material3 dialog style is currently only available for Dialogs created with MaterialAlertDialogBuilder, and that it might be harder to achieve for dialog styled activities. It might even not be possible to achieve by this library without changes in the Android system. But as a developer/user applying one of the Theme.Material3.*.Dialog themes to an activity, I would expect the result consistent with the M3 specification.
