### ISSUE TITLE
Project sync failing on master branch

### ISSUE THREAD

**Issue by amitav13** [material-components/material-components-android#342]
Hi, 
Just downloaded a fresh copy of this project and am getting the following error when trying to do a gradle sync:
```
FAILURE: Build failed with an exception.

* Where:
Build file '/Users/amitavk/androidStudioProjects/material-components-android/build.gradle' line: 113

* What went wrong:
A problem occurred evaluating project ':lib'.
> No mapping exists for name: viewpager2.
```
Android Studio config:
Android Studio 3.4
Build #AI-183.5429.30.34.5452501, built on April 10, 2019
JRE: 1.8.0_152-release-1343-b01 x86_64
JVM: OpenJDK 64-Bit Server VM by JetBrains s.r.o
macOS 10.14.3

**Comment by ethan627hsu** [comment]
@amitav13, can you give me needed information by providing the gradle command you used to import the material components library?
For example:
`implementation 'com.google.android.material:material:1.1.0-alpha04'`
`compile 'com.google.android.material:material:1.1.0-alpha04'`

Or, if you are wanting to contribute to this library and downloaded the repository it would be nice to specify it.

**Comment by ethan627hsu** [comment]
@amitav13, additionally, can you download the latest version of the repository? The issue you are facing has been accounted for in the latest master branch.

Here is the code for reference:

File location: `material-components-android/build.gradle`

> function is ran with name=viewpager2

def compatibility(name) {
  switch (name) {
    case "annotation":
      return "androidx.annotation:annotation:${androidXVersions.annotation}"
    case "appcompat":
      return "androidx.appcompat:appcompat:${androidXVersions.appCompat}"
    case "cardview":
      return "androidx.cardview:cardview:${androidXVersions.cardView}"
    case "coordinatorlayout":
      return "androidx.coordinatorlayout:coordinatorlayout:${androidXVersions.coordinatorlayout}"
    case "core":
      return "androidx.core:core:${androidXVersions.core}"
    case "core_ui":
      return "androidx.legacy:legacy-support-core-ui:${androidXVersions.legacySupportCoreUi}"
    case "core_utils":
      return "androidx.legacy:legacy-support-core-utils:${androidXVersions.legacySupportCoreUtils}"
    case "fragment":
      return "androidx.fragment:fragment:${androidXVersions.fragment}"
    case "recyclerview":
      return "androidx.recyclerview:recyclerview:${androidXVersions.recyclerView}"
    case "transition":
      return "androidx.transition:transition:${androidXVersions.transition}"
    case "vectordrawable":
      return "androidx.vectordrawable:vectordrawable:${androidXVersions.vectorDrawable}"
    case "recyclerViewSelection":
      return "androidx.recyclerview:recyclerview-selection:${androidXVersions.recyclerViewSelection}"
> switch is supposed to run the code for this case, but it has not been added in your old version    

    case "viewpager2":
      return "androidx.viewpager2:viewpager2:${androidXVersions.viewpager2}"
> instead runs default since the case is not included in your version

    default:
      throw new IllegalArgumentException("No mapping exists for name: $name.")
  }
}

After updating your version, you should see this code in your root build.gradle file, if you have this content included and the error still remains, then you can respond to the thread to further the conversation. Otherwise, wish you the best of luck 😉

**Comment by amitav13** [comment]
Hi @ethan627hsu, thanks for the detailed reply. 

> Or, if you are wanting to contribute to this library and downloaded the repository it would be nice to specify it.

I wanted to build the apk from the `catalog` module to test out the new components released. It would be great if we could have it as part of the releases, but that's another issue.

> After updating your version, you should see this code in your root build.gradle file

I did already have this, did another pull just to be sure. I'm on commit `e1019ee4`. Not sure why it isn't picking it up in the switch case. I've done project cleans, even re-downloaded a fresh copy of the repo. I've also tried it from the command line with `./gradlew clean catalog:assembleDebug`, and with Android Studio Canary:

Android Studio 3.5 Canary 13
Build #AI-191.6183.87.35.5487692, built on April 20, 2019
JRE: 1.8.0_202-release-1483-b01 x86_64
JVM: OpenJDK 64-Bit Server VM by JetBrains s.r.o
macOS 10.14.3

Still getting the same original error :(

**Comment by ethan627hsu** [comment]
@amitav13 Thanks for the context to help me out.

Similar to other issues I have involved myself in, your issue seems to be system-specific as I cannot replicate it when running an APK build on my system. A basic simplification of the issue (accounting that your system is setup properly) is that an old version of the `compatibility(name)` function is being ran, whether it is stored in a cache, studio IDE or in the final code you are running...

Although I cannot aid you with any information about the repository that may help you at this time, I will still provide assistance if you give me more contextual information or instructional info. I hope I provided a worthy perspective on your issue, and appropriate context for you to solve your issue.

Good luck! 🍀
