### ISSUE TITLE
[MaterialDatePicker] Unable to apply rounded corners to dialog

### ISSUE THREAD

**Issue by dkiktenko** [material-components/material-components-android#3437]
**Description:** With the source code provided below, dialog shape does not change from default

**Expected behavior:** Corners of dialog are more rounded out

**Source code:** 

In a module's `styles.xml` file, I have the following defined:

```
    <style name="SomeFragmentDatePicker" parent="ThemeOverlay.Material3.MaterialCalendar">
        <item name="materialCalendarStyle">@style/Widget.MaterialComponents.MaterialCalendar</item>
        <item name="materialCalendarFullscreenTheme">@style/ThemeOverlay.MaterialComponents.MaterialCalendar.Fullscreen</item>
        <item name="materialCalendarTheme">@style/ThemeOverlay.MaterialComponents.MaterialCalendar</item>
        <item name="shapeAppearanceCornerExtraLarge">@style/SomeFragmentDatePicker.Shape</item>
    </style>


    <style name="SomeFragmentDatePicker.Shape" parent="@style/ShapeAppearance.Material3.Corner.ExtraLarge">
        <item name="cornerSize">16dp</item>
        <item name="cornerFamily">rounded</item>
    </style>
```

In my fragment:
```
if (datePickerDialog == null) {
      datePickerDialog =
          MaterialDatePicker.Builder.datePicker()
              .setTheme(R.style.SomeFragmentDatePicker)
              .setSelection(MaterialDatePicker.todayInUtcMilliseconds())
              .build();
      datePickerDialog.addOnPositiveButtonClickListener(
          selection -> {
            // TODO
          });
    }
    datePickerDialog.show(getParentFragmentManager(), "SomeFragment");
```

NOTE: Using `shapeAppearanceCornerExtraLarge` as per guidance [here](https://github.com/material-components/material-components-android/issues/2736).

**Android API version:** Android API 28 and 33

**Material Library version:** Material Android Library version 1.8.0

**Device:** Pixel 4, Pixel 6

**Comment by afohrman** [comment]
The default M3 datepicker shape appearance is set to reference `?attr/shapeAppearanceCornerExtraLarge` in [`Widget.Material3.MaterialCalendar`](https://github.com/material-components/material-components-android/blob/7d6a977d50b798e991d31d5223a4f3efcdfd6a24/lib/java/com/google/android/material/datepicker/res/values/styles.xml#L217), but you're overriding `materialCalendarStyle` to `Widget.MaterialComponents.MaterialCalendar`, rather than using `Widget.Material3.MaterialCalendar` . This would cause your override of `?attr/shapeAppearanceCornerExtraLarge` to be ignored, since [`Widget.MaterialComponents.MaterialCalendar` sets the shapeAppearance to point to `?attr/shapeAppearanceMediumComponent`](https://github.com/material-components/material-components-android/blob/7d6a977d50b798e991d31d5223a4f3efcdfd6a24/lib/java/com/google/android/material/datepicker/res/values/styles.xml#L35), rather than the M3 style, which [points to `?attr/shapeAppearanceCornerExtraLarge`](https://github.com/material-components/material-components-android/blob/7d6a977d50b798e991d31d5223a4f3efcdfd6a24/lib/java/com/google/android/material/datepicker/res/values/tokens.xml#L25).

Why are you overriding all of the date picker styles to point to the MaterialComponents styles? My first recommendation would be to remove those overrides to avoid bugs like this one, and you'd get the proper styling for free. If that's not possible for some reason, I'd recommend at least overriding the `Widget.MaterialComponents` styles, set `shapeAppearance` to the desired value, and then update `SomeFragmentDatePicker` to point to those new styles. Note that I would **not** recommend overriding the value that `?attr/shapeAppearanceMediumComponent` points to, like in your example above. Structuring shape appearance overrides like that is risky, because you're depending on the component style never updating which shape theme attributes it references. The default component shape appearance can theoretically change to reference some other shape appearance theme attribute, in which case your override of that specific attribute would be ignored.

One more thing: why are you setting `ShapeAppearance.Material3.Corner.ExtraLarge` to 16dp? It's supposed to be 28dp by default. If you're trying to change your app-wide `ShapeAppearance.Material3.Corner.ExtraLarge` corners, you should override that at the theme level. If you're trying to simply change the date picker corners to a hardcoded 16dp, I'd recommend setting that directly in the style (or again, just using the default M3 styles and getting this all for free).
