### ISSUE TITLE
Publish catalog module apk to Play Store or release artifacts

### ISSUE THREAD

**Issue by amitav13** [material-components/material-components-android#344]
Hi,
I like to frequently see the updates that have been made to this project via the `catalog` apk, and also share this with designers that I work with. 

It would be immensely helpful if we could have built APKs published to the Play Store, or at least included in the release artefacts. 

Also worth mentioning here is because I'm facing build issues, #342. I don't know if this is affecting others in my position, but building the APK myself isn't currently an option.

**Comment by ethan627hsu** [comment]
@amitav13, thanks for narrowing down your issue, so that I can provide you with assistance!

Currently, the repository holds a regularly-updated version of catalog app, that has not been compiled. The philosophy behind this choice is that the repository is constantly changing and evolving with new features to add, therefore recompiling a new APK every single change would be very verbose. I understand that you are currently facing build issues, and that others would just build like normal.

To solve your temporary issue of needing an APK of the catalog app, I have posted an APK of the most recent catalog app (since May 5) on Google Drive. Here is the public access link (or click [here](https://drive.google.com/file/d/14Aiawkbho0c5_zdQpIENS0lLXT2DPTjf/view?usp=sharing])):

`https://drive.google.com/file/d/14Aiawkbho0c5_zdQpIENS0lLXT2DPTjf/view?usp=sharing`

In other terms, your idea sounds wonderful! I certainly think that a public record to show off the work done on this repository would be fabulous ✨. Though it is up to the _actual_ Material Components Team to review your idea... @cketcham, what do you think about such idea?

**Comment by amitav13** [comment]
> The philosophy behind this choice is that the repository is constantly changing and evolving with new features to add, therefore recompiling a new APK every single change would be very verbose.

Agreed, I was thinking more along the lines of when we have releases of the library itself.

> https://drive.google.com/file/d/14Aiawkbho0c5_zdQpIENS0lLXT2DPTjf/view?usp=sharing

Thanks for this! Helps solve my issue for now, though a Play store release of this app would be great. A quick playstore search does give some apps with a material design 'catalog', but they don't seem to be utilising the new material components here.

**Comment by ethan627hsu** [comment]
No worries @amitav13, it would be interesting to see your idea evolve into a Play Store release...

**Comment by dsn5ft** [comment]
@amitav13 good idea! We will incorporate this into our release process.

**Comment by ethan627hsu** [comment]
Great @dsn5ft! If you need any help updating the catalog application with more components or specification, I would be willing to work on that 🔨
