### ISSUE TITLE
[Carousel] Item doesn't expand fully in a carousel with center-aligned items with only 2 items

### ISSUE THREAD

**Issue by pubiqq** [material-components/material-components-android#3589]
https://github.com/material-components/material-components-android/assets/82187521/ac80d14b-5198-4262-94f4-efb7ecd19acf

**Material Library version:** 1.11.0-alpha02
**Device:** Pixel 4a (5G)

**Comment by imhappi** [comment]
This issue is occurring because the range across 2 items is not large enough to fill the transition from the starting state (start-aligned) to the ending state (end-aligned)

Instead of trying to force the end state when at the end of the scroll range, which wouldn't be smooth, we should just disallow center alignment when there are only 2 items since it doesn't make sense to have a center alignment with just 2 items

Will work on this this week
