### ISSUE TITLE
[Carousel] An uncontained carousel cannot be scrolled to the end if there are few items in it

### ISSUE THREAD

**Issue by pubiqq** [material-components/material-components-android#3599]
https://github.com/material-components/material-components-android/assets/82187521/b118d21b-70c6-4afc-bcba-04098bc6f5bb

**Material Library version:** 1.11.0-alpha03
**Device:** Pixel 4a (5G)

**Comment by imhappi** [comment]
A bug has already been filed for this internally (actually it came to our attention because of https://github.com/material-components/material-components-android/issues/3589 !) and is waiting on design guidance for further steps

Since https://github.com/material-components/material-components-android/issues/3598 is actually the same issue (cannot scroll when there are less items than keylines), will close that one as a duplicate

**Comment by imhappi** [comment]
Looking into this more deeply, will un-duplicate as I believe this will require different solutions. Sorry for the churn!
