### ISSUE TITLE
[Button] Double ripple

### ISSUE THREAD

**Issue by pubiqq** [material-components/material-components-android#3605]
_This issue is a duplicate of https://github.com/material-components/material-components-android/issues/2833, but I had to reopen it, because it's still not resolved, and this bug is quite serious as it affects **all** material buttons on devices running API 30 and below._

https://github.com/material-components/material-components-android/assets/82187521/cc9be48f-8eda-4236-b604-c2ed7802de9e

**Material Library version:** 1.11.0-alpha03
**Device:** API 23 Emulator

**Comment by OxygenCobalt** [comment]
Original author here.

AFAIK this also occurs from API 31 onwards, it's just much more subtle (the ripple tinting is off since there's still two layered ripples). I also noticed that you can use any arbitrary `RippleDrawable` on any `AppCompatButton` and trigger this bug, so there is definitely some exact series of drawable method calls that triggers this issue. I just haven't had the time to look into it.

I found a workaround personally by clobbering the internal `mBackgroundTintHelper` field with reflection, which results in the codepath that triggers the bug not being ran, as below:

```kotlin
AppCompatButton::class.java.getDeclaredField("mBackgroundTintHelper").apply {
    isAccessible = true
    set(this@fixDoubleRipple, null)
}
```

I believe this works from API 21 onwards from my testing, but probably breaks on API 19 since my workaround is probably disabling a bunch of compatibility hacks for that version.

**Comment by afohrman** [comment]
Thanks for resurfacing this, @pubiqq, and thanks for filing this initially, @OxygenCobalt. There are two open issues on AppCompat's issue tracker for this (https://issuetracker.google.com/242570967 and https://issuetracker.google.com/262784311), in addition to that other issue in the Material library that was closed in May. I left a comment on one of the AppCompat issues asking for an update, and please feel free to add any extra details. It looks like [this issue](https://issuetracker.google.com/262784311) has more traction, so I'd recommend chiming in on that one.

As for addressing this on the Material side, I did find that https://issuetracker.google.com/262784311#comment5 mentions an interesting workaround which we might be able to use in MaterialButton. I'm going to re-open #2833 to track exploring that workaround. In the meantime, I'm closing this issue so that we can direct all details related to the Material side of this bug in one place.

**Comment by bubbleguuum** [comment]
I do not observe this issue in my own app running in the Android API 29 emulator, clicking with the mouse on various buttons.
Is it a touch only issue ?

**Comment by pubiqq** [comment]
> I do not observe this issue in my own app running in the Android API 29 emulator, clicking with the mouse on various buttons.
Is it a touch only issue ?

On API 29, this problem is also present, but due to the speed and pace of the ripple spreading, it looks like there's only one ripple, and it spreads from the center of the button (which is also incorrect, btw). However, you can slow down the animation and make sure that there are actually two ripples:

https://github.com/material-components/material-components-android/assets/82187521/eafc70d7-701a-413d-8fb2-cb084d8fb0d6

**Comment by afohrman** [comment]
Reopened https://github.com/material-components/material-components-android/issues/2833, please direct all info to that issue.
