### ISSUE TITLE
[MaterialComponentsAndroid-MaterialDatePicker] Incorrect behaviour on Samsung device

### ISSUE THREAD

**Issue by SmirnovDV-98** [material-components/material-components-android#3625]
On Samsung Galaxy S9 Api30 date picker component from demo application behaves totally incorrectly.

System information:

![system1](https://github.com/material-components/material-components-android/assets/61781754/46d689c8-c81f-4ed0-a0dc-1fc2c6c98a58)
![System2](https://github.com/material-components/material-components-android/assets/61781754/3864623d-0663-4ea8-b013-1b856b5aaf6e)

Text input works completely incorrectly, not applying text format and treating hint as simple text

Video of incorrect work attached:
https://github.com/material-components/material-components-android/assets/61781754/e6a7b812-2565-440b-80e5-c6c93a270054

**Comment by hunterstich** [comment]
Hi @SmirnovDV-98,

Could you describe what the expected behavior should be? I see the same behavior on my end running Android 14 on a Pixel but I think this is working as intended.

**Comment by SmirnovDV-98** [comment]
Greetings. In my opinion, expected behaviour would be the same as on my
other phone, Xiaomi 9 Api30 (whole specification on attached screenshot),
when input is restricted with numbers only, the hint is replaced exactly
with inputed numbers, saving text format. I'll attach creenshots, cause
Gmail for some reason don't wanna to send video.

**Comment by SmirnovDV-98** [comment]
video of expected behaviour

https://github.com/material-components/material-components-android/assets/61781754/09bf1977-0946-496b-bbc2-d99bebe5f6b9

video of expected behaviour

**Comment by hunterstich** [comment]
Ah, so the issue is the IME (keyboard) that shows on Samsung is the full alphanumeric keyboard instead of just the numeric keyboard?

**Comment by pubiqq** [comment]
> Ah, so the issue is the IME (keyboard) that shows on Samsung is the full alphanumeric keyboard instead of just the numeric keyboard?

No, the issue is that the date field is automatically filled with the hint text when you enter a character:

<table>
  <tr>
    <th>Actual result</th>
    <th>Expected result</th>
   </tr> 
   <tr>
    <td><video src="https://github.com/material-components/material-components-android/assets/61781754/e6a7b812-2565-440b-80e5-c6c93a270054" width="270px"></td>
    <td><video src="https://user-images.githubusercontent.com/61781754/274149332-09bf1977-0946-496b-bbc2-d99bebe5f6b9.mp4" width="270px"></td>
  </tr>
</table>

**Comment by hunterstich** [comment]
Ah! Thanks for the clarification. And thanks for the PR @pubiqq.

https://github.com/material-components/material-components-android/pull/3628

**Comment by pubiqq** [comment]
Unfortunately, https://github.com/material-components/material-components-android/commit/5aa6edfaed08a6dff8439b51e91cd43e2ffb0386  is an unreliable hack, not a fix. It would be great if you would replace it with [this proposal](https://github.com/material-components/material-components-android/pull/3628).

**Comment by paulfthomas** [comment]
@pubiqq I don't think your fix properly accounts for all the different languages/international date patterns.

**Comment by pubiqq** [comment]
> I don't think your fix properly accounts for all the different languages/international date patterns.

The current implementation doesn't do that either 😂.

My implementation is much better because it uses the actual date pattern and filters characters that are guaranteed to be delimiters, whereas the current implementation uses a decorative string (huh?) and filters all letters and digits in it (huh? x2).

As a result, my implementation works just as well as the current one, but it also:
- Works correctly with digits in the pattern.
- Works correctly with non-Latin letters in the pattern.
- Works correctly with Korean and some other languages (actually, I could even get rid of the hack related to the Korean language in this PR, but I'd like to do it a bit later in another one).

**Comment by pubiqq** [comment]
> I don't think your fix properly accounts for all the different languages/international date patterns.

The current implementation doesn't do that either 😂.

My implementation is much better because it uses the actual date pattern and filters characters that are guaranteed to be delimiters, whereas the current implementation uses a decorative string (huh?) and filters all letters and digits in it (huh? x2).

As a result, my implementation works just as well as the current one, but it also:
- Works correctly with digits in the pattern.
- Works correctly with non-Latin letters in the pattern.
- Works correctly with Korean and some other languages (actually, I could even get rid of the hack related to the Korean language in this PR, but I'd like to do it a bit later in another one).

To account for all the different languages/international date patterns, we will also need to implement the correct handling of single quotation marks, but personally I will be ready to do this only after the `DateFormatTextWatcher` is fixed.

**Comment by automaton82** [comment]
This is affecting me as well with a S22+, it's impossible to type the date anymore. The cursor constantly goes to the end of the input after every key press.

Rolling back to `com.google.android.material:material:1.9.0` solves the problem, it appears to be a regression in `1.10.0`. It would be great if #3662 fixes it, but until then the latest version is unusable.

**Comment by nowulus** [comment]
material version 1.12.0 fixes the problem
