### ISSUE TITLE
Bottom App Bar Dark Colour Issue

### ISSUE THREAD

**Issue by jacklroberts** [material-components/material-components-android#378]
We're transitioning from github issues to a public buganizer component. Rather
than submitting a bug here on github, please file any bugs or feature requests
at https://issuetracker.google.com/issues/new?component=439535.

Hi, I don't know exactly if this is a bug or my stupidity, but when I use the bottom app bar in light mode with primary colours it looks how it should (how I want it too), but if I change the material components theme to dark with the same colour pallet (no values-night) the bottom app bar appears a lighter colour.

![Screenshot_1558633324](https://user-images.githubusercontent.com/21020402/58274454-d7251000-7d8a-11e9-9d73-60375b0feac4.png)
![Screenshot_1558633343](https://user-images.githubusercontent.com/21020402/58274455-d7251000-7d8a-11e9-8311-9703001cb2a4.png)

**Comment by dsn5ft** [comment]
This is the expected behavior as of the recent [Material dark theme guidance](https://material.io/design/color/dark-theme.html#properties) that was published.

See our [dark theme docs](https://github.com/material-components/material-components-android/blob/master/docs/theming/Dark.md) for more engineering information.

**Comment by jacklroberts** [comment]
Ok, thank you 👍
