### ISSUE TITLE
[DrawerLayout] Allow to (temporarily and programmatically) disable predictive back handling 

### ISSUE THREAD

**Issue by iNPUTmice** [material-components/material-components-android#3968]
I have an expand / collapse action inside my DrawerLayout / global navigation. The user first opens the drawer; then clicks on a navigation item; which causes more or different items to be shown. When the user presses back I first want to collapse the navigation item; and then, only on the second back press, close the drawer.

Currently with the automatic on back pressed handling / predictive back this is not possible as the DrawerLayout intercepts all my custom OnBackPressed handlers.

I would like for a possibility to disable the DrawerLayour predictive back momentarily so I can handle that first back press (the one that is supposed to collapse navigation items) myself.

**Comment by dsn5ft** [comment]
Unfortunately this is challenging because `DrawerLayout` (not part of the Material library) registers the back callback internally and there's no API to disable it:

https://cs.android.com/androidx/platform/frameworks/support/+/androidx-main:drawerlayout/drawerlayout/src/main/java/androidx/drawerlayout/widget/DrawerLayout.java;l=2045-2072;drc=68550f4ea52e7a2c2c1802ca6d135578a7a8c52f

However you may be able to register your own callback in `onDrawerOpened` to take precedence over `DrawerLayout` by using a `post()` and `OnBackInvokedDispatcher.PRIORITY_OVERLAY`, similar to what we do in `NavigationView`:

https://github.com/material-components/material-components-android/blob/52b48450fc63a8aa48ba3d89ae888069e31b874a/lib/java/com/google/android/material/navigation/NavigationView.java#L157-L163

https://github.com/material-components/material-components-android/blob/52b48450fc63a8aa48ba3d89ae888069e31b874a/lib/java/com/google/android/material/motion/MaterialBackOrchestrator.java#L179-L183
