### ISSUE TITLE
[BottomNavigationView] Crashes after upgrading to 1.11.0. Getting-Start doc may need an upgrade.

### ISSUE THREAD

**Issue by Tynox** [material-components/material-components-android#4020]
**Android API version:** 30

**Material Library version:** 1.11.0

**Device:** Android Emulator

I upgraded the material library to 1.11.0 and my app keeps crashing when launches. And finally I figured out that in version 1.11.0 the background tint uses a new attribute which is missing in the getting-start (my app uses a AppCompat theme). Then I added this attribute in the style.xml, there are no crashes. 

According to this [commit](https://github.com/material-components/material-components-android/commit/2114a11378fd801b32cd7431bb8a2c94de4f462c), a few default values use new attributes. Maybe the getting-start doc needs an upgrade.

**Comment by dsn5ft** [comment]
The Getting Started guide talks about how it's required to use a Material theme which will set up all of the necessary attributes:

https://github.com/material-components/material-components-android/blob/master/docs/getting-started.md#7-material3-theme-inheritance

Or you can use an AppCompat theme but then you need to make sure to add many attributes so that they can be found by the components.
