### ISSUE TITLE
[ProgressIndicator] CCW CircularProgressIndicator is broken on API 29

### ISSUE THREAD

**Issue by pubiqq** [material-components/material-components-android#4125]
https://github.com/material-components/material-components-android/assets/82187521/6bdcb5cd-1a5c-45c3-b8f2-ab3819dd7e16

**Material Library version:** 1.12.0-beta01

**Devices:**
- API 29 Emulator (Build QSR1.190920.001) - **reproduced**
- Huawei P Smart 2019 (POT-LX1) (Build QP1A.190711.020) - **reproduced**
- API 28 Emulator (Build PSR1.180720.117) - not reproduced
- API 30 Emulator (Build RSR1.201013.001) - not reproduced

**Comment by pekingme** [comment]
Only API 29?

**Comment by pubiqq** [comment]
> Only API 29?

Looks like it (see updated description).

**Comment by Cosebe** [comment]
As I am not a native English speaker, I have used a translation tool for the comment below. I apologize in advance for any awkward expressions that may appear.

Hello everyone,

I hope this comment finds you well. I wanted to share a potential workaround for the issue with CircularProgressIndicator on older SDK versions (29 and below).

After some investigation, we found that the unexpected behavior of scale properties when using hardware acceleration could be addressed by forcing the view to be rendered in a software layer. Here's a Kotlin extension function that implements this fix:

```kotlin
import android.os.Build
import android.view.View.LAYER_TYPE_SOFTWARE
import com.google.android.material.progressindicator.CircularProgressIndicator

fun CircularProgressIndicator.fixDirectionForOlderSDK() {
    // There's an issue in SDK 29 and below where hardware acceleration
    // causes scale properties to behave unexpectedly with
    // CircularProgressIndicator.
    // To address this, we force the view to be rendered in software layer.
    if (Build.VERSION.SDK_INT <= Build.VERSION_CODES.Q) {
        setLayerType(LAYER_TYPE_SOFTWARE, null)
    }
}
```

You can apply this fix by calling the extension function on your CircularProgressIndicator instance:

```kotlin
yourCircularProgressIndicator.fixDirectionForOlderSDK()
```

While this may not be a perfect solution, it has helped in our case to achieve the expected behavior on older devices. Please note that using software rendering might have some performance implications, so it's advisable to test thoroughly in your specific use case.

I hope this helps! If anyone has any questions or has found alternative solutions, please feel free to share. Together, we can work towards improving the experience for all users across different Android versions.

Thank you for your attention to this issue!
