### ISSUE TITLE
[TopAppBar] Material Design Rules

### ISSUE THREAD

**Issue by patrickfrei** [material-components/material-components-android#4156]
**Description:** My app has a `MainActivity` and an `AboutActivity`. The latter is showing some information about the app, such as version, copyright, etc. The `AboutActivity` is called by an `Intent`.

I'm unsure how the design of the AboutActivity's TopAppBar should look like when applying the M3 design rules. I've seen the following two design variants:

1) The [M3 documentation](https://github.com/material-components/material-components-android/blob/master/docs/components/TopAppBar.md) shows the following design:
- light-grey background for status bar and TopAppBar
- background for content: white or light-grey??
- close-icon
![topappbar_small](https://github.com/material-components/material-components-android/assets/7906165/56f2915f-f549-4b02-8933-513346bc3ce8)

2) The M3 catalog app shows the following design:
- white background for status bar and TopAppBar
- white background for content
- status bar and TopAppBar change color to light-grey when scrolling up
- back-arrow-icon
<img width="540" alt="Screenshot_1714153324" src="https://github.com/material-components/material-components-android/assets/7906165/4b5d9fd1-c9cb-44f7-98eb-95c73808fdd5">

Could you please tell which design variant would be the correct one for my app?

Many thanks!

**Comment by imhappi** [comment]
Hi @patrickfrei I believe the first example you've linked above is just showing the top app bar when scrolled (ie. it is the lift on scroll colour, so it is the same variant as the second example, just scrolled and with some different icons).

Although note that there are also multiple other variants with the top app bar that you can see in the catalog app as well, such as the ones with headlines (eg. collapsing toolbar) which are all valid and depending on your use case. You can see here for guidelines https://m3.material.io/components/top-app-bar/guidelines

although it does look like the design specs do advise using a back arrow instead of the 'x'. I'll file a bug to update this in our catalog app
