### ISSUE TITLE
BottomNavigationView taking full height if no minHeight is set

### ISSUE THREAD

**Issue by mikolajefento** [material-components/material-components-android#4247]
**Description:** 
In [this](https://github.com/material-components/material-components-android/commit/943c4f0eedb35850f19167ac989387f5b640af2f) commit new attribute of `minHeight` was added. The default value is set to 0, and when combined with `wrap_content` the BottomNavigationView is taking up all free space. The result is that from version 1.5.0 onwards one must set minHeight in order to display BottomNavigationView correctly.

**Expected behavior:** 
`wrap_content` working correctly as in version < 1.5.0 without having to set `minHeight`

**Source code:** 
```
    <com.google.android.material.bottomnavigation.BottomNavigationView
        android:id="@+id/bottom_navigation"
        android:layout_width="0dp"
        android:layout_height="wrap_content"
        app:layout_constraintBottom_toBottomOf="parent"
        app:layout_constraintEnd_toEndOf="parent"
        app:layout_constraintStart_toStartOf="parent"
        app:menu="@menu/app_menu" />
```

**Android API version:** 34

**Material Library version:**  1.12.0 (bug exist from >= 1.5.0)

**Device:** Emulator & Motorola moto g22

**Comment by imhappi** [comment]
Hi @mikolajefento ! Recently in 1.13-alpha03, some changes were submitted to change BottomNavigationView to use the minHeight attribute as an actual minimum height, not an exact height. I'm going to close this issue as I believe the issue you are describing should be fixed with that change, but feel free to re-open if it is still happening
