### ISSUE TITLE
[MaterialCheckBox] Cannot customize checkbox with attribute android:button

### ISSUE THREAD

**Issue by dturant** [material-components/material-components-android#4312]
**Description:** I want to customize checkboxes by setting a custom checkbox drawable selector with android:button attribute. It doesn't work - setting android:button on a checkbox doesn't change anything. I can't rely only on buttonTint and buttonIconTint because I want to be able to control whether border is visible or not, have different color for indeterminate checkboxes and so on.

**Expected behavior:** Setting android:button on a checkbox changes checkbox drawable

**Source code:** 
```
<com.google.android.material.checkbox.MaterialCheckBox
                    android:id="@+id/read_checkbox"
                    android:layout_width="wrap_content"
                    android:layout_height="wrap_content"
                    android:button="@drawable/square_checkbox_selector" />
```
square_checkbox_selector:
```
<?xml version="1.0" encoding="utf-8"?>
<selector xmlns:android="http://schemas.android.com/apk/res/android">
    <item android:drawable="@drawable/ic_disabled_square_checkbox" android:state_checked="true" android:state_enabled="false" />
    <item android:drawable="@drawable/ic_disabled_unchecked_square_checkbox" android:state_checked="false" android:state_enabled="false" />
    <item android:drawable="@drawable/ic_unchecked_square_checkbox" android:state_checked="false" />
    <item android:drawable="@drawable/ic_checked_square_checkbox" android:state_checked="true" />
</selector>

```

**Android API version:** Android API 34

**Material Library version:** 1.13.0-alpha06

**Device:** Pixel 5 emulator

**Comment by dsn5ft** [comment]
Hello! I think this might be because MaterialCheckBox inherits from AppCompatCheckBox and in AppCompat they set both `buttonCompat` and `android:button`:

https://cs.android.com/androidx/platform/frameworks/support/+/androidx-main:appcompat/appcompat/src/main/res/values/styles_base.xml;l=392-393;drc=b7128d8e04b51282d09a8d3e45a1c4aa63c6998a

Can you try setting `buttonCompat` instead of or in addition to `android:button` to see if that fixes the issue?

Closing the issue for now since that seems to be the likely cause, but let me know if that fixes the issue or if not feel free to reopen.

**Comment by dsn5ft** [comment]
Some more info here as well: https://github.com/material-components/material-components-android/blob/master/docs/components/Checkbox.md#checkbox-attributes

**Comment by dturant** [comment]
@dsn5ft Unfortunately this doesn't help.
Here's a sample app: 
[MaterialCheckboxExample.zip](https://github.com/user-attachments/files/17138662/MaterialCheckboxExample.zip)
