### ISSUE TITLE
Outdated DrawerLayout dependency: 1.1.1 instead of 1.2.0

### ISSUE THREAD

**Issue by mtotschnig** [material-components/material-components-android#4402]
**Is your feature request related to a problem? Please describe.**
In my project I was relying on the transitive dependency on Androidx DrawerLayout that this project provides, and was surprised when I realized that I was missing out on the latest DrawerLayout 1.2.0 published on March 22, 2023. While I can easily fix this, by adding an explicit dependency, I was wondering if material components depending on an old version was by omission or by design?

**Comment by dsn5ft** [comment]
Just a heads up that this was reverted in https://github.com/material-components/material-components-android/commit/4662301f7bfe14a12d92caa22040f059609d3e4e.

It is actually by design that the Material library depends on the oldest versions of other androidx library that it can, that way we don't unnecessarily force apps to upgrade their androidx versions. We typically only update our androidx dependencies when we need to use a new API from an androidx library within the Material library.
