### ISSUE TITLE
[BottomNavigationView] Scrolling View offset for BottomNavigationView in CoordinatorLayout

### ISSUE THREAD

**Issue by Sourav-21** [material-components/material-components-android#442]
In `CoordinatorLayout` when I set a `ScrollingViewBehavior` for a `RecyclerView` it automatically creates an offset for AppBarLayout. But it doesn't create any offset for `BottomNavigationView` and `BottomNavigationView` overlaps the `RecyclerView`.

I can temporarily solve this problem by setting `clipToPadding` in `RecyclerView`. But `BottomNavigationView` also covers the over scroll animation.

**Comment by dupovalo** [comment]
> I can temporarily solve this problem by setting `clipToPadding` in `RecyclerView`. But `BottomNavigationView` also covers the over scroll animation.

Hi @Sourav-21 , just faced the same problem yesterday and solved it by applying a custom scrolling behaviour to my recycler view. Here is the custom behaviour. Try if it may help you.

`import android.content.Context;
import android.util.AttributeSet;
import android.view.View;

import androidx.coordinatorlayout.widget.CoordinatorLayout;

import com.google.android.material.appbar.AppBarLayout;
import com.google.android.material.bottomnavigation.BottomNavigationView;

public class ScrollingViewAboveBottomNavigationBehavior extends AppBarLayout.ScrollingViewBehavior {

    private int marginBottom = 0;

    public ScrollingViewAboveBottomNavigationBehavior() {
        super();
    }

    public ScrollingViewAboveBottomNavigationBehavior(Context context, AttributeSet attrs) {
        super(context, attrs);
    }

    @Override
    public boolean layoutDependsOn(CoordinatorLayout parent, View child, View dependency) {
        return super.layoutDependsOn(parent, child, dependency)
                || (dependency instanceof BottomNavigationView);
    }

    @Override
    public boolean onDependentViewChanged(CoordinatorLayout parent, View child, View dependency) {
        return super.onDependentViewChanged(parent, child, dependency)
                | /* [!] single pipe is required */ updateBottomMarginIfNeeded(child, dependency);
    }

    private boolean updateBottomMarginIfNeeded(View child, View dependency) {
        if (dependency instanceof BottomNavigationView
                && dependency.getMeasuredHeight() != this.marginBottom) {
            this.marginBottom = dependency.getMeasuredHeight();
            CoordinatorLayout.LayoutParams lp = (CoordinatorLayout.LayoutParams) child.getLayoutParams();
            lp.bottomMargin = this.marginBottom;
            child.requestLayout();
            return true;
        }
        return false;
    }
}`

P.S. Perhaps, it's better to have this within the default behaviour, because it seems not so rare nowadays.

**Comment by Sourav-21** [comment]
Thank you @dupovalo 
It looks interesting. I shall try this. My temporary solution is to put the whole CoordinatorLayout inside a LinearLayout.

**Comment by drchen** [comment]
Hi, BottomNavigationView's scrolling view behavior depends on each app's UX requirement and there's no single solution can serve everyone's need. Considering that it's really easy to implement the requested behavior (prevent overlapping between bottom navigation and RecyclerView) on your own, we decided not to add this into the library. 

But please still feel free to add a pull request if you really want that. If the solution is general enough and makes sense, we will be happy to adopt it. : )
