### ISSUE TITLE
[Catalog App] Unable to build catalog app from source code

### ISSUE THREAD

**Issue by patrickfrei** [material-components/material-components-android#4447]
**Description:** I'm trying to build the M3 catalog app by using **Android Studio Ladybug Feature Drop | 2024.2.2 Beta 1** and the latest available M3 [repository](https://github.com/material-components/material-components-android) as of today. However, I'm getting various errors:
```
Invalid Gradle JDK configuration found
Undefined java.home on the project gradle/config.properties file when using the gradleJvm #GRADLE_LOCAL_JAVA_HOME macro. To mitigate the issue, this was changed to use the Embedded JDK (JetBrains Runtime 21.0.4).
```
```
Your build is currently configured to use incompatible Java 21.0.4 and Gradle 7.6.2. Cannot sync the project.
We recommend upgrading to Gradle version 8.9.
The minimum compatible Gradle version is 8.5.
The maximum compatible Gradle JVM version is 19.
Possible solutions:
 - Upgrade to Gradle 8.9 and re-sync
 - Upgrade to Gradle 8.5 and re-sync
```

I clicked on `Upgrade to Gradle 8.5 and re-sync` and it successfuly synced the project. But during the build process, I've got another compilation error:
```
\lib\java\com\google\android\material\loadingindicator\LoadingIndicatorDrawingDelegate.java:33: Error: Symbol not found
import androidx.graphics.shapes.Shapes_androidKt;
```
In addition, I get...
`Android Gradle plugin version 7.4.2 has an upgrade available. Start the AGP Upgrade Assistant to update this project's AGP version.`
But that doesn't work either as I get... 
`This step is blocked. The upgrade assistant is unable to upgrade this project.`

**Expected behavior:** Compiling the source is successful without errors. How can I build the catalog app without errors?

**Minimal sample app repro:** Download the current M3 project code on https://github.com/material-components/material-components-android ("master" branch).

**Comment by manabu-nakamura** [comment]
https://github.com/material-components/material-components-android/issues/4338#issuecomment-2408415458
https://issuetracker.google.com/issues/361215219

**Comment by hunterstich** [comment]
Hi @patrickfrei

This is probably because Gradle is using something other than Java 11 to build the project.

For our project, you need to use:
 
* <b>Java 11</b>
Check Android Studio > Settings > Build, Execution, Deployment > Build Tools > Gradle to view/change what jdk Gradle is using. There is a drop down box for "Gradle JDK" that should tell you what jdk version you are using. This needs to be changed to version 11.

* <b>Gradle 7.6.2</b>
Set in `material-components-android/gradle/wrapper/gradle-wrapper.properties`

* <b>Android Gradle Plugin version 7.4.2</b>
Set in `material-components-android/build.gradle`

If you've imported the project and let Android Studio update your Gradle or AGP automatically, you'll likely want to revert those changes. I would check the above locations and versions to confirm these are 

More info if you're interested - https://developer.android.com/build/jdks

Closing this but please feel free to re-open if you still have issues!

**Comment by manabu-nakamura** [comment]
Do you have a plan to use new tools?

**Comment by hunterstich** [comment]
Yes, we're working on migrating to Gradle 8+ and AGP 8+

**Comment by manabu-nakamura** [comment]
I'm looking forward to seeing it soon.
See also: https://github.com/material-components/material-components-android/issues/4338#issuecomment-2408415458

**Comment by manabu-nakamura** [comment]
https://github.com/material-components/material-components-android/commit/2c2a26cd9e711fd52f1bd8cdfabce9fc5f4a4ee7
