### ISSUE TITLE
[AppBar] `MaterialToolbar` styles shouldn't use `android:theme`

### ISSUE THREAD

**Issue by alexjlockwood** [material-components/material-components-android#472]
**Description:** `MaterialToolbar` styles shouldn't use `android:theme`, because this prevents developers from being able to use the theme as a default style. The styles should use `materialThemeOverlay` instead. 

I'm guessing this code was probably written before to `materialThemeOverlay` was a thing because the very similar `BottomAppBar` component correctly uses `materialThemeOverlay here: https://github.com/material-components/material-components-android/blob/master/lib/java/com/google/android/material/bottomappbar/res/values/styles.xml#L32-L35

**Source code:** https://github.com/material-components/material-components-android/blob/master/lib/java/com/google/android/material/appbar/res/values/styles.xml#L58-L73

**Comment by dsn5ft** [comment]
Thanks for reporting, @alexjlockwood. The other tricky detail here is that the `Widget.MaterialComponents.Toolbar` styles were originally written for AppCompat `Toolbar`s, which we still want to support. Since AppCompat `Toolbar`s don't know about `materialThemeOverlay`, I think we'll want to keep `android:theme` in these styles, and add a duplicate `materialThemeOverlay` for the default style case. We might also want to update [ThemeEnforcement#createThemedContext](https://github.com/material-components/material-components-android/blob/master/lib/java/com/google/android/material/internal/ThemeEnforcement.java#L268) to not add the extra `materialThemeOverlay` if the same `android:theme` is actually being applied.

Alternatively, we could split the `MaterialToolbar` styling from the AppCompat `Toolbar` styling by introducing a `materialToolbarStyle` attr + `Widget.MaterialComponents.MaterialToolbar`, but since `MaterialToolbar` is intended as a thin layer I'm not sure we want to go down that road just yet.

**Comment by drchen** [comment]
FYI in Material 3 toolbar styles, we moved to use materialThemeOverlay instead.

I'll close the issue as obsolete. : )
