### ISSUE TITLE
[Appbar] Appbar does not follow colorPrimary

### ISSUE THREAD

**Issue by LossyDragon** [material-components/material-components-android#473]
**Description:** Full description of issue here

Staring after material:1.1.0-alpha05 the appbar color is no longer taking the primaryColor of an application. 

(Screenshot is with alpha08)
![alpha08](https://user-images.githubusercontent.com/4994318/62020966-a72f2a00-b18a-11e9-8bc0-def48554a755.png)

**Expected behavior:** Screenshots and/or description of expected behavior

App bar should color itself with the primary color when using a theme that puts in an actionbar

eg:  <style name="AppTheme" parent="Theme.MaterialComponents">

(Screenshot is with alpha05)
![alpha05](https://user-images.githubusercontent.com/4994318/62020963-a0081c00-b18a-11e9-9eae-6822f657bdf8.png)

**Android API version:** Android API version here
API 28

**Material Library version:** Material Android Library version you are using here (e.g., 1.1.0-alpha07)

Working:
com.google.android.material:material:1.1.0-alpha05

Affected:
com.google.android.material:material:1.1.0-alpha06
com.google.android.material:material:1.1.0-alpha07
com.google.android.material:material:1.1.0-alpha08

**Comment by dsn5ft** [comment]
Hello! This is the intended behavior, as our [dark theme guidance](https://material.io/design/color/dark-theme.html#custom-application) for components that use a large portion of a screen is that they should use `colorSurface` for their background instead of `colorPrimary` or `colorAccent`, so AppBarLayouts, Toolbars, and ActionBars now default to their `Surface` styles in dark theme.

**Comment by LossyDragon** [comment]
Thanks! Explains a lot and now works. :D
