### ISSUE TITLE
[TextInputLayout] Unable to change error drawable icon

### ISSUE THREAD

**Issue by ugurcany** [material-components/material-components-android#485]
**Description:** It's not possible to change error icon of a `TextInputLayout` with **version 1.1.0-alpha09**

**Expected behavior:** Error drawable should be changed, but still seeing default red circle exclamation mark.

**Source code:** 
```
inputLayout.apply {
            val errorIcon = ContextCompat.getDrawable(context, R.drawable.ic_alert)
            errorIcon?.setBounds(0, 0, errorIcon.intrinsicWidth, errorIcon.intrinsicHeight)

            error = errorMessage
            endIconDrawable = errorIcon
            endIconMode = TextInputLayout.END_ICON_CUSTOM
            setEndIconTintMode(PorterDuff.Mode.DST)
        }
```

**Android API version:** 28

**Material Library version:** 1.1.0-alpha09

**Device:** Pixel_2_API_28 Emulator

**Comment by leticiarossi** [comment]
Hi! the error icon API introduced in https://github.com/material-components/material-components-android/commit/3f73804b576fafe77febb75f06ac33b832588192 is independent from the endIconMode API. 
In order to change the default icon you should use setErrorIconDrawable, setErrorIconTintList and setErrorIconTintMode (or the attributes errorIconDrawable, errorIconTint and errorIconTintMode)

**Comment by aalap03** [comment]
are these attributes are not available in version 1.1.0 ? As I dont see those, also there used to be suffixText, but that's not there anymore.

**Comment by leticiarossi** [comment]
@aalap03 yes those attrs are in 1.1.0! Suffix and prefix support was introduced in 1.2.0-alpha01

**Comment by aalap03** [comment]
When I use app:suffixText, it gives error. there is nothing with suffix or predfix support in 1.1.0 it seems.
