### ISSUE TITLE
[TextInputLayout] endIconMode change dynamically not possible

### ISSUE THREAD

**Issue by ramden** [material-components/material-components-android#503]
**Description:** 
Changing endIconMode of a TextInputLayout (combination with TextInputEditText) does not work dynamically.

To reproduce:
Set a textbox endIconMode first to "clear". 

After that set endIconMode to "custom" and set a custom icon drawable - produces strange results. 

The end icon is not visible anymore. 

After pressing/tapping the area where the endIcon should reside, the icon is visible for a short period of time (milliseconds) showing the changed icon.

**Expected behavior:** endIconMode should change dynamically without causing it to break endIcon functionality

**Source code:**
Initial state:

`textBox.endIconMode="clear"`

Later (change from an event outside / button click / something else):

`textBox.endIconMode="custom"`
`textBox.endIconDrawable = someDrawable`

**Android API version:** 28

**Material Library version:** 1.1.0-alpha09

**Device:** Samsung Galaxy S9 / Emulator

**Comment by amzer-nazeer** [comment]
I too ran into this issue.. Ihave an exposed drop down menu using AutoCompleteTextView inside TextInputLayout.

After the user select an item from the drop down.. I set the endIcon to END_ICON_CLEAR_TEXT to give the user the option to clear his selection. Works perfect until this..  When it is cleared, I want to set the endIcon to END_ICON_DROPDOWN_MENU... It doesnt show.. Tried adding a TextWatcher but nothing helped

**Comment by Magtuz** [comment]
Also seems like setEndIconCheckable method is not called after new endIcon was set. So if it was END_ICON_CLEAR_TEXT before, END_ICON_PASSWORD_TOGGLE will not work properly, until you will call setEndIconCheckable.

**Comment by rodolfo-tenfen** [comment]
I have the same problem, I'm trying to change between CUSTOM and CLEAR_TEXT modes depending on whether the `TextInputEditText` is empty or not. So CUSTOM when empty and CLEAR_TEXT otherwise.

What I found is that, when the `TextInputEditText` is cleared (by pressing the Clear Text button or by deleting the text with the keyboard), the Clear Text button disappears using an animation, which sets its alpha to `0`. So when the mode is changed to CUSTOM and the icon replaced, the animation is not stopped and it ends up hiding the new icon. Forcing the button's alpha to go back to `1` _after_ the animation ends works. However, because the animation will still run, the icon will "blink".

**Comment by tapan-jtechworld** [comment]
Is there any update on this fix ?

**Comment by TobyEb** [comment]
i still got some strange behavior when switching dynamically between endIconMode `clear_text` and ` dropdown_menu`.

i tried the following implementation, if an item is selected i want the endIconMode to be `clear_text` if the input is empty i want `dropdown_menu`.

setting `dropdown_menu` after `clear_text` was clicked, leads to an invisible icon because of the `clear_text` icon animation. 

when calling `showDropdown()` after the clear icon was clicked, and selecting an item, the clear icon is also invisible even the input contains text. nevertheless the icon is clickable, so i assume this is also a problem with the alpha animation

**Comment by SDILogin** [comment]
I had the same issue. My solutions was quite simple: implement clear_text behavior with mode=CUSTOM_ICON. It'll look like this 
```kotlin 
textInputLayout.endIconMode = TextInputLayout.END_ICON_CUSTOM // may be set in xml 
textInputLayout.setEndIconDrawable(com.google.android.material.R.drawable.mtrl_ic_cancel)
textInputLayout.setEndIconOnClickListener { textInputLayout.editText?.text?.clear() } 
``` 

I'm not sure it'll work in all possible cases. It's better to **_check ClearTextEndIconDelegate before doing any tricks_** with textInputLayout. 

The main problem of the ClearTextEndIconDelegate is internal animations. Because of them it's impossible to call `textInputLayout#setEndIconVisible` right after switch between end icon modes. `iconInAnim#onAnimationEnd` will hide end icon in a few ms (exact animation time depends on a device settings). 

If ClearTextEndIconDelegate is required and can't be replaced, it's possible to remove all listeners from iconInAnim by using reflection. In this case `setEndIconVisible(false)` won't be invoked and end icon will stay on screen, but you will need to add proguard/r8 rules to make sure everything is okay in release builds. 

Also there is an opportunity to create a custom TextInputLayout with overridden  setEndIconVisible and analyze a call stack to determinate when `ClearTextEndIconDelegate.iconInAnim.onAnimationEnd` invokes `TextInputLayout#setEndIconVisible`. Invocation of `setEndIconVisible(false)` from iconInAnim may be ignored to prevent end icon disappear.

**Comment by maklaymiklyxa** [comment]
main problem with dynamically changes of endiconmode that there is no realisation for removing all textwatchers from previous working mode(and it is real pain for me)!
i think that developers must implement OnEndIconChangedListener for all EndIconDelegate and remove all textwatchers.
`/**
   * Callback interface invoked when the view's end icon changes.
   *
   * @see #setEndIconMode(int)
   */
  public interface OnEndIconChangedListener {

    /**
     * Called when the end icon changes.
     *
     * @param textInputLayout the {@link TextInputLayout}
     * @param previousIcon the {@link EndIconMode} the view previously had set
     */
    void onEndIconChanged(TextInputLayout textInputLayout, @EndIconMode int previousIcon);
  }`

**Comment by maklaymiklyxa** [comment]
so problem still here!
with END_ICON_CLEAR_TEXT the code below is runnable, so it's called after afterTextChanged(afterTextChanged-> Runnable block), but as i understood it was fix for this one https://github.com/material-components/material-components-android/commit/963ad14b84a4ae65d480c471ec6139746f02f7a0
```
editText.post(
                new Runnable() {
                  @Override
                  public void run() {
                    editText.removeTextChangedListener(clearTextEndIconTextWatcher);
                  }
                });
```

also you started work with onFocusChangeListener so if someone has his own onFocusChangeListener you remove it
```
if (editText.getOnFocusChangeListener() == onFocusChangeListener) {
              editText.setOnFocusChangeListener(null);
            }
```

**Comment by angelix** [comment]
Based on @SDILogin solution, i have created the following extension for a custom paste icon along with clear_text functionality.

```
fun TextInputLayout.endIconCopyMode() {
    endIconMode = TextInputLayout.END_ICON_CUSTOM

    setEndIconDrawable(if (editText?.text.isNullOrBlank()) R.drawable.ic_baseline_content_paste_24 else com.google.android.material.R.drawable.mtrl_ic_cancel)

    editText?.doAfterTextChanged {
        setEndIconDrawable(if (it.isNullOrBlank()) R.drawable.ic_baseline_content_paste_24 else com.google.android.material.R.drawable.mtrl_ic_cancel)
    }

    setEndIconOnClickListener {
        if (editText?.text.isNullOrBlank()) {
            editText?.setText(getClipboard(context))
        } else {
            editText?.text?.clear()
        }
    }
}
```

**Comment by simakovvv-areality** [comment]
Hi all. I've finally found the way to make dynamically endIcon change works. My problem was that after changing the icon to "password toggle", the function of showing the password by clicking on the eye stopped working for me.
` fun TextInputLayout.enableEye(needToChange: Boolean) {

    clearOnEndIconChangedListeners()  // After removing the listeners, this function appeared, but the icon change still did not //work. When I clicked on the eye, the text appeared and the eye icon remained the same. RefreshEndIconDrawableState () did //not help
    endIconMode = if(s.isNullOrEmpty()) {
        TextInputLayout.END_ICON_NONE
    } else {
        TextInputLayout.END_ICON_PASSWORD_TOGGLE
    }

    if(!s.isNullOrEmpty()) {
        endIconDrawable = AppCompatResources.getDrawable(context, R.drawable.switch_password_toggle_selected)
    }
}`

R.drawable.switch_password_toggle_selected - icon state selector.
`<selector xmlns:android="http://schemas.android.com/apk/res/android">
    <item android:drawable="@drawable/ic_eye_open"
        android:state_checked="false"/>
    <item android:drawable="@drawable/ic_eye_closed"/>
</selector>`

@drawable/ic_eye_closed:
`<vector xmlns:android="http://schemas.android.com/apk/res/android"
    android:width="24dp"
    android:height="24dp"
    android:viewportWidth="24.0"
    android:viewportHeight="24.0">
  <path
      android:fillColor="@color/mr_yellow"
      android:pathData="M12,7c2.76,0 5,2.24 5,5 0,0.65 -0.13,1.26 -0.36,1.83l2.92,2.92c1.51,-1.26 2.7,-2.89 3.43,-4.75 -1.73,-4.39 -6,-7.5 -11,-7.5 -1.4,0 -2.74,0.25 -3.98,0.7l2.16,2.16C10.74,7.13 11.35,7 12,7zM2,4.27l2.28,2.28 0.46,0.46C3.08,8.3 1.78,10.02 1,12c1.73,4.39 6,7.5 11,7.5 1.55,0 3.03,-0.3 4.38,-0.84l0.42,0.42L19.73,22 21,20.73 3.27,3 2,4.27zM7.53,9.8l1.55,1.55c-0.05,0.21 -0.08,0.43 -0.08,0.65 0,1.66 1.34,3 3,3 0.22,0 0.44,-0.03 0.65,-0.08l1.55,1.55c-0.67,0.33 -1.41,0.53 -2.2,0.53 -2.76,0 -5,-2.24 -5,-5 0,-0.79 0.2,-1.53 0.53,-2.2zM11.84,9.02l3.15,3.15 0.02,-0.16c0,-1.66 -1.34,-3 -3,-3l-0.17,0.01z"/>
</vector>`

@drawable/ic_eye_open:
`<vector xmlns:android="http://schemas.android.com/apk/res/android"
    android:width="24dp"
    android:height="24dp"
    android:viewportWidth="24.0"
    android:viewportHeight="24.0">
  <path
      android:fillColor="@color/mr_yellow"
      android:pathData="M12,4.5C7,4.5 2.73,7.61 1,12c1.73,4.39 6,7.5 11,7.5s9.27,-3.11 11,-7.5c-1.73,-4.39 -6,-7.5 -11,-7.5zM12,17c-2.76,0 -5,-2.24 -5,-5s2.24,-5 5,-5 5,2.24 5,5 -2.24,5 -5,5zM12,9c-1.66,0 -3,1.34 -3,3s1.34,3 3,3 3,-1.34 3,-3 -1.34,-3 -3,-3z"/>
</vector>`

**Comment by maresan** [comment]
Hi everybody! I used your code but not the function. I directly used the Drawable in the TextInputLayout as follows and it works perfectly. :D

```
    <com.google.android.material.textfield.TextInputLayout
        ...
        app:endIconMode="password_toggle"
        app:endIconDrawable="@drawable/switch_password_toggle_selected"
       ...

```

The code of yours that I used was the following


> 
> ```
> <selector xmlns:android="http://schemas.android.com/apk/res/android">
>     <item android:drawable="@drawable/ic_eye_open"
>         android:state_checked="false"/>
>     <item android:drawable="@drawable/ic_eye_closed"/>
> </selector>
> ```
> 
> @drawable/ic_eye_closed:
> 
> ```
> <vector xmlns:android="http://schemas.android.com/apk/res/android"
>     android:width="24dp"
>     android:height="24dp"
>     android:viewportWidth="24.0"
>     android:viewportHeight="24.0">
>   <path
>       android:fillColor="@color/mr_yellow"
>       android:pathData="M12,7c2.76,0 5,2.24 5,5 0,0.65 -0.13,1.26 -0.36,1.83l2.92,2.92c1.51,-1.26 2.7,-2.89 3.43,-4.75 -1.73,-4.39 -6,-7.5 -11,-7.5 -1.4,0 -2.74,0.25 -3.98,0.7l2.16,2.16C10.74,7.13 11.35,7 12,7zM2,4.27l2.28,2.28 0.46,0.46C3.08,8.3 1.78,10.02 1,12c1.73,4.39 6,7.5 11,7.5 1.55,0 3.03,-0.3 4.38,-0.84l0.42,0.42L19.73,22 21,20.73 3.27,3 2,4.27zM7.53,9.8l1.55,1.55c-0.05,0.21 -0.08,0.43 -0.08,0.65 0,1.66 1.34,3 3,3 0.22,0 0.44,-0.03 0.65,-0.08l1.55,1.55c-0.67,0.33 -1.41,0.53 -2.2,0.53 -2.76,0 -5,-2.24 -5,-5 0,-0.79 0.2,-1.53 0.53,-2.2zM11.84,9.02l3.15,3.15 0.02,-0.16c0,-1.66 -1.34,-3 -3,-3l-0.17,0.01z"/>
> </vector>
> ```
> 
> @drawable/ic_eye_open:
> 
> ```
> <vector xmlns:android="http://schemas.android.com/apk/res/android"
>     android:width="24dp"
>     android:height="24dp"
>     android:viewportWidth="24.0"
>     android:viewportHeight="24.0">
>   <path
>       android:fillColor="@color/mr_yellow"
>       android:pathData="M12,4.5C7,4.5 2.73,7.61 1,12c1.73,4.39 6,7.5 11,7.5s9.27,-3.11 11,-7.5c-1.73,-4.39 -6,-7.5 -11,-7.5zM12,17c-2.76,0 -5,-2.24 -5,-5s2.24,-5 5,-5 5,2.24 5,5 -2.24,5 -5,5zM12,9c-1.66,0 -3,1.34 -3,3s1.34,3 3,3 3,-1.34 3,-3 -1.34,-3 -3,-3z"/>
> </vector>
> ```

**Comment by sophie-capricorne-fox** [comment]
It is still not working by the way, why close the issue ? 
I've wasted a lot of time just to find out this is a bug that has never been fixed :/
