### ISSUE TITLE
What is the plan for release 1.1.0

### ISSUE THREAD

**Issue by gabrielemariotti** [material-components/material-components-android#577]
The first 1.1.0-alpha was released almost 1 year ago and it is a very huge period.
In the meantime the 1.0.0 didn't receive any updates or minor bug fixes.  

What is the plan to release a **stable 1.1.0** ?

**Comment by MGaetan89** [comment]
They are waiting for other AndroidX libraries to reach stable: [build.gradle#L27](https://github.com/material-components/material-components-android/blob/1.1.0-alpha10/build.gradle#L27)
Most of them did last week, but not all of them (`coordinatorlayout` and `viewpager2`).
I don't know if something else is blocking the stable release of 1.1.0.

**Comment by adityabhaskar** [comment]
> They are waiting for other AndroidX libraries to reach stable: [build.gradle#L27](https://github.com/material-components/material-components-android/blob/1.1.0-alpha10/build.gradle#L27)
> Most of them did last week, but not all of them (`coordinatorlayout` and `viewpager2`).
> I don't know if something else is blocking the stable release of 1.1.0.

But other libraries are already at least in beta or RC. Material 1.1.0 is still in alpha, which means the API [still changes](https://github.com/material-components/material-components-android/releases/tag/1.1.0-alpha10). 

If the delay was due to dependencies, the API should have stabilised and probably moved to beta after the other libs moved to beta/RC.

**Comment by ldjcmu** [comment]
We're working on releasing a beta with final API changes and bug fixes (e.g., NPEs) based on alpha-10 "soon". All our dependencies are in beta now, so we're getting close.
