### ISSUE TITLE
a question about 'gradlew assembleRelease'

### ISSUE THREAD

**Issue by LuodiJackShen** [material-components/material-components-android#67]
1. 

> git clone https://github.com/material-components/material-components-android.git

2.  

> gradlew assembleRelease

finally, i got the aar file(located in lib/build/outputs/aar/),but the aar is empty, i can not find any class in the aar/class.jar and can not use it. Can you tell me why, thank you?
![1](https://user-images.githubusercontent.com/25525335/37639966-66a25a10-2c4e-11e8-99dc-85cad2887a16.PNG)
![2](https://user-images.githubusercontent.com/25525335/37639967-66d84882-2c4e-11e8-91af-fc00b22ee44f.PNG)

[https://github.com/material-components/material-components-android/blob/master/docs/howto.md](https://github.com/material-components/material-components-android/blob/master/docs/howto.md)

**Comment by dsn5ft** [comment]
Hi @LuodiJackShen, thanks for reaching out!

Our project is now split up into several Gradle/Maven modules, which is why there are no class files in the top-level module (`lib/build/outputs/aar`).

Instead of running `./gradlew assembleRelease`, you can run `./gradlew uploadArchives -PmavenRepoUrl="file://localhost/$HOME/Desktop/material_aars"`, which will output all of the AARs/Maven artifacts to a `material_aars` directory on your Desktop. To use the AARs locally, you could copy the output in `material_aars` into your local Maven repository (`~/.m2/repository`), add `mavenLocal()` as a repository in your project's top-level `build.gradle`, and then add the design library dependency as you would normally.

I will update the How To docs so this is more clear. Let us know if you have any other questions.

**Comment by LuodiJackShen** [comment]
thanks
