### ISSUE TITLE
[TextInputLayout] text color

### ISSUE THREAD

**Issue by gabrielemariotti** [material-components/material-components-android#673]
Currently the text color of the `TextInputEditText` is based on `android:textColorPrimary`.

In the `Widget.MaterialComponents.TextInputLayout.*` styles are defined all the text colors (hintText, helperText, counterText, helperText) used by `TextInputEditLayout`.
To improve the readability of the style it might be useful to add another attribute in the style to define the color(selector) of text.

In general `android:textColorPrimary`, except for a few components, is not overridden or related to [material colors](https://github.com/material-components/material-components-android/blob/master/docs/theming/Color.md). It makes more difficult to override it defining a materialThemeOverlay.

**Comment by leticiarossi** [comment]
You can change the input text color via the edit text's `android:textColor` attribute in the edit text directly or in a style that extends a `TextInputEditText` style. It's an existing framework attribute so that's why there is no `app:inputTextColor`, for example, while the other features (helper text, counter text, etc) are specific of the `TextInputLayout` so they have those color attributes.

**Comment by gabrielemariotti** [comment]
I agree with the existing framework attribute. It could be redundant.

However evaluate to add in the `Base.Widget.MaterialComponents.TextInputEditText` style an attribute like:
`<item name="android:textColor">?android:attr/textColorPrimary</item>`
It improves the readability of the style avoiding to navigate through the AppCompat Theme.

In general consider to override in the base material component theme the attribute
`<item name="editTextColor">?android:attr/textColorPrimary</item>`.
and/or matching the `android:attr/textColorPrimary` with a color defined in the Material Components Theme.
