### ISSUE TITLE
[BottomSheet] shapeAppearance darkens backgroundTint

### ISSUE THREAD

**Issue by Pitel** [material-components/material-components-android#777]
**Description:** When I set `shapeAppearance` attribute to the style, the `backgroundTint` color is darkened.

![Should be white!](https://user-images.githubusercontent.com/113248/69140856-b2082480-0ac3-11ea-9633-288103335238.png)

This should be white!

**Expected behavior:** The sheet keeps the defined `backgroundTint` color

**Source code:**
```xml
<style name="AppTheme.BottomSheet" parent="@style/Widget.Design.BottomSheet.Modal">
	<item name="android:background">#fff</item>
	<item name="backgroundTint">#fff</item>
	<item name="shapeAppearance">@style/ShapeAppearance.MaterialComponents.LargeComponent</item>
	<item name="shapeAppearanceOverlay">@style/ShapeAppearanceOverlay.MaterialComponents.BottomSheet</item>
</style>
```

**Android API version:** 29

**Material Library version:** 1.2.0-alpha01

**Device:** Pixel 3a

**Comment by hunterstich** [comment]
Hey Pitel, thanks for filing an issue.

Is this only happening in Android Studio's layout editor or is this happening when you run the app on an actual device/emulator? Any chance you can include a small sample app that reproduces the problem?

**Comment by Pitel** [comment]
Sample project: https://gitlab.com/Pitel/bottomsheet777/tree/master

I figured it has something to do with `colorSurface` and `colorOnSurface`.

Bonus question: Why, when I set `android:textColor` in my `AppTheme.BottomSheet` does it not affect `TextViews` inside my Bottom Sheer `FrameLayout`?

**Comment by hunterstich** [comment]
Okay so -

In dark themes, to support the idea of elevation we have a concept called _elevation overlays_. Since black shadows can't usually be seen in darkly themed apps, a dark surface is progressively lightened as its elevation increases to give it the visual effect of being raised in z-space. 

You can read more about elevation overlays at [material.io/design/color/dark-theme.html#properties](https://material.io/design/color/dark-theme.html#properties).

What's happening in your sample is your theme is set to `Theme.MaterialComponents` (a dark theme) and a bottom sheet is a component with an elevation, meaning it will be given an elevation overlay. The elevation overlay _color_ is by default set to `colorOnSurface`. Since your `colorOnSurface` is black, our library automatically takes that color, applies an alpha to it, and overlays it on top of your bottom sheet (which has a background of `colorSurface` - white in this case) combining to produce the grey you're seeing. 

There are a few ways to fix this, but the solution depends on whether you're trying to build a app with a  primarily light theme or primarily dark theme. If you're building an app with a primarily light theme, look into using `Theme.MaterialComponents.Light ` which does not apply elevation overlays by default.

Alternatively, If the rest of your app is dark and you need a one-off light bottom sheet, look into using a theme overlay and applying it to your bottom sheet's layout. There is some great info on theme overlays in this talk from [Android Developer Summit '19 - Developing Themes with Style](https://youtu.be/Owkf8DhAOSo).

As a last resort, you could turn off elevation overlays in your theme with `elevationOverlaysEnabled` or change the color of the elevation overlay with `elevationOverlayColor`. Both of these will effect all other elevated components in your app, not just your bottom sheet, and most likely point to the fact that you should consider using a different parent theme.

______

For your bonus question - you're applying a style to your bottom sheet's `FrameLayout`. If you want all of your FrameLayout's children to use different colors, you'd need to apply a theme overlay to your `FrameLayout` with `android:theme`.


Hopefully this clears things up!

**Comment by Pitel** [comment]
Thank you very much for explanation and the video!

So the main take-away for my app is that just because I have colorful background with pattern which results in mainly white text doesn't mean I should use dark theme as a base. :+1:
