### ISSUE TITLE
Add new `Dividers` component guidance

### ISSUE THREAD

**Issue by sfdexter** [material-components/material-components-android#78]
https://material.io/go/design-dividers

**Comment by garretyoder** [comment]
Is this widget supposed to use onSurface or onBackground as it's default background color by default? The material guidelines https://material.io/design/components/dividers.html are unclear on this. I can implement this since it's a quick few lines of code. Also, is this widget intended to have any intrinsic padding? Again, the guidelines left this out.

**Comment by ldjcmu** [comment]
Closing this issue as we have no plans to implement this in the library directly. For a divider, you should use a color depending upon the color of the container it is on top of.

**Comment by leticiarossi** [comment]
The divider component has been added to the library https://github.com/material-components/material-components-android/commit/782dffa8b719ff4129590380896d2619531906dc
