### ISSUE TITLE
[CoordinatorLayout] Ignoring cardBackgroundColor at MaterialCardView with BottomSheetBehavior&shapeAppearance 

### ISSUE THREAD

**Issue by hikkidev** [material-components/material-components-android#786]
**Description:** If MaterialCardView has `cardBackgroundColor` and `behavior=BottomSheetBehavior`, then when specifying `shapeAppearance`, `cardBackgroundColor` will be ignored

**Expected behavior:** 
![image](https://user-images.githubusercontent.com/52655010/69416117-79c54800-0d48-11ea-890c-7d3d0ae81df7.png)

**Actual behavior:**
![image](https://user-images.githubusercontent.com/52655010/69416146-8ba6eb00-0d48-11ea-9365-58258d9fe4b4.png)

**Source code:** 
```xml
<?xml version="1.0" encoding="utf-8"?>
<style name="AppShapeAppearance.TopCorners" parent="ShapeAppearance.MaterialComponents.MediumComponent">
     <item name="cornerFamily">rounded</item>
     <item name="cornerSizeTopRight">16dp</item>
     <item name="cornerSizeTopLeft">16dp</item>
     <item name="cornerSizeBottomRight">0dp</item>
     <item name="cornerSizeBottomLeft">0dp</item>
</style>

    <androidx.coordinatorlayout.widget.CoordinatorLayout
        android:layout_width="match_parent"
        android:layout_height="match_parent">

        <com.google.android.material.card.MaterialCardView
              android:layout_width="match_parent"
              android:layout_height="wrap_content"
              app:cardBackgroundColor="@color/red650"
              app:shapeAppearance="@style/AppShapeAppearance.TopCorners"
              app:layout_behavior="com.google.android.material.bottomsheet.BottomSheetBehavior">

                     <com.google.android.material.textview.MaterialTextView ... />

         </com.google.android.material.card.MaterialCardView>
    </androidx.coordinatorlayout.widget.CoordinatorLayout>

```

**Android API version:** API 28 (Android 9.0)

**Material Library version:** 1.1.0-beta02, 1.2.0-alpha02

**Device:** Xiaomi MI A1

**Comment by hunterstich** [comment]
Hey there. Thanks for taking the time to file an issue.

Your card is probably inflated and styled correctly with your red background but then overridden when `BottomSheetBehavior` applies it's styling to the view on which it is set (in this case, your Card). Bottom sheet, by default, sets its background to your theme's `android:colorBackground` color. You can change this at the View level by setting `app:backgroundTint` on the same view where your `BottomSheetBehavior` is applied. 

As a side note, is there a reason you need to use a Card instead of something more generic like a FrameLayout? A Card is basically a FrameLayout that's given corner shape and elevation. When you apply `BottomSheetBehavior` to a view in conjunction with a bottom sheet style, the behavior applies a similar styling (corner shaping and elevation) to the view on which it is set. This handles a lot of things for you out-of-the-box including setting the bottom left and right corners to 0dp as you've done manually with `AppShapeAppearance.TopCorners`. 

You could change what you have to something like:

```
   <!--Your app's theme-->
    <style name="MyTheme" parent="Theme.MaterialComponents.DayNight">
        <item name="shapeAppearanceLargeComponent">@style/ShapeAppearance.MyApp.LargeComponent</item>
        <item name="bottomSheetStyle">@style/Widget.MyApp.BottomSheet</item>
    </style>

   <!--Your app's large shape appearance-->
    <style name="ShapeAppearance.MyApp.LargeComponent" parent="ShapeAppearance.MaterialComponents.LargeComponent">
        <item name="cornerSize">16dp</item>
    </style>

    <!--Your app's bottom sheet style-->
    <style name="Widget.MyApp.BottomSheet" parent="Widget.MaterialComponents.BottomSheet">
        <item name="backgroundTint">@android:color/holo_red_dark</item>
    </style>
```

and in your layout:
```
    <FrameLayout
        style="?attr/bottomSheetStyle"
        android:layout_width="match_parent"
        android:layout_height="wrap_content"
       ....
        app:layout_behavior="@string/bottom_sheet_behavior">

        <!--Bottom sheet content-->

    </FrameLayout>
```

The above will create a persistent bottom sheet with the top left and right corners rounded at 16dp ([0dp for bottom left and right corners](https://github.com/material-components/material-components-android/blob/master/lib/java/com/google/android/material/bottomsheet/res/values/styles.xml#L47)) and a red background:

<img src="https://user-images.githubusercontent.com/7459254/69480561-4b358480-0dbd-11ea-980c-2b72ba5e80b9.png"  height="400" />

Hope this helps. Going ahead and closing this but feel free to respond and reopen if this doesn't solve your question.

**Comment by Ekalips** [comment]
Hi @hunterstich 
It would be good to have a programmatic way to do it. Or at least to disable the BottomSheetBehaviour background replacement
