### ISSUE TITLE
[Slider] Add keyboard control and accessibility

### ISSUE THREAD

**Issue by Sourav-21** [material-components/material-components-android#827]
**Is your feature request related to a problem? Please describe.**
By pressing + and - and we can control progress in `SeekBar`. But there is no such functionality here. And if the talkback is on it should tell it's current progress.

**Comment by cketcham** [comment]
Generally it should match the behavior of `SeekBar.class`. I think we might be able to set the a11y class name to `SeekBar` and get some things for free.

It should add actions to scroll forwards and backwards for the thumb.

It gets a little trickier once support for multiple thumbs becomes possible since we'll need a way to navigate between thumbs, select a thumb, scroll forwards and backwards, and then unselect the thumb.
