### ISSUE TITLE
Stuck in alpha-beta forever?

### ISSUE THREAD

**Issue by valeriyo** [material-components/material-components-android#829]
It would be great to have a non-alpha/beta release, you know? It just doesn't inspire confidence when there are 10 alphas + multiple betas, and the next version already starts with an alpha. What's the problem, guys?

**Comment by MGaetan89** [comment]
Version 1.1.x hasn't reach stable yet because it was dependant on alpha/beta version of other AndroidX artefacts. Now all dependencies have reached stable releases, and the Material team is planning a RC version next (see https://github.com/material-components/material-components-android/commit/a4b90321e32e1dbc0414958bea14a28f9fe68e14#commitcomment-36070353). So I guess that the stable version of the 1.1 branch is not too far now, if no major issues are found during the RC.
As for the 1.2 branch, it includes new components and features, so it is not surprising that it is in alpha.

**Comment by dsn5ft** [comment]
Thanks @MGaetan89, that's all accurate. We're planning on moving 1.1.0 to RC very soon, and then stable (hopefully) shortly after that.
