### ISSUE TITLE
[MaterialCalendar] Color surface not being applied properly

### ISSUE THREAD

**Issue by jgavazzisp** [material-components/material-components-android#838]
**Description:** Full description of the issue here
When a custom theme for the DatePicker is used, **"colorSurface"** is ignored despite the fact of **"colorPrimary"**, **"colorOnPrimary"** and **"colorOnSurface"** working properly.

**Expected behaviour:** Screenshots and/or description of expected behaviour
Attribute **"colorSurface"** from overwritten DatePicker theme should be used instead of the main theme **"colorSurface"**.

**Source code:** 
![image](https://user-images.githubusercontent.com/309389/71050616-881d4d00-21aa-11ea-8090-0377d74f4eda.png)

**Android API version:** 29

**Material Library version:** 1.2.0-alpha02

**Device:** Pixel 3 XL

**Comment by dsn5ft** [comment]
Thanks for reporting this issue. My guess is that this is because we're calling `getContext()` again to read the `colorSurface` attribute, instead of using the `Dialog`'s context which is wrapped using the DatePicker theme:

https://github.com/material-components/material-components-android/blob/master/lib/java/com/google/android/material/datepicker/MaterialDatePicker.java#L167

I'll verify that that's the issue and submit a fix soon.
