### ISSUE TITLE
[CheckBox] require tristate checkbox

### ISSUE THREAD

**Issue by autthapol-k** [material-components/material-components-android#857]
require tristate checkbox like flutter [here](https://api.flutter.dev/flutter/material/Checkbox/tristate.html)

**Comment by Anigif** [comment]
I wouldn't mind trying to make a PR for this, but it would be nice to have an idea about what the solution should be.

A simple solution could be to just add an extra boolean property representing if the the checkbox is in the indeterminate state or not. This is how it looks like it's done at least in the web implementation. I however haven't had a chance to figure out how the flow is if you click the checkbox in indeterminate state. And the [Flutter demo](https://dartpad.dev/embed-flutter.html?gh_owner=material-components&gh_repo=material-components-flutter&gh_path=docs/components/dartpad/checkboxes/regular&gh_ref=develop) for sure shows something else than I would imagine the flow would be.

My suggestion to the new state is as follows:

**Visual representation:**
I would imagine the `indeterminate` state overrule the `checked` state.
```
checked: false / indeterminate: false => empty checkbox
checked: true  / indeterminate: false => checkbox with check mark
checked: false / indeterminate: true  => checkbox with line (indeterminate state)
checked: true  / indeterminate: true  => checkbox with line (indeterminate state)
```

**Clicked reaction:**
The simplest solution would just be to set the `indeterminate` state to false and toggle the `checked` state. This is due to it doesn't make too much sense to click into indeterminate state as the checkbox should be based on its "children" and not the other way around. Furthermore it simplifies `setOnCheckedChangeListener` as nothing needs to be changed.
```
checked: false / indeterminate: false => checked: true  / indeterminate: false
checked: true  / indeterminate: false => checked: false / indeterminate: false
checked: false / indeterminate: true  => checked: true  / indeterminate: false
checked: true  / indeterminate: true  => checked: false / indeterminate: false
```

**Comment by TarekkMA** [comment]
Any update on this issue?

**Comment by drchen** [comment]
I think this makes sense given that it's sort of a Web standard. 

However given that it's a huge design change, and we may need to coordinate with all other platforms than Android.
I'll raise this to the team and see what they thinks.

**Comment by leticiarossi** [comment]
we're currently working on updating the material checkbox to include the indeterminate state!
