### ISSUE TITLE
[ShapeableImageView] Issue loading GIFs with Glide. No issue with images.

### ISSUE THREAD

**Issue by ocarey** [material-components/material-components-android#890]
Issues with: 

```
Glide.with(itemView).asGif().load(item.gifPath).into(thumbnailImageView)
```

No issues with:

```
Glide.with(itemView).load(item.thumbnailPath).into(thumbnailImageView)
```

Tested on 3 Android devices & simulator. 

Love this new component! Will be perfect with GIFs working. Thank you!

**Comment by ocarey** [comment]
Full Code:

```
private val thumbnailImageView = itemView.findViewById<ShapeableImageView>(R.id.thumbnail_image_view)
Glide.with(itemView).asGif().load(item.gifPath).into(thumbnailImageView)
```

```
<com.google.android.material.imageview.ShapeableImageView
            android:id="@+id/thumbnail_image_view"
            android:layout_width="match_parent"
            android:layout_height="match_parent"
            android:adjustViewBounds="true"
            android:scaleType="centerCrop"
            app:shapeAppearanceOverlay="@style/ShapeAppearance.AppTheme.MediumComponent" />
```

**Comment by pekingme** [comment]
Hi @ocarey, glad to hear you love it. Could you please provide more details about what the issues are? A sample app can reproduce the issues will let us identify the problem much easier. Thanks.

**Comment by ocarey** [comment]
Definitely. Here's the sample project: https://github.com/ocarey/ShapeableImageView-GIFs

Shapeable & App Compat Image Views work fine with Glide & static images:
![Screenshot_1578615062](https://user-images.githubusercontent.com/37121709/72115085-a7ffe680-32fa-11ea-9a13-8aebb650ff08.png)

However, Shapeable Image View won't render the Gif with Glide:
![Screenshot_1578614722](https://user-images.githubusercontent.com/37121709/72114986-345dd980-32fa-11ea-8361-1af39d9243d7.png)

Looks like it's falling into this conditional statement in onDraw():
```
// only supporting BitmapDrawable for now.
if (!(getDrawable() instanceof BitmapDrawable)) {
   Log.e(TAG, "Shapeable Image view does not support the provided drawable. "
      + "Only BitmapDrawble is supported");
   return;
}
```

Thank you!

**Comment by ymarian** [comment]
Hey @ocarey thanks for the example it helps a lot.

I made a fix but I forgot with Glide you actually get GIFs to animate on image views. Since they have a custom GifDrawable. I have no idea about the performance. Can you try it and let me know if you see any issues? I think I might need to cache the bitmap and keep drawing there. 

We have nightly snapshot releases. So the first fix should be included here:

https://github.com/material-components/material-components-android/packages/81484?version=1.2.0-dev-20200112

To start using it you need to create a GitHub access token, and add the following to your build.gradle Maven repositories:

        maven {
            name = "MaterialSnapshots"
            url = uri("https://maven.pkg.github.com/material-components/material-components-android")
            credentials {
                username = <github_username>
                password = <github_access_token>
            }
        }
Then you can use the com.google.android.material:material:1.2.0-dev-20200112 dependency as per usual (more info [here](https://help.github.com/en/github/managing-packages-with-github-packages/configuring-gradle-for-use-with-github-packages)).

If you want to test the animation you can add this workaround too, but it will probably not work very well: 

```kt
package com.owencarey.shapeableimageviewgifs

import android.annotation.SuppressLint
import android.content.Context
import android.util.AttributeSet
import com.google.android.material.imageview.ShapeableImageView

@SuppressLint("UnsafeExperimentalUsageError")
class ShapeableImageView2 @JvmOverloads constructor(
    context: Context, attrs: AttributeSet? = null, defStyleAttr: Int = 0
) : ShapeableImageView(context, attrs, defStyleAttr) {


    override fun invalidate() {
        super.invalidate()
        setImageDrawable(drawable)
    }
}
```
