### ISSUE TITLE
[ShapePath] Add support for cubicToPoint

### ISSUE THREAD

**Issue by mathroule** [material-components/material-components-android#924]
**Is your feature request related to a problem? Please describe.**
It's not possible to use method [Path#cubicTo](https://developer.android.com/reference/android/graphics/Path#cubicTo(float,%20float,%20float,%20float,%20float,%20float)) to draw cubic bezier.

**Describe the solution you'd like**
ShapePath should support cubic path calling `Path#cubicTo` method.
```
  /**
   * Add a cubic to the ShapePath.
   *
   * @param controlX1 the 1st control point x of the arc.
   * @param controlY1 the 1st control point y of the arc.
   * @param controlX2 the 2nd control point x of the arc.
   * @param controlY2 the 2nd control point y of the arc.
   * @param toX the end x of the arc.
   * @param toY the end y of the arc.
   */
  public void cubicToPoint(float controlX1, float controlY1, float controlX2, float controlY2, float toX, float toY) {
    PathCubicOperation operation = new PathCubicOperation(controlX1, controlY1, controlX2, controlY2, toX, toY);
    operations.add(operation);
    ...
  }
```

```
  /** Path cubic operation. */
  public static class PathCubicOperation extends PathOperation {

    private float controlX1;

    private float controlY1;

    private float controlX2;

    private float controlY2;

    private float endX;

    private float endY;

    public PathCubicOperation(float controlX1, float controlY1, float controlX2, float controlY2, float endX, float endY) {
      setControlX1(controlX1);
      setControlY1(controlY1);
      setControlX2(controlX2);
      setControlY2(controlY2);
      setEndX(endX);
      setEndY(endY);
    }

    @Override
    public void applyToPath(@NonNull Matrix transform, @NonNull Path path) {
      Matrix inverse = matrix;
      transform.invert(inverse);
      path.transform(inverse);
      path.cubicTo(controlX1, controlY1, controlX2, controlY2, endX, endY);
      path.transform(transform);
    }

    private float getControlX1() {
      return controlX1;
    }

    private void setControlX1(float controlX1) {
      this.controlX1 = controlX1;
    }

    private float getControlY1() {
      return controlY1;
    }

    private void setControlY1(float controlY1) {
      this.controlY1 = controlY1;
    }

    private float getControlX2() {
      return controlX2;
    }

    private void setControlX2(float controlX2) {
      this.controlX2 = controlX2;
    }

    private float getControlY2() {
      return controlY1;
    }

    private void setControlY2(float controlY2) {
      this.controlY2 = controlY2;
    }

    private float getEndX() {
      return endX;
    }

    private void setEndX(float endX) {
      this.endX = endX;
    }

    private float getEndY() {
      return endY;
    }

    private void setEndY(float endY) {
      this.endY = endY;
    }
  }
```

I don't know how to define a `CubicShadowOperation`.

**Describe alternatives you've considered**
I was not able to achieve cubic bezier using `ShapePath#quadToPoint` or `ShapePath#addArc`.

**Additional context**
None

**Comment by cketcham** [comment]
We could add support for cubicToPoint() paths, however, because of the way gradients can be rendered on Android (either linear or radial) it means we can only add compat shadows (required on API < 21 or before Q if concave) that follow a line or an arc.

A few possible solutions. Add support for cubic beziers but:

- document that it won't have shadows unless API > 21 with convex shape, or >= Q if concave.
- approximate the quadradic and cubic curves with arcs and use that to draw the shadow (Not sure if there will be performance impact, or visual artifacts)
- Change the way shadows are drawn to use a different method like blurring (May result in a differently looking shadow)

I'm not sure what the best option is. And we haven't had that many requests for curves other than arcs so we haven't done anything yet.
