### ISSUE TITLE
[BottomSheetDialog] cornerSize** attribute not supported

### ISSUE THREAD

**Issue by Ghedeon** [material-components/material-components-android#954]
**Description:** 
When shape theming `BottomSheetDialogFragment` (according to https://github.com/material-components/material-components-android/blob/master/docs/theming/Shape.md), seems like `cornerSize` alone is respected but none of `cornerSizeTopLeft`, `cornerSizeTopRight`, `cornerSizeBottomRight`, `cornerSizeBottomLeft` has any visual effect.

**Expected behavior:** shape theming of the individual corner should work

**Android API version:** 23

**Material Library version:** `1.2.0-alpha04`

**Device:** OnePlus 5T

**Comment by ikim24** [comment]
cornerSizeTopLeft and cornerSizeTopRight should work as expected (note: when the bottom sheet is fully expanded, the corners will no longer be shaped to indicate that the bottom sheet is fully expanded).

I believe bottom corner shaping is not supported because the bottom sheet should go all the way to the bottom of the screen.
