### ISSUE TITLE
[BottomAppBar] With a negative fabCradleVerticalOffset the app crashes

### ISSUE THREAD

**Issue by gabrielemariotti** [material-components/material-components-android#957]
**Description:** 
Using the `BottomAppBar` with a negative `fabCradleVerticalOffset` value the app crashes.

**Expected behavior:** 
It would be nice to have the possibility to use a negative offset.
In any case it is appropriate to avoid the crash.

**Source code:** 

```
  <com.google.android.material.bottomappbar.BottomAppBar
      android:id="@+id/bottom_app_bar"
      app:fabCradleVerticalOffset="-8dp"
     ..>
```

**Material Library version:** 1.1.0-rc02 and 1.2.0-alpha04

**Comment by pavlospt** [comment]
Seems that this was an explicit decision: https://github.com/material-components/material-components-android/commit/6e340c49d4b2c61c9d9811542ce81aac9d822586

**Comment by ikim24** [comment]
As @pavlospt pointed out, disallowing negative values was an intentional decision. We currently do not support negative values and currently have no plans to support negative values.

We would be open to a PR for supporting negative values that would draw the cutout correctly, so I'm leaving this open as a feature request.

As long as we do not support negative values, we are planning to keep the exception (as opposed to having unknown behavior of drawing the cutout).

**Comment by drchen** [comment]
Per what @ikim24 said, closing the issue for now....
