### ISSUE TITLE
Enhancement - Add FAB support to bottom navigation

### ISSUE THREAD

**Issue by sedestrian** [material-components/material-components-android#98]
It would be great if you could add support for inset / attached fabs to the bottom navigation, making the items wrap around the FAB. Kinda like this

<img width="382" alt="screen shot 2018-05-09 at 20 39 41" src="https://user-images.githubusercontent.com/1345755/39833033-39a78402-53c9-11e8-8d9c-7f1e6e6f477b.png">

But with the new material components bottom app bar styling

**Comment by kioba** [comment]
We are looking into implementing the same functionality and happy to contribute our solution

**Comment by cketcham** [comment]
This is definitely something people bring up often! We haven't done any studies to determine how this will effect users. Since we don't know, for now we can't include it by default in the library.

When we finish shape theming (which should be done by the end of this quarter) it might be possible to set a `MaterialShapeDrawable` background on the BottomNavigationView and have it react to the background of the fab to draw a cutout in a similar way to BottomAppBar. Since that's not a primary use case for us, we won't be ensuring it will work, but based on our discussions of shape theming so far I think it should be possible?

**Comment by sedestrian** [comment]
Oh ok then, i'll be waiting for shape theming :) Thank you for the answer

**Comment by varunam** [comment]
Hey, any solution on this? adding fab to bottom navigation...
